package com.ff.domain.organization;

import com.capgemini.lbs.framework.domain.CGMasterDO;




//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : FirstFlight
//  @ File Name : OfficeTypeDO.java
//  @ Date : 10/4/2012
//  @ Author : 





public class OfficeTypeDO extends CGMasterDO 
{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2320335590759299485L;
	private Integer offcTypeId;
	private String offcTypeCode;
	private String offcTypeDesc;
	private String aaplicableForDispatch;
	  
  /**
	 * @return the offcTypeId
	 */
	public Integer getOffcTypeId() {
		return offcTypeId;
	}
	/**
	 * @param offcTypeId the offcTypeId to set
	 */
	public void setOffcTypeId(Integer offcTypeId) {
		this.offcTypeId = offcTypeId;
	}
	/**
	 * @return the offcTypeCode
	 */
	public String getOffcTypeCode() {
		return offcTypeCode;
	}
	/**
	 * @param offcTypeCode the offcTypeCode to set
	 */
	public void setOffcTypeCode(String offcTypeCode) {
		this.offcTypeCode = offcTypeCode;
	}
	/**
	 * @return the offcTypeDesc
	 */
	public String getOffcTypeDesc() {
		return offcTypeDesc;
	}
	/**
	 * @param offcTypeDesc the offcTypeDesc to set
	 */
	public void setOffcTypeDesc(String offcTypeDesc) {
		this.offcTypeDesc = offcTypeDesc;
	}
	
	public String getAaplicableForDispatch() {
		return aaplicableForDispatch;
	}
	public void setAaplicableForDispatch(String aaplicableForDispatch) {
		this.aaplicableForDispatch = aaplicableForDispatch;
	}
}
