package com.firstflight.sd.csdtosap.contract;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-01-08T19:20:25.919+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/SD/CSDToSAP/Contract", name = "SI_CSD_Contract_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDContractOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_Contract_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDContractOut(
        @WebParam(partName = "MT_CSD_Contract", name = "MT_CSD_Contract", targetNamespace = "http://FirstFlight.com/SD/CSDToSAP/Contract")
        DTCSDContract mtCSDContract
    );
}
