
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.sd.csdtosap.contract;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-01-08T19:20:25.903+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_Contract_OutService",
                      portName = "SI_CSD_Contract_OutPort",
                      targetNamespace = "http://FirstFlight.com/SD/CSDToSAP/Contract",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FSD%2FCSDToSAP%2FContract%5ESI_CSD_Contract_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                      endpointInterface = "com.firstflight.sd.csdtosap.contract.SICSDContractOut")
                      
public class SICSDContractOutImpl implements SICSDContractOut {

	/** The logger. */
	private final static Logger LOG = LoggerFactory
			.getLogger(SICSDContractOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.sd.csdtosap.contract.SICSDContractOut#siCSDContractOut(com.firstflight.sd.csdtosap.contract.DTCSDContract  mtCSDContract )*
     */
    public void siCSDContractOut(DTCSDContract mtCSDContract) { 
        LOG.info("Executing operation siCSDContractOut");
        LOG.debug("mtCSDContract::"+mtCSDContract);
        try {
        } catch (java.lang.Exception ex) {
        	LOG.error("SICSDContractOutImpl::siCSDContractOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
