
package com.firstflight.sd.csdtosap.contract;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-01-08T19:20:25.794+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDContractOut_SICSDContractOutPort_Client {
	
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDContractOut_SICSDContractOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/SD/CSDToSAP/Contract", "SI_CSD_Contract_OutService");

    private SICSDContractOut_SICSDContractOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDContractOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDContractOut_SICSDContractOutPort_Client::main::error::",e);
            }
        }
      
        SICSDContractOutService ss = new SICSDContractOutService(wsdlURL, SERVICE_NAME);
        SICSDContractOut port = ss.getSICSDContractOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDContractOut...");
        com.firstflight.sd.csdtosap.contract.DTCSDContract _siCSDContractOut_mtCSDContract = new com.firstflight.sd.csdtosap.contract.DTCSDContract();
        java.util.List<com.firstflight.sd.csdtosap.contract.DTCSDContract.Contract> _siCSDContractOut_mtCSDContractContract = new java.util.ArrayList<com.firstflight.sd.csdtosap.contract.DTCSDContract.Contract>();
        com.firstflight.sd.csdtosap.contract.DTCSDContract.Contract _siCSDContractOut_mtCSDContractContractVal1 = new com.firstflight.sd.csdtosap.contract.DTCSDContract.Contract();
        _siCSDContractOut_mtCSDContractContractVal1.setTimestamp("Timestamp335940460");
        _siCSDContractOut_mtCSDContractContractVal1.setSAPStatus("SAPStatus408264286");
        _siCSDContractOut_mtCSDContractContractVal1.setContractNo("ContractNo-107727350");
        _siCSDContractOut_mtCSDContractContractVal1.setCustomerNo("CustomerNo-1874071527");
        _siCSDContractOut_mtCSDContractContractVal1.setSalesOfficeCode("SalesOfficeCode-1405941606");
        _siCSDContractOut_mtCSDContractContractVal1.setSalesPersonCode("SalesPersonCode-697065279");
        _siCSDContractOut_mtCSDContractContractVal1.setIndustryTypeCode("IndustryTypeCode-404340500");
        _siCSDContractOut_mtCSDContractContractVal1.setCustomerGroup("CustomerGroup1243247596");
        _siCSDContractOut_mtCSDContractContractVal1.setDistChannel("DistChannel-944603205");
        _siCSDContractOut_mtCSDContractContractVal1.setGroupKey("GroupKey795964854");
        _siCSDContractOut_mtCSDContractContractVal1.setCustName("CustName-555336092");
        _siCSDContractOut_mtCSDContractContractVal1.setAddress1("Address1-1739513769");
        _siCSDContractOut_mtCSDContractContractVal1.setAddress2("Address2-756315599");
        _siCSDContractOut_mtCSDContractContractVal1.setAddress3("Address3998290323");
        _siCSDContractOut_mtCSDContractContractVal1.setCity("City-2083852529");
        _siCSDContractOut_mtCSDContractContractVal1.setPincode("Pincode-2061535186");
        _siCSDContractOut_mtCSDContractContractVal1.setState("State1897186478");
        com.firstflight.sd.csdtosap.contract.DTCSDContract.Contract.PrimaryContact _siCSDContractOut_mtCSDContractContractVal1PrimaryContact = new com.firstflight.sd.csdtosap.contract.DTCSDContract.Contract.PrimaryContact();
        _siCSDContractOut_mtCSDContractContractVal1PrimaryContact.setTitle("Title-1651516987");
        _siCSDContractOut_mtCSDContractContractVal1PrimaryContact.setPersonName("PersonName1904286811");
        _siCSDContractOut_mtCSDContractContractVal1PrimaryContact.setEmail("Email-647787590");
        _siCSDContractOut_mtCSDContractContractVal1PrimaryContact.setContactNo("ContactNo27175693");
        _siCSDContractOut_mtCSDContractContractVal1PrimaryContact.setExtention("Extention1602478615");
        _siCSDContractOut_mtCSDContractContractVal1PrimaryContact.setMobile("Mobile-1738438015");
        _siCSDContractOut_mtCSDContractContractVal1PrimaryContact.setFax("Fax-109890152");
        _siCSDContractOut_mtCSDContractContractVal1.setPrimaryContact(_siCSDContractOut_mtCSDContractContractVal1PrimaryContact);
        com.firstflight.sd.csdtosap.contract.DTCSDContract.Contract.SecondaryContact _siCSDContractOut_mtCSDContractContractVal1SecondaryContact = new com.firstflight.sd.csdtosap.contract.DTCSDContract.Contract.SecondaryContact();
        _siCSDContractOut_mtCSDContractContractVal1SecondaryContact.setTitle("Title1221025119");
        _siCSDContractOut_mtCSDContractContractVal1SecondaryContact.setPersonName("PersonName-2103238092");
        _siCSDContractOut_mtCSDContractContractVal1SecondaryContact.setEmail("Email536843698");
        _siCSDContractOut_mtCSDContractContractVal1SecondaryContact.setContactNo("ContactNo-1354645023");
        _siCSDContractOut_mtCSDContractContractVal1SecondaryContact.setExtention("Extention-1560468925");
        _siCSDContractOut_mtCSDContractContractVal1SecondaryContact.setMobile("Mobile1594769770");
        _siCSDContractOut_mtCSDContractContractVal1SecondaryContact.setFax("Fax1126690448");
        _siCSDContractOut_mtCSDContractContractVal1.setSecondaryContact(_siCSDContractOut_mtCSDContractContractVal1SecondaryContact);
        _siCSDContractOut_mtCSDContractContractVal1.setBillingCycle("BillingCycle102130571");
        _siCSDContractOut_mtCSDContractContractVal1.setPaymentTerms("PaymentTerms1865824890");
        _siCSDContractOut_mtCSDContractContractVal1.setPlantCode("PlantCode934037168");
        _siCSDContractOut_mtCSDContractContractVal1.setTANNo("TANNo-1012258337");
        _siCSDContractOut_mtCSDContractContractVal1.setSalesDistrict("SalesDistrict1080695822");
        _siCSDContractOut_mtCSDContractContractVal1.setPANNo("PANNo-541468231");
        _siCSDContractOut_mtCSDContractContractVal1.setStatus("Status-356842774");
        _siCSDContractOut_mtCSDContractContract.add(_siCSDContractOut_mtCSDContractContractVal1);
        _siCSDContractOut_mtCSDContract.getContract().addAll(_siCSDContractOut_mtCSDContractContract);
        port.siCSDContractOut(_siCSDContractOut_mtCSDContract);


        }

        System.exit(0);
    }

}
