
package com.firstflight.fi.csdtosap.codlcliability;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-05-14T20:43:18.022+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDCODLCLiabilityOut_SICSDCODLCLiabilityOutPort_Client {
	
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDCODLCLiabilityOut_SICSDCODLCLiabilityOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/FI/CSDToSAP/CODLCLiability", "SI_CSD_CODLCLiability_OutService");

    private SICSDCODLCLiabilityOut_SICSDCODLCLiabilityOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDCODLCLiabilityOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDCODLCLiabilityOut_SICSDCODLCLiabilityOutPort_Client::main::error::",e);
            }
        }
      
        SICSDCODLCLiabilityOutService ss = new SICSDCODLCLiabilityOutService(wsdlURL, SERVICE_NAME);
        SICSDCODLCLiabilityOut port = ss.getSICSDCODLCLiabilityOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDCODLCLiabilityOut...");
        com.firstflight.fi.csdtosap.codlcliability.DTCSDCODLCLiability _siCSDCODLCLiabilityOut_mtCSDCODLCLiability = new com.firstflight.fi.csdtosap.codlcliability.DTCSDCODLCLiability();
        java.util.List<com.firstflight.fi.csdtosap.codlcliability.DTCSDCODLCLiability.CODLCLiability> _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiability = new java.util.ArrayList<com.firstflight.fi.csdtosap.codlcliability.DTCSDCODLCLiability.CODLCLiability>();
        com.firstflight.fi.csdtosap.codlcliability.DTCSDCODLCLiability.CODLCLiability _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1 = new com.firstflight.fi.csdtosap.codlcliability.DTCSDCODLCLiability.CODLCLiability();
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1.setTransactionNo("TransactionNo-740719841");
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-05-14T20:43:18.179+05:30"));
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1.setCustomerCode("CustomerCode-92737141");
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1.setChequeDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-05-14T20:43:18.179+05:30"));
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1.setChequeNo("ChequeNo-252744699");
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1.setChequeBankName("ChequeBankName834895766");
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1.setBankGLCode("BankGLCode-1827554107");
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1.setAmount("Amount1855512390");
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1.setSAPStatus("SAPStatus1490335241");
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1.setTimestamp("Timestamp92976134");
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiability.add(_siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiabilityVal1);
        _siCSDCODLCLiabilityOut_mtCSDCODLCLiability.getCODLCLiability().addAll(_siCSDCODLCLiabilityOut_mtCSDCODLCLiabilityCODLCLiability);
        port.siCSDCODLCLiabilityOut(_siCSDCODLCLiabilityOut_mtCSDCODLCLiability);


        }

        System.exit(0);
    }

}
