
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.fi.csdtosap.codlcliability;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-05-14T20:43:18.194+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_CODLCLiability_OutService",
                      portName = "SI_CSD_CODLCLiability_OutPort",
                      targetNamespace = "http://FirstFlight.com/FI/CSDToSAP/CODLCLiability",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FFI%2FCSDToSAP%2FCODLCLiability%5ESI_CSD_CODLCLiability_Out&QualityOfService=ExactlyOnce&sap-user=cg-pi&sap-password=gouri1",
                      endpointInterface = "com.firstflight.fi.csdtosap.codlcliability.SICSDCODLCLiabilityOut")
                      
public class SICSDCODLCLiabilityOutImpl implements SICSDCODLCLiabilityOut {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDCODLCLiabilityOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.fi.csdtosap.codlcliability.SICSDCODLCLiabilityOut#siCSDCODLCLiabilityOut(com.firstflight.fi.csdtosap.codlcliability.DTCSDCODLCLiability  mtCSDCODLCLiability )*
     */
    public void siCSDCODLCLiabilityOut(DTCSDCODLCLiability mtCSDCODLCLiability) { 
    	LOGGER.info("Executing operation siCSDCODLCLiabilityOut");
        LOGGER.debug("mtCSDCODLCLiability is="+mtCSDCODLCLiability);
        try {
        } catch (java.lang.Exception ex) {
        	LOGGER.error("SICSDCODLCLiabilityOutImpl::siCSDCODLCLiabilityOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
