
package com.firstflight.mm.csdtosap.purchasereq;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-08-28T17:44:18.549+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDPurchaseRequisitionOut_SICSDPurchaseRequisitionOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDPurchaseRequisitionOut_SICSDPurchaseRequisitionOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/MM/CSDToSAP/PurchaseRequisition", "SI_CSD_PurchaseRequisition_OutService");

    private SICSDPurchaseRequisitionOut_SICSDPurchaseRequisitionOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDPurchaseRequisitionOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDPurchaseRequisitionOut_SICSDPurchaseRequisitionOutPort_Client::main::error::",e);
            }
        }
      
        SICSDPurchaseRequisitionOutService ss = new SICSDPurchaseRequisitionOutService(wsdlURL, SERVICE_NAME);
        SICSDPurchaseRequisitionOut port = ss.getSICSDPurchaseRequisitionOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDPurchaseRequisitionOut...");
        com.firstflight.mm.csdtosap.purchasereq.DTCSDPurchaseRequisition _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisition = new com.firstflight.mm.csdtosap.purchasereq.DTCSDPurchaseRequisition();
        java.util.List<com.firstflight.mm.csdtosap.purchasereq.DTCSDPurchaseRequisition.PurchaseRequisition> _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisition = new java.util.ArrayList<com.firstflight.mm.csdtosap.purchasereq.DTCSDPurchaseRequisition.PurchaseRequisition>();
        com.firstflight.mm.csdtosap.purchasereq.DTCSDPurchaseRequisition.PurchaseRequisition _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1 = new com.firstflight.mm.csdtosap.purchasereq.DTCSDPurchaseRequisition.PurchaseRequisition();
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setTimestamp("Timestamp1138776707");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setSAPStatus("SAPStatus-241166845");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setROWNUMBER(new java.math.BigInteger("-64362708665230138278046381163118235197"));
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setREQUISITIONOFFICECODE("REQUISITIONOFFICECODE1837890075");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setREQCREATEDDATETIME(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-07-17T09:49:33.615+05:30"));
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setREQUISITIONNUMBER("REQUISITIONNUMBER236537914");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setITEMCODE("ITEMCODE-2110729359");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setITEMTYPECODE("ITEMTYPECODE1988769973");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setDESCRIPTION("DESCRIPTION-307126321");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setUOM("UOM1484250144");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setAPPROVEDQUANTITY("APPROVEDQUANTITY422393705");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setProcurementType("ProcurementType-108500759");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setSerierStartsWith("SerierStartsWith-1384690511");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisition.add(_siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1);
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisition.getPurchaseRequisition().addAll(_siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisition);
        port.siCSDPurchaseRequisitionOut(_siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisition);


        }

        System.exit(0);
    }

}
