
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.mm.csdtosap.purchasereq;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-08-28T17:44:18.658+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_PurchaseRequisition_OutService",
                      portName = "SI_CSD_PurchaseRequisition_OutPort",
                      targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/PurchaseRequisition",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FPurchaseRequisition%5ESI_CSD_PurchaseRequisition_Out&QualityOfService=ExactlyOnce&sap-user=cg-pi&sap-password=gouri1",
                      endpointInterface = "com.firstflight.mm.csdtosap.purchaserequisition.SICSDPurchaseRequisitionOut")
                      
public class SICSDPurchaseRequisitionOutImpl implements SICSDPurchaseRequisitionOut {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDPurchaseRequisitionOutImpl.class);
    /* (non-Javadoc)
     * @see com.firstflight.mm.csdtosap.purchaserequisition.SICSDPurchaseRequisitionOut#siCSDPurchaseRequisitionOut(com.firstflight.mm.csdtosap.purchaserequisition.DTCSDPurchaseRequisition  mtCSDPurchaseRequisition )*
     */
    public void siCSDPurchaseRequisitionOut(DTCSDPurchaseRequisition mtCSDPurchaseRequisition) { 
    	LOGGER.info("Executing operation siCSDPurchaseRequisitionOut");
    	  LOGGER.debug("mtCSDPurchaseRequisition::"+mtCSDPurchaseRequisition);
        try {
        } catch (java.lang.Exception ex) {
        	LOGGER.error("SICSDPurchaseRequisitionOutImpl::siCSDPurchaseRequisitionOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
