package com.firstflight.mm.csdtosap.purchasereq;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-08-28T17:44:18.690+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/PurchaseRequisition", name = "SI_CSD_PurchaseRequisition_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDPurchaseRequisitionOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_PurchaseRequisition_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDPurchaseRequisitionOut(
        @WebParam(partName = "MT_CSD_PurchaseRequisition", name = "MT_CSD_PurchaseRequisition", targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/PurchaseRequisition")
        DTCSDPurchaseRequisition mtCSDPurchaseRequisition
    );
}
