package com.firstflight.fi.csdtosap.collectionentries;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-05-09T19:23:37.777+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/FI/CSDToSAP/CollectionEntries", name = "SI_CSD_CollectionEntries_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDCollectionEntriesOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_CollectionEntries_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDCollectionEntriesOut(
        @WebParam(partName = "MT_CSD_CollectionEntries", name = "MT_CSD_CollectionEntries", targetNamespace = "http://FirstFlight.com/FI/CSDToSAP/CollectionEntries")
        DTCSDCollectionEntries mtCSDCollectionEntries
    );
}
