
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.mm.csdtosap.stockreturn;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-09-03T12:20:58.567+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_StockReturn_OutService",
                      portName = "SI_CSD_StockReturn_OutPort",
                      targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/StockReturn",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FStockReturn%5ESI_CSD_StockReturn_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                      endpointInterface = "com.firstflight.mm.csdtosap.stockreturn.SICSDStockReturnOut")
                      
public class SICSDStockReturnOutImpl implements SICSDStockReturnOut {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDStockReturnOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.mm.csdtosap.stockreturn.SICSDStockReturnOut#siCSDStockReturnOut(com.firstflight.mm.csdtosap.stockreturn.DTCSDStockReturn  mtCSDStockReturn )*
     */
    public void siCSDStockReturnOut(DTCSDStockReturn mtCSDStockReturn) { 
    	LOGGER.info("Executing operation siCSDStockReturnOut");
    	LOGGER.debug("mtCSDStockReturn::"+mtCSDStockReturn);
        try {
        } catch (java.lang.Exception ex) {
        	LOGGER.error("SICSDStockReturnOutImpl::siCSDStockReturnOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
