
package com.firstflight.mm.csdtosap.stockreturn;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-09-03T12:20:58.457+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDStockReturnOut_SICSDStockReturnOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDStockReturnOut_SICSDStockReturnOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/MM/CSDToSAP/StockReturn", "SI_CSD_StockReturn_OutService");

    private SICSDStockReturnOut_SICSDStockReturnOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDStockReturnOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDStockReturnOut_SICSDStockReturnOutPort_Client::main::error::",e);
            }
        }
      
        SICSDStockReturnOutService ss = new SICSDStockReturnOutService(wsdlURL, SERVICE_NAME);
        SICSDStockReturnOut port = ss.getSICSDStockReturnOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDStockReturnOut...");
        com.firstflight.mm.csdtosap.stockreturn.DTCSDStockReturn _siCSDStockReturnOut_mtCSDStockReturn = new com.firstflight.mm.csdtosap.stockreturn.DTCSDStockReturn();
        java.util.List<com.firstflight.mm.csdtosap.stockreturn.DTCSDStockReturn.StockReturn> _siCSDStockReturnOut_mtCSDStockReturnStockReturn = new java.util.ArrayList<com.firstflight.mm.csdtosap.stockreturn.DTCSDStockReturn.StockReturn>();
        com.firstflight.mm.csdtosap.stockreturn.DTCSDStockReturn.StockReturn _siCSDStockReturnOut_mtCSDStockReturnStockReturnVal1 = new com.firstflight.mm.csdtosap.stockreturn.DTCSDStockReturn.StockReturn();
        _siCSDStockReturnOut_mtCSDStockReturnStockReturnVal1.setDocumentDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-06-07T14:37:55.976+05:30"));
        _siCSDStockReturnOut_mtCSDStockReturnStockReturnVal1.setQuantity(new java.math.BigDecimal("1626135501111409194.251392595842411445"));
        _siCSDStockReturnOut_mtCSDStockReturnStockReturnVal1.setMaterialCode("MaterialCode1895204780");
        _siCSDStockReturnOut_mtCSDStockReturnStockReturnVal1.setLoggedInPlant("LoggedInPlant-1530214405");
        _siCSDStockReturnOut_mtCSDStockReturnStockReturnVal1.setStkTransNo("StkTransNo2096443202");
        _siCSDStockReturnOut_mtCSDStockReturnStockReturnVal1.setIssueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-06-07T14:37:55.992+05:30"));
        _siCSDStockReturnOut_mtCSDStockReturnStockReturnVal1.setCustNo("CustNo1634598733");
        _siCSDStockReturnOut_mtCSDStockReturnStockReturnVal1.setTimestamp("Timestamp-470887877");
        _siCSDStockReturnOut_mtCSDStockReturnStockReturn.add(_siCSDStockReturnOut_mtCSDStockReturnStockReturnVal1);
        _siCSDStockReturnOut_mtCSDStockReturn.getStockReturn().addAll(_siCSDStockReturnOut_mtCSDStockReturnStockReturn);
        port.siCSDStockReturnOut(_siCSDStockReturnOut_mtCSDStockReturn);


        }

        System.exit(0);
    }

}
