package com.firstflight.mm.csdtosap.stockreturn;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-09-03T12:20:58.598+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/StockReturn", name = "SI_CSD_StockReturn_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDStockReturnOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_StockReturn_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDStockReturnOut(
        @WebParam(partName = "MT_CSD_StockReturn", name = "MT_CSD_StockReturn", targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/StockReturn")
        DTCSDStockReturn mtCSDStockReturn
    );
}
