package com.firstflight.mm.csdtosap.stockconsumption;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1 2014-02-21T13:43:16.035+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/StockConsumption", name = "SI_CSD_StockConsumption_Out")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDStockConsumptionOut {

	@Oneway
	@WebMethod(operationName = "SI_CSD_StockConsumption_Out", action = "http://sap.com/xi/WebService/soap1.1")
	public void siCSDStockConsumptionOut(
			@WebParam(partName = "MT_CSD_StockConsumption", name = "MT_CSD_StockConsumption", targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/StockConsumption") DTCSDStockConsumption mtCSDStockConsumption);
}
