package com.firstflight.mm.csdtosap.stockconsumption;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1 2014-02-21T13:43:15.738+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDStockConsumptionOut_SICSDStockConsumptionOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDStockConsumptionOut_SICSDStockConsumptionOutPort_Client.class);

	private static final QName SERVICE_NAME = new QName(
			"http://FirstFlight.com/MM/CSDToSAP/StockConsumption",
			"SI_CSD_StockConsumption_OutService");

	private SICSDStockConsumptionOut_SICSDStockConsumptionOutPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = SICSDStockConsumptionOutService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				LOGGER.error("SICSDStockConsumptionOut_SICSDStockConsumptionOutPort_Client::main::error::",e);
			}
		}

		SICSDStockConsumptionOutService ss = new SICSDStockConsumptionOutService(
				wsdlURL, SERVICE_NAME);
		SICSDStockConsumptionOut port = ss.getSICSDStockConsumptionOutPort();

		{
			LOGGER.debug("Invoking siCSDStockConsumptionOut...");
			com.firstflight.mm.csdtosap.stockconsumption.DTCSDStockConsumption _siCSDStockConsumptionOut_mtCSDStockConsumption = new com.firstflight.mm.csdtosap.stockconsumption.DTCSDStockConsumption();
			java.util.List<com.firstflight.mm.csdtosap.stockconsumption.DTCSDStockConsumption.StockConsumption> _siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumption = new java.util.ArrayList<com.firstflight.mm.csdtosap.stockconsumption.DTCSDStockConsumption.StockConsumption>();
			com.firstflight.mm.csdtosap.stockconsumption.DTCSDStockConsumption.StockConsumption _siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumptionVal1 = new com.firstflight.mm.csdtosap.stockconsumption.DTCSDStockConsumption.StockConsumption();
			_siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumptionVal1
					.setBookingDate(javax.xml.datatype.DatatypeFactory
							.newInstance().newXMLGregorianCalendar(
									"2014-02-21T13:43:15.988+05:30"));
			_siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumptionVal1
					.setMaterial("Material-1222542349");
			_siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumptionVal1
					.setQuantity("Quantity465853312");
			_siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumptionVal1
					.setBookingDocNo("BookingDocNo-914907073");
			_siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumptionVal1
					.setLoggedInPlant("LoggedInPlant1089924095");
			_siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumptionVal1
					.setCustomerCode("CustomerCode275730935");
			_siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumptionVal1
					.setTransactionNo("TransactionNo89967738");
			_siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumption
					.add(_siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumptionVal1);
			_siCSDStockConsumptionOut_mtCSDStockConsumption
					.getStockConsumption()
					.addAll(_siCSDStockConsumptionOut_mtCSDStockConsumptionStockConsumption);
			port.siCSDStockConsumptionOut(_siCSDStockConsumptionOut_mtCSDStockConsumption);

		}

		System.exit(0);
	}

}
