/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.mm.csdtosap.stockconsumption;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1 2014-02-21T13:43:16.019+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(serviceName = "SI_CSD_StockConsumption_OutService", portName = "SI_CSD_StockConsumption_OutPort", targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/StockConsumption", wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FStockConsumption%5ESI_CSD_StockConsumption_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface", endpointInterface = "com.firstflight.mm.csdtosap.stockconsumption.SICSDStockConsumptionOut")
public class SICSDStockConsumptionOutImpl implements SICSDStockConsumptionOut {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDStockConsumptionOutImpl.class);

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.firstflight.mm.csdtosap.stockconsumption.SICSDStockConsumptionOut
	 * #siCSDStockConsumptionOut
	 * (com.firstflight.mm.csdtosap.stockconsumption.DTCSDStockConsumption
	 * mtCSDStockConsumption )*
	 */
	public void siCSDStockConsumptionOut(
			DTCSDStockConsumption mtCSDStockConsumption) {
		LOGGER.info("Executing operation siCSDStockConsumptionOut");
		LOGGER.debug("mtCSDStockConsumption::"+mtCSDStockConsumption);
		try {
		} catch (java.lang.Exception ex) {
			LOGGER.error("SICSDStockConsumptionOutImpl::siCSDStockConsumptionOut::error::",ex);
			throw new RuntimeException(ex);
		}
	}

}
