 <!--hidden fields start from here --> 
<%@ taglib uri="http://struts.apache.org/tags-html" prefix="html" %>
<html:hidden property="to.loggedInUserId" styleId="loggedInUserId"/>
<html:hidden property="to.createdByUserId" styleId="createdByUserId"/>
<html:hidden property="to.loginOfficeId" styleId="loggedInOfficeId"/>
<html:hidden property="to.loginOfficeCode" styleId="loggedInOfficeCode" />

<html:hidden property="to.drsScreenCode" styleId="drsScreenCode" />

<html:hidden property="to.consigmntTypePpx" styleId="consigmntTypePpx" />
<html:hidden property="to.consigmntTypeDox" styleId="consigmntTypeDox" />

<html:hidden property="to.deliveryId" styleId="deliveryId" />

<html:hidden property="to.loginCityId" styleId="loginCityId" />
<html:hidden property="to.drsOfficeName" styleId="drsOfficeName" />
<html:hidden property="to.drsType" styleId="drsType" />

<html:hidden property="to.isDrsDicarded" styleId="isDrsDicarded" />
<html:hidden property="to.canUpdate" styleId="canUpdate" />
<html:hidden property="to.drsStatus" styleId="drsStatus" />
<html:hidden property="to.allowedSeries" styleId="allowedSeries" />
<html:hidden property="to.isNormalCnoteAllowed" styleId="isNormalCnoteAllowed" />
<html:hidden property="to.flagYes" styleId="flagYes" />
<html:hidden property="to.flagNo" styleId="flagNo" />
<html:hidden property="to.consgNumLength" styleId="consgNumLength" />
<html:hidden property="to.comailLength" styleId="comailLength" />
<html:hidden property="to.comailStartsWith" styleId="comailStartsWith" />
<html:hidden property="to.reasonsForMisCard" styleId="reasonsForMisCard" />
<html:hidden property="to.dlvTypeOffice" styleId="dlvTypeOffice" />
<html:hidden property="to.dlvTypeNonDlv" styleId="dlvTypeNonDlv" />
<html:hidden property="to.drsStatusUpdate" styleId="drsStatusUpdate" />
<html:hidden property="to.drsStatusClosed" styleId="drsStatusClosed" />
<html:hidden property="to.seriesQ" styleId="seriesQ" />
<html:hidden property="to.seriesC" styleId="seriesC" />
<html:hidden property="to.seriesT" styleId="seriesT" />
<html:hidden property="to.seriesL" styleId="seriesL" />
<html:hidden property="to.seriesD" styleId="seriesD" />
<html:hidden property="to.isPricingInfoRequired" styleId="isPricingInfoRequired" />


<html:hidden property="to.currentDateStr" styleId="currentDateStr" />
<html:hidden property="to.currentTimeStr" styleId="currentTimeStr" />
<html:hidden property="to.createdDateStr" styleId="createdDateStr" />
<html:hidden property="to.createdTimeStr" styleId="createdTimeStr" />
<html:hidden property="to.updatedDateStr" styleId="updatedDateStr" />
<html:hidden property="to.updatedTimeStr" styleId="updatedTimeStr" />

<html:hidden property="to.maxAllowedRows" styleId="maxAllowedRows" />
<html:hidden property="to.companySealAndSign" styleId="companySealAndSign" />


<html:hidden property="to.deliveredStatus" styleId="deliveredStatus" />
<html:hidden property="to.pendingStatus" styleId="pendingStatus" />
<html:hidden property="to.canCreateRows" styleId="canCreateRows" />
<html:hidden property="to.manifestDrsTypeMnfst" styleId="manifestDrsTypeMnfst" />
<html:hidden property="to.manifestDrsTypeDrs" styleId="manifestDrsTypeDrs" />

<html:hidden property="to.pendingDrsScreenCode" styleId="pendingDrsScreenCode" />
<html:hidden property="to.autoGeneratedManualDrsNumber" styleId="autoGeneratedManualDrsNumber" />
<html:hidden property="to.loggedInOfficeType" styleId="loggedInOfficeType" />








 <!--hidden fields Ends here --> 