package com.firstflight.mm.csdtosap.serviceentrycreation;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-12-27T16:21:18.311+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/ServiceEntryCreation", name = "SI_CSD_ServiceEntryCreation_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDServiceEntryCreationOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_ServiceEntryCreation_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDServiceEntryCreationOut(
        @WebParam(partName = "MT_CSD_ServiceEntryCreation", name = "MT_CSD_ServiceEntryCreation", targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/ServiceEntryCreation")
        DTCSDServiceEntryCreation mtCSDServiceEntryCreation
    );
}
