
package com.firstflight.mm.csdtosap.serviceentrycreation;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-12-27T16:21:18.231+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDServiceEntryCreationOut_SICSDServiceEntryCreationOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDServiceEntryCreationOut_SICSDServiceEntryCreationOutPort_Client.class);
	

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/MM/CSDToSAP/ServiceEntryCreation", "SI_CSD_ServiceEntryCreation_OutService");

    private SICSDServiceEntryCreationOut_SICSDServiceEntryCreationOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDServiceEntryCreationOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDServiceEntryCreationOut_SICSDServiceEntryCreationOutPort_Client::main::error::",e);
            }
        }
      
        SICSDServiceEntryCreationOutService ss = new SICSDServiceEntryCreationOutService(wsdlURL, SERVICE_NAME);
        SICSDServiceEntryCreationOut port = ss.getSICSDServiceEntryCreationOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDServiceEntryCreationOut...");
        com.firstflight.mm.csdtosap.serviceentrycreation.DTCSDServiceEntryCreation _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreation = new com.firstflight.mm.csdtosap.serviceentrycreation.DTCSDServiceEntryCreation();
        java.util.List<com.firstflight.mm.csdtosap.serviceentrycreation.DTCSDServiceEntryCreation.ServiceEntryCreation> _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreation = new java.util.ArrayList<com.firstflight.mm.csdtosap.serviceentrycreation.DTCSDServiceEntryCreation.ServiceEntryCreation>();
        com.firstflight.mm.csdtosap.serviceentrycreation.DTCSDServiceEntryCreation.ServiceEntryCreation _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1 = new com.firstflight.mm.csdtosap.serviceentrycreation.DTCSDServiceEntryCreation.ServiceEntryCreation();
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setSLNO("SLNO820376206");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setNameOfColoader("NameOfColoader636045034");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setSubServiceType("SubServiceType-2067357166");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setWayBill("WayBill-1785643098");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setCDNo("CDNo-1074710901");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setFlightNo("FlightNo-572616826");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setDestination("Destination-1517608767");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setGrossPrice("GrossPrice-255030339");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setPriceOthers("PriceOthers-301097255");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setTotalPrice("TotalPrice-2022208176");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setServiceType("ServiceType-147171164");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setUOM("UOM1787447473");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setQuantity("Quantity1425440385");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setPlant("Plant763272388");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setTranscationNo("TranscationNo1571506523");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setNameOfVendor("NameOfVendor-2086352576");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setVehicleNo("VehicleNo-452562546");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setTripSheetDate("TripSheetDate-1124826481");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setTripSheetNo("TripSheetNo1436277688");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setRent("Rent1001449884");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setRRNo("RRNo1575069119");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1.setTrainNo("TrainNo-2133649362");
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreation.add(_siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreationVal1);
        _siCSDServiceEntryCreationOut_mtCSDServiceEntryCreation.getServiceEntryCreation().addAll(_siCSDServiceEntryCreationOut_mtCSDServiceEntryCreationServiceEntryCreation);
        port.siCSDServiceEntryCreationOut(_siCSDServiceEntryCreationOut_mtCSDServiceEntryCreation);


        }

        System.exit(0);
    }

}
