CREATE TABLE `ff_d_sap_interface_error_config` (
  `INTERFACE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INTERFACE_NAME` varchar(255) NOT NULL,
  `INTERFACE_TYPE` enum('MASTER','TRANSACTIONAL') NOT NULL,
  `TABLE_NAME` varchar(200) NOT NULL,
  `STATUS_COLUMN_NAME` varchar(50) NOT NULL,
  `CREATED_DATE` date DEFAULT NULL,
  `UPDATED_DATE` date DEFAULT NULL,
  PRIMARY KEY (`INTERFACE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
