package com.ff.rate.configuration.ratequotation.constants;

public interface RateQuotationExcelConstants {
	String CUSTOMER_NO = "CUSTOMER_NO";
	String SALES_OFFICE_CODE = "SALES_OFFICE_CODE";

	String SALES_EMPLOYEE_CODE = "SALES_EMPLOYEE_CODE";
	String INDUSTRY_TYPE_CODE = "INDUSTRY_TYPE_CODE";
	String CUSTOMER_GROUP =	"CUSTOMER_GROUP";
			
	String CUSTOMER_TYPE = "CUSTOMER_TYPE";
	String CUST_NAME = "CUST_NAME";
	String ADDRESS_1 =	"ADDRESS_1";
	String ADDRESS_2 = "ADDRESS_2";
	String ADDRESS_3 = "ADDRESS_3";
	String CITY_CODE =	"CITY_CODE";
	String PINCODE = "PINCODE";

	String CUST_CONTACT_NO = "CONTACT_NO";
	String CUST_EXTENTION = "EXTENTION";
	String CUST_MOBILE = "MOBILE";
	String CUST_FAX = "FAX";
	String CUST_EMAIL = "EMAIL";
	String PRI_TITLE = "TITLE";
	String PRI_DEPT_CODE = "DEPT_CODE";
	String PRI_PERSON_NAME = "PERSON_NAME";
	String PRI_DESIGNATION = "DESIGNATION";
	String PRI_EMAIL = "EMAIL";
	String PRI_CONTACT_NO = "CONTACT_NO";
	String PRI_EXTENTION = "EXTENTION";
	String PRI_MOBILE = "MOBILE";
	String PRI_FAX = "FAX";
	
	
	String SEC_TITLE = "TITLE";
	String SEC_DEPT_CODE = "DEPT_CODE";
	String SEC_PERSON_NAME = "PERSON_NAME";
	String SEC_DESIGNATION = "DESIGNATION";
	String SEC_EMAIL = "EMAIL";
	String SEC_CONTACT_NO = "CONTACT_NO";
	String SEC_EXTENTION = "EXTENTION";
	String SEC_MOBILE = "MOBILE";
	String SEC_FAX = "FAX";
	
	String BILLING_CYCLE = "BILLING_CYCLE";
	String LEGACY_CODE = "LEGACY_CODE";
	String PAN_NO = "PAN_NO";
	String TAN_NO = "TAN_NO";
	String BUSINESS_TYPE = "BUSINESS_TYPE";
	String INDUSTRY_CATEGORY = "INDUSTRY_CATEGORY";
	String CUSTOMER_CATEGORY = "CUSTOMER_CATEGORY";
	String QUOTATION_TYPE = "QUOTATION_TYPE";
	String OWNER_TYPE = "OWNER_TYPE";
	String SALES_USER_NAME = "SALES_USER_NAME";
	String  SALES_USER_OFFICE_CODE = "SALES_USER_OFFICE_CODE";

	








	





	
}
