package com.firstflight.mm.csdtosap.stocktransfers;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-04-16T15:50:21.068+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/StockTransfer", name = "SI_CSD_StockTransfer_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDStockTransferOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_StockTransfer_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDStockTransferOut(
        @WebParam(partName = "MT_CSD_StockTransfer", name = "MT_CSD_StockTransfer", targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/StockTransfer")
        DTCSDStockTransfer mtCSDStockTransfer
    );
}
