
package com.firstflight.mm.csdtosap.stocktransfers;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-04-16T15:50:20.897+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDStockTransferOut_SICSDStockTransferOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDStockTransferOut_SICSDStockTransferOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/MM/CSDToSAP/StockTransfer", "SI_CSD_StockTransfer_OutService");

    private SICSDStockTransferOut_SICSDStockTransferOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDStockTransferOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDStockTransferOut_SICSDStockTransferOutPort_Client::main::error::",e);
            }
        }
      
        SICSDStockTransferOutService ss = new SICSDStockTransferOutService(wsdlURL, SERVICE_NAME);
        SICSDStockTransferOut port = ss.getSICSDStockTransferOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDStockTransferOut...");
        com.firstflight.mm.csdtosap.stocktransfers.DTCSDStockTransfer _siCSDStockTransferOut_mtCSDStockTransfer = new com.firstflight.mm.csdtosap.stocktransfers.DTCSDStockTransfer();
        java.util.List<com.firstflight.mm.csdtosap.stocktransfers.DTCSDStockTransfer.StockTransfer> _siCSDStockTransferOut_mtCSDStockTransferStockTransfer = new java.util.ArrayList<com.firstflight.mm.csdtosap.stocktransfers.DTCSDStockTransfer.StockTransfer>();
        com.firstflight.mm.csdtosap.stocktransfers.DTCSDStockTransfer.StockTransfer _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1 = new com.firstflight.mm.csdtosap.stocktransfers.DTCSDStockTransfer.StockTransfer();
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setTimestamp("Timestamp-1993951080");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setROWNUMBER(new java.math.BigInteger("76855679987671870097847829307785916617"));
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setISSUEDATE(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-16T15:50:21.037+05:30"));
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setREQUISITIONNUMBER("REQUISITIONNUMBER246168737");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setITEMTYPECODE("ITEMTYPECODE-873657389");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setITEMCODE("ITEMCODE-927009228");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setDESCRIPTION("DESCRIPTION1519330363");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setUNITOFMEASURE("UNITOFMEASURE1885493233");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setISSUEDQUANTITY(new java.math.BigInteger("4000457433091760666940272804777814656"));
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setISSUENUMBER("ISSUENUMBER1570847412");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setISSUEDTOOFFICE("ISSUEDTOOFFICE-613228610");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setISSUEOFFICEID("ISSUEOFFICEID-1467513154");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransfer.add(_siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1);
        _siCSDStockTransferOut_mtCSDStockTransfer.getStockTransfer().addAll(_siCSDStockTransferOut_mtCSDStockTransferStockTransfer);
        port.siCSDStockTransferOut(_siCSDStockTransferOut_mtCSDStockTransfer);


        }

        System.exit(0);
    }

}
