
ALTER TABLE `CorpUDAAN`.`ff_f_delivery_dtls` MODIFY COLUMN `COD_AMOUNT` DOUBLE(13,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_delivery_dtls` MODIFY COLUMN `LC_AMOUNT` DOUBLE(13,2) DEFAULT '0.00';

ALTER TABLE `CorpUDAAN`.`ff_f_delivery_dtls` MODIFY COLUMN `TO_PAY_AMOUNT` DOUBLE(13,2) DEFAULT '0.00';

ALTER TABLE `CorpUDAAN`.`ff_f_delivery_dtls` MODIFY COLUMN `OTHER_AMOUNT` DOUBLE(13,2) DEFAULT '0.00';

ALTER TABLE `CorpUDAAN`.`ff_f_delivery_dtls` MODIFY COLUMN `ADDITIONAL_CHARGES` DOUBLE(13,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_delivery_dtls` MODIFY COLUMN `BA_AMT` DOUBLE(13,2) DEFAULT '0.00';
