-- COLLECTION TABLES ALTER SCRIPT
ALTER TABLE `CorpUDAAN`.`ff_f_collection` MODIFY COLUMN `TOTAL_COLLECTION_AMOUNT` DOUBLE(13,2);
ALTER TABLE `CorpUDAAN`.`ff_f_collection_entries` MODIFY COLUMN `BILL_AMOUNT` DOUBLE(13,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_collection_entries` MODIFY COLUMN `RECEIVED_AMOUNT` DOUBLE(13,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_collection_entries` MODIFY COLUMN `TDS_AMOUNT` DOUBLE(13,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_collection_entries` MODIFY COLUMN `DEDUCTION` DOUBLE(13,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_collection_entries` MODIFY COLUMN `TOTAL_BILL_AMOUNT` DOUBLE(13,2) DEFAULT '0.00';