
-- LIABILITY TABLES ALTER SCRIPT 
ALTER TABLE `CorpUDAAN`.`ff_f_liability_payment` MODIFY COLUMN `LIABILTIY_AMOUNT` DOUBLE(13,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_liability_entries` MODIFY COLUMN `COD_LC_AMT` DOUBLE(13,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_liability_entries` MODIFY COLUMN `COLLECTED_AMT` DOUBLE(13,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_liability_entries` MODIFY COLUMN `PAID_AMT` DOUBLE(13,2) DEFAULT '0.00';
