
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.fi.csdtosap.codlcconsignmentNew;

import org.slf4j.Logger;

import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-03-18T12:47:51.797+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_CODLCConsignment_OutService",
                      portName = "SI_CSD_CODLCConsignment_OutPort",
                      targetNamespace = "http://FirstFlight.com/FI/CSDToSAP/CODLCConsignment",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FFI%2FCSDToSAP%2FCODLCConsignment%5ESI_CSD_CODLCConsignment_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                      endpointInterface = "com.firstflight.fi.csdtosap.codlcconsignment.SICSDCODLCConsignmentOut")
                      
public class SICSDCODLCConsignmentOutImpl implements SICSDCODLCConsignmentOut {

	/** The logger. */
	private final static Logger LOG = LoggerFactory
			.getLogger(SICSDCODLCConsignmentOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.fi.csdtosap.codlcconsignment.SICSDCODLCConsignmentOut#siCODCODLCConsignmentOut(com.firstflight.fi.csdtosap.codlcconsignment.DTCSDCODLCConsignment  mtCSDCODLCConsignment )*
     */
    public void siCODCODLCConsignmentOut(DTCSDCODLCConsignment mtCSDCODLCConsignment) { 
        LOG.info("Executing operation siCODCODLCConsignmentOut");
        LOG.debug("mtCSDCODLCConsignment=="+mtCSDCODLCConsignment);
        try {
        } catch (java.lang.Exception ex) {
        	 LOG.error("SICSDCODLCConsignmentOutImpl::siCODCODLCConsignmentOut()::error",ex);
            throw new RuntimeException(ex);
        }
    }

}
