package com.firstflight.fi.csdtosap.codlcconsignmentNew;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-03-18T12:47:51.825+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "SI_CSD_CODLCConsignment_OutService", 
                  wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FFI%2FCSDToSAP%2FCODLCConsignment%5ESI_CSD_CODLCConsignment_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                  targetNamespace = "http://FirstFlight.com/FI/CSDToSAP/CODLCConsignment") 
public class SICSDCODLCConsignmentOutService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://FirstFlight.com/FI/CSDToSAP/CODLCConsignment", "SI_CSD_CODLCConsignment_OutService");
    public final static QName SICSDCODLCConsignmentOutPort = new QName("http://FirstFlight.com/FI/CSDToSAP/CODLCConsignment", "SI_CSD_CODLCConsignment_OutPort");
    static {
        URL url = null;
        try {
            url = new URL("http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FFI%2FCSDToSAP%2FCODLCConsignment%5ESI_CSD_CODLCConsignment_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SICSDCODLCConsignmentOutService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FFI%2FCSDToSAP%2FCODLCConsignment%5ESI_CSD_CODLCConsignment_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface");
        }
        WSDL_LOCATION = url;
    }

    public SICSDCODLCConsignmentOutService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SICSDCODLCConsignmentOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICSDCODLCConsignmentOutService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDCODLCConsignmentOutService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDCODLCConsignmentOutService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDCODLCConsignmentOutService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SICSDCODLCConsignmentOut
     */
    @WebEndpoint(name = "SI_CSD_CODLCConsignment_OutPort")
    public SICSDCODLCConsignmentOut getSICSDCODLCConsignmentOutPort() {
        return super.getPort(SICSDCODLCConsignmentOutPort, SICSDCODLCConsignmentOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICSDCODLCConsignmentOut
     */
    @WebEndpoint(name = "SI_CSD_CODLCConsignment_OutPort")
    public SICSDCODLCConsignmentOut getSICSDCODLCConsignmentOutPort(WebServiceFeature... features) {
        return super.getPort(SICSDCODLCConsignmentOutPort, SICSDCODLCConsignmentOut.class, features);
    }

}
