
package com.firstflight.mm.csdtosap.serviceentrysheetcocourier;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-01-15T19:21:23.913+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDServiceEntrySheetCoCourierOut_SICSDServiceEntrySheetCoCourierOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDServiceEntrySheetCoCourierOut_SICSDServiceEntrySheetCoCourierOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/MM/CSDToSAP/ServiceEntrySheetCoCourier", "SI_CSD_ServiceEntrySheetCoCourier_OutService");

    private SICSDServiceEntrySheetCoCourierOut_SICSDServiceEntrySheetCoCourierOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDServiceEntrySheetCoCourierOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDServiceEntrySheetCoCourierOut_SICSDServiceEntrySheetCoCourierOutPort_Client::main::error::",e);
            }
        }
      
        SICSDServiceEntrySheetCoCourierOutService ss = new SICSDServiceEntrySheetCoCourierOutService(wsdlURL, SERVICE_NAME);
        SICSDServiceEntrySheetCoCourierOut port = ss.getSICSDServiceEntrySheetCoCourierOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDServiceEntrySheetCoCourierOut...");
        com.firstflight.mm.csdtosap.serviceentrysheetcocourier.DTCSDServiceEntrySheetCoCourier _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourier = new com.firstflight.mm.csdtosap.serviceentrysheetcocourier.DTCSDServiceEntrySheetCoCourier();
        java.util.List<com.firstflight.mm.csdtosap.serviceentrysheetcocourier.DTCSDServiceEntrySheetCoCourier.ServiceEntrySheetCoCourier> _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourier = new java.util.ArrayList<com.firstflight.mm.csdtosap.serviceentrysheetcocourier.DTCSDServiceEntrySheetCoCourier.ServiceEntrySheetCoCourier>();
        com.firstflight.mm.csdtosap.serviceentrysheetcocourier.DTCSDServiceEntrySheetCoCourier.ServiceEntrySheetCoCourier _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1 = new com.firstflight.mm.csdtosap.serviceentrysheetcocourier.DTCSDServiceEntrySheetCoCourier.ServiceEntrySheetCoCourier();
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1.setVendor("Vendor-1596579805");
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1.setDate("Date-1574452925");
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1.setPickUpOrDeliveryFlag("PickUpOrDeliveryFlag-1116628246");
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1.setCountOfConsignments("CountOfConsignments930018867");
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1.setProductCode("ProductCode-1263204834");
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1.setPlant("Plant-1288834802");
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1.setServiceType("ServiceType-1311332294");
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1.setWeight("Weight498432466");
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1.setTransactionNo("TransactionNo-708453001");
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1.setDoxNonDoxType("DoxNonDoxType342981944");
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourier.add(_siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourierVal1);
        _siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourier.getServiceEntrySheetCoCourier().addAll(_siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourierServiceEntrySheetCoCourier);
        port.siCSDServiceEntrySheetCoCourierOut(_siCSDServiceEntrySheetCoCourierOut_mtCSDServiceEntrySheetCoCourier);


        }

        System.exit(0);
    }

}
