package com.firstflight.mm.csdtosap.serviceentrysheetcocourier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-01-15T19:21:24.053+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "SI_CSD_ServiceEntrySheetCoCourier_OutService", 
                  wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FServiceEntrySheetCoCourier%5ESI_CSD_ServiceEntrySheetCoCourier_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                  targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/ServiceEntrySheetCoCourier") 
public class SICSDServiceEntrySheetCoCourierOutService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://FirstFlight.com/MM/CSDToSAP/ServiceEntrySheetCoCourier", "SI_CSD_ServiceEntrySheetCoCourier_OutService");
    public final static QName SICSDServiceEntrySheetCoCourierOutPort = new QName("http://FirstFlight.com/MM/CSDToSAP/ServiceEntrySheetCoCourier", "SI_CSD_ServiceEntrySheetCoCourier_OutPort");
    static {
        URL url = null;
        try {
            url = new URL("http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FServiceEntrySheetCoCourier%5ESI_CSD_ServiceEntrySheetCoCourier_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SICSDServiceEntrySheetCoCourierOutService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FServiceEntrySheetCoCourier%5ESI_CSD_ServiceEntrySheetCoCourier_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface");
        }
        WSDL_LOCATION = url;
    }

    public SICSDServiceEntrySheetCoCourierOutService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SICSDServiceEntrySheetCoCourierOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICSDServiceEntrySheetCoCourierOutService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDServiceEntrySheetCoCourierOutService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDServiceEntrySheetCoCourierOutService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDServiceEntrySheetCoCourierOutService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SICSDServiceEntrySheetCoCourierOut
     */
    @WebEndpoint(name = "SI_CSD_ServiceEntrySheetCoCourier_OutPort")
    public SICSDServiceEntrySheetCoCourierOut getSICSDServiceEntrySheetCoCourierOutPort() {
        return super.getPort(SICSDServiceEntrySheetCoCourierOutPort, SICSDServiceEntrySheetCoCourierOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICSDServiceEntrySheetCoCourierOut
     */
    @WebEndpoint(name = "SI_CSD_ServiceEntrySheetCoCourier_OutPort")
    public SICSDServiceEntrySheetCoCourierOut getSICSDServiceEntrySheetCoCourierOutPort(WebServiceFeature... features) {
        return super.getPort(SICSDServiceEntrySheetCoCourierOutPort, SICSDServiceEntrySheetCoCourierOut.class, features);
    }

}
