
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.mm.csdtosap.serviceentrysheetcocourier;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-01-15T19:21:24.022+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_ServiceEntrySheetCoCourier_OutService",
                      portName = "SI_CSD_ServiceEntrySheetCoCourier_OutPort",
                      targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/ServiceEntrySheetCoCourier",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FServiceEntrySheetCoCourier%5ESI_CSD_ServiceEntrySheetCoCourier_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                      endpointInterface = "com.firstflight.mm.csdtosap.serviceentrysheetcocourier.SICSDServiceEntrySheetCoCourierOut")
                      
public class SICSDServiceEntrySheetCoCourierOutImpl implements SICSDServiceEntrySheetCoCourierOut {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDServiceEntrySheetCoCourierOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.mm.csdtosap.serviceentrysheetcocourier.SICSDServiceEntrySheetCoCourierOut#siCSDServiceEntrySheetCoCourierOut(com.firstflight.mm.csdtosap.serviceentrysheetcocourier.DTCSDServiceEntrySheetCoCourier  mtCSDServiceEntrySheetCoCourier )*
     */
    public void siCSDServiceEntrySheetCoCourierOut(DTCSDServiceEntrySheetCoCourier mtCSDServiceEntrySheetCoCourier) { 
    	LOGGER.info("Executing operation siCSDServiceEntrySheetCoCourierOut");
    	LOGGER.debug("mtCSDServiceEntrySheetCoCourier::"+mtCSDServiceEntrySheetCoCourier);
        try {
        } catch (java.lang.Exception ex) {
        	LOGGER.error("SICSDServiceEntrySheetCoCourierOutImpl::siCSDServiceEntrySheetCoCourierOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
