ALTER TABLE ff_f_bill MODIFY LC_AMOUNT double(20, 2) DEFAULT '0.00';
ALTER TABLE ff_f_bill MODIFY LC_CHARGE double(20, 2) DEFAULT '0.00';
ALTER TABLE ff_f_bill MODIFY COD_AMOUNT double(20, 2) DEFAULT '0.00';
ALTER TABLE ff_f_bill MODIFY COD_CHARGE double(20, 2) DEFAULT '0.00';
ALTER TABLE ff_f_bill MODIFY RTO_CHARGE double(20, 2) DEFAULT '0.00'
