/**
 * 
 */
package com.ff.admin.constants;

/**
 * @author mohammes
 * 
 */
public interface AdminErrorConstants {

	String ORDER_DTLS_NOT_EXIST = "E0001";
	String DETAILS_NOT_EXIST = "E0002";
	String DETAILS_AL_READY_APPROVED = "E0003";
	String NUMBER_DOES_NOT_EXIST = "E0004";
	String DETAILS_NOT_SAVED = "E0005";
	String DETAILS_NOT_SAVED_DB_ISSUE = "E0006";
	String NUMBER_DOES_NOT_EXIST_FOR_BRANCH = "E0007";
	String DETAILS_NOT_FOUND_DB_ISSUE = "E0008";
	String DETAILS_NOT_APPROVED = "E0009";
	String STOCK_CLOSED = "E0010";
	String PROBLEM_NUMBER_GENERATION = "E0011";
	String RECEIVED_FROM_VENDOR = "E0012";
	String NOT_YET_ACKNOWLEDGED = "E0013";
	String NO_CUSTOMERS_FOR_LC_COD = "E0014";
	String ALREADY_ISSUED = "E0015";

	String DETAILS_SAVED_SUCCESS = "I0001";
	String DUPLICATE_FORM_SUBMISSION = "I0002";
	String UN_AUTHORIZED_USER = "I0003";

	String DETAILS_DOES_NOT_EXIST = "I0004";
	String SEARCH_DETAILS_DOES_NOT_EXIST = "I0005";

	String STOCK_NUMBER_EMPTY = "S001";
	String STOCK_REQ_DTLS_NOT_EXIST = "S002";

	String CAN_NOT_FOUND_WITH_REASON = "S003";

	String STOCK_ISSUE_PAYMENT_DTLS = "S004";
	String STOCK_NOT_EXIST = "S005";
	
	String MATERIAL_NOT_ALLOWED = "S006";
	String NOT_ISSUED_HERE = "S007";

	String REPORTING_RHO_NOT_EXIST_FOR_LOGGED_IN_OFFICE = "S008";
	String STOCK_RETURNED_COMPLETED = "S009";
	String STOCK_EXCEL_UPLOAD_INVALID="S010";
	String STOCK_EXCEL_UPLOAD_MATERIAL_INVALID="S011";
	String STOCK_EXCEL_SAVED = "S012";
	String STOCK_EXCEL_INVALID_SERIES_LENGTH = "S013";
	String STOCK_EXCEL_INVALID_SERIES = "S014";
	String STOCK_EXCEL_INVALID_SERIES_LEAF = "S015";
	String STOCK_EXCEL_INVALID_END_SERIES = "S016";
	String STOCK_EXCEL_SAVED_WITH_NUMBER = "S017";
	
	
	
	
	

	String ROUTE_INFO_NOT_SAVED = "RTP002";

	String ROUTE_INFO_SAVED = "RTP001";

	String ROUTE_INFO_NOT_UPDATED = "RTP004";

	String ROUTE_INFO_UPDATED = "RTP003";

	String ROUTE_SERVICE_PARSE_ERROR = "RSE001";

	String ROUTE_DTLS_ERROR = "RSS001";

	String ROUTE_STATION_ERROR = "RSS002";

	// String ROUTE_TRANSPORT_ERROR = "RSS003";

	String ROUTE_DB_ISSUE = "RSS003";

	String ROUTE_SERVICE_DTLS_PARSE_ERROR = "RSE002";

	String ROUTE_NOT_EXIST = "RSS004";

	String ROUTE_VENDORS_NOT_EXIST = "RSS005";

	String ROUTE_DETAILS_NOT_FOUND_DB_ISSUE = "RSS006";
	
	String TRIP_DETAILS_NOT_FOUND = "RSS007";

	String TRIP_SERVICE_DETAILS_NOT_FOUND = "RSS008";
	// for Billing
	String INVOICE_RUNSHEET_HEADERDEATILS_NOT_AVAILABLE = "INV001";
	String NO_STATIONARY_AVAILABLE = "BILL001";
	String NO_STATION_FOUND = "BILL002";
	String NO_BRANCHES_FOUND = "BILL003";
	String NO_CUSTOMER_FOUND = "BILL004";
	String NO_BILLS_FOUND = "BILL005";
	String NO_PICKUPBOY = "BILL006";
	String DATABASE_ISSUE = "BILL0007";
	String BillINVOICE_DATA_NOT_SAVED = "BILL0008";
	String NO_CUSTOMERBYPICKUPBOY_FOUND = "BILL0009";
	String NO_SHIPTOCODE_FOUND = "BILL0010";
	String NO_INVOICERUNSHEET_FOUND = "BILL0011";
	String NO_RUNSHEETSTATUS_FOUND = "BILL0012";
	String NO_REGION_FOUND = "BILL0013";
	String NOT_AUTHIRIZED_USER = "BILL0014";
	String NO_CONSG_DETAILS_FORMODIFICATION="CUSTM001";
	String NO_BOOK_DETAILS_FORMODIFICATION="CUSTM002";
//	String NO_RATE_DETAILS_FORMODIFICATION="CUSTM003";
	String INVALID_CONSIGNMENT_FORMAT = "CON003";
	String CN_BILLED_FORMODIFICATION="CUSTM004";
	String NO_CUSTOMER_FORMODIFICATION="CUSTM005";
	String NO_CUSTOMER_AVALABLE_FORMODIFICATION="CUSTM006";
	String EXPENSE_CREATED_FORCN="CUSTM007";
	String COLLECTION_CREATED_FORCN="CUSTM008";
	String LIABILITY_CREATED_FORCN="CUSTM009";
	String CREDIT_CUSTOMER_ALLOW="CUSTM010";
	String OLDCUSTTYPE_NEWCUSTTYPE_ERROR="CUSTM011";
	String CUST_NOT_MODIFIED="CUSTM012";
	String CUST_MODIFICATION_DATA_SAVED="CUSTM013";
	String ERROR_IN_GETTING_BRANCH_LIST_OF_HUB="BILL0016";
	String NO_SHIPPEDTO_CODE="CUSTM016";
    String SAP_LIABILITY_ENTRY_CONSUMED="CUSTM018";
    String NO_CONSG_DETAILS_ON_PRODUCT_SERIES="CUSTM019";
    String MAX_LIMIT_DECLAREVALUE ="CUSTM021";
    String CUST_CONSIGN_EXCEED_LIMIT ="CUSTM025";
    String CN_MODIFICATION_NOT_ALLOWS_OLDER_CONSIGNMENTS = "CNMOD09";
    
    // For Tracking
	String NO_STOCK_TYPE = "TRERR001";
	String BOOKING_DETAILS_NOT_FOUND = "TRERR002";
	String CONSIGNMENT_NOT_FOUND = "TRERR003";
	String PROCESS_DETAILS_NOT_FOUND = "TRERR004";
	String LOAD_MOVEMENT_DETAILS_NOT_FOUND = "TRERR005";
	String MANIFEST_DETAILS_NOT_FOUND = "TRERR006";
	String TRACKING_DETAILS_NOT_FOUND = "TRERR007";
	String PATH_NOT_FOUND = "TRERR008";
	String CONSIGNMENT_EXCEED_LIMIT = "TRERR009";
	String MULTIPLE_RESULTS_FOUND = "TRERR010";
	String PROVIDE_NUMBERS_TO_TRACK = "TRERR011";
	String COMPLETE_CONSIGNMENT_DETAILS_NOT_AVAILABLE ="Complete Consignment details still not available for Tracking!!";

	// MEC
	String MEC_CUSTOMER_NOT_EXIST = "MEC100";
	String NO_COLLECTION_AGAINST_DTLS = "MEC101";
	String NO_BILL_COLLECTION_AGAINST_DTLS = "MEC102";
	String NO_CONSG_DTLS_FOUND_FOR_TODAYS_DATE = "MEC103";
	String NO_DTLS_FOUND = "MEC104";
	String DETAILS_CAN_NOT_SAVED = "MEC105";
	String CN_ALREADY_DELIVERED = "MEC106";
	String NO_SUCH_CN_FOUND = "MEC107";
	// MASTER
	String NO_STATE_FOUND = "MASTER100";
	String NO_CITY_FOUND ="MASTER101";
	String NO_VENDORDETAILS_FOUND="MASTERV001";
	
	//Complaints
	String COMPLAINTS_PINCODE_DTLS_NOT_EXIST="CM004";
	String COMPLAINTS_INVALID_SEARCH_TYPE="CM009";
	String COMPLAINTS_INVALID_SEARCH_TYPE_NUMBER="CM010";
	String COMPLAINTS_QUERY_TYPE_EMPTY="CM011";
	String COMPLAINTS_UPDATE_SERVICE_REQUEST="CM012";
	String COMPLAINTS_DETAILS_NOT_FOUNDT="CM014";
	String COMPLAINTS_FILE_UPLOAD_SIZE_EXCEEDED="CM015";
	String COMPLAINTS_FILE_UPLOAD_SIZE_EMPTY="CM016";
	String COMPLAINTS_CAN_NOT_BE_EMPTY="CM018";
	
	
	
	//Stop Delivery
	String NO_CN_DETAILS_FOUND="SDELV001";
	String NO_BOOKING_DETIALS="SDELV002";
	
	String JOB_DB_ISSUE="JOB001";
	String JOB_PROCESS_DATA ="JOB003";
	String NO_REBILL_DATA="REB0011";
	String NO_REBILLGDR_DATA="REBG001";
	String NO_CONTRACT_AVAILABLE_IN_BOOKING_PERIOD = "REBC001";
}
