
package com.firstflight.fi.csdtosap.expenseentry;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-05-09T16:06:11.876+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDExpenseEntriesOut_SICSDExpenseEntriesOutPort_Client {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDExpenseEntriesOut_SICSDExpenseEntriesOutPort_Client.class);

	
    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/FI/CSDToSAP/ExpenseEntries", "SI_CSD_ExpenseEntries_OutService");

    private SICSDExpenseEntriesOut_SICSDExpenseEntriesOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDExpenseEntriesOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDExpenseEntriesOut_SICSDExpenseEntriesOutPort_Client::main::error::",e);
            }
        }
      
        SICSDExpenseEntriesOutService ss = new SICSDExpenseEntriesOutService(wsdlURL, SERVICE_NAME);
        SICSDExpenseEntriesOut port = ss.getSICSDExpenseEntriesOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDExpenseEntriesOut...");
        com.firstflight.fi.csdtosap.expenseentry.DTCSDExpenseEntries _siCSDExpenseEntriesOut_mtCSDExpenseEntries = new com.firstflight.fi.csdtosap.expenseentry.DTCSDExpenseEntries();
        java.util.List<com.firstflight.fi.csdtosap.expenseentry.DTCSDExpenseEntries.ExpenseEntries> _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntries = new java.util.ArrayList<com.firstflight.fi.csdtosap.expenseentry.DTCSDExpenseEntries.ExpenseEntries>();
        com.firstflight.fi.csdtosap.expenseentry.DTCSDExpenseEntries.ExpenseEntries _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1 = new com.firstflight.fi.csdtosap.expenseentry.DTCSDExpenseEntries.ExpenseEntries();
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setBranchCode("BranchCode284801137");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setTransactionID("TransactionID1380615715");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setExpenseGLCode("ExpenseGLCode-1712840965");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setModeOfPayment("ModeOfPayment-808366114");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setAmount("Amount-1484213766");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setChequeDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-05-03T14:59:11.612+05:30"));
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setChequeNo("ChequeNo2063651661");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setChequeBank("ChequeBank-693706435");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setCreationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-05-03T14:59:11.659+05:30"));
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntries.add(_siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1);
        _siCSDExpenseEntriesOut_mtCSDExpenseEntries.getExpenseEntries().addAll(_siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntries);
        port.siCSDExpenseEntriesOut(_siCSDExpenseEntriesOut_mtCSDExpenseEntries);


        }

        System.exit(0);
    }

}
