package com.ff.domain.business;

import com.capgemini.lbs.framework.domain.CGFactDO;
import com.ff.domain.organization.EmployeeDO;
import com.ff.domain.organization.OfficeDO;
import com.ff.domain.pickup.AddressDO;
import com.ff.domain.ratemanagement.masters.ContactDO;
import com.ff.domain.ratemanagement.masters.CustomerGroupDO;
import com.ff.domain.ratemanagement.masters.RateCustomerCategoryDO;
import com.ff.domain.ratemanagement.masters.RateIndustryCategoryDO;
import com.ff.domain.ratemanagement.masters.RateIndustryTypeDO;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : FirstFlight
//  @ File Name : CustomerDO.java
//  @ Date : 10/4/2012
//  @ Author : 
//
//

public class BaseCustomerDO extends CGFactDO {

	/**
     * 
     */
    private static final long serialVersionUID = 375899922121291808L;
    private Integer customerId;
    private String customerCode;
    private String businessName;
    private String firstName;
    private String lastName;
    private String phone;
    private String mobile;
    private String fax;
    private String status;
    private String email;
    private String description;
   // private Integer mappedOffice;
    private String city;
    
    /*Added fo customer new changes*/
    private OfficeDO salesOfficeDO;
	private EmployeeDO salesPersonDO;
	private RateIndustryCategoryDO industryCategoryDO;
	private RateIndustryTypeDO industryTypeDO;
	private String distributionChannels;
	private RateCustomerCategoryDO customerCategoryDO;
	private AddressDO addressDO;
	private ContactDO primaryContactDO;
	private ContactDO secondaryContactDO;
	private OfficeDO officeMappedDO;
	private String tanNo;
	private String panNo;
	private CustomerGroupDO groupKeyDO;
	private String businessType;
	private CustomerTypeDO customerType;
	private String billingCycle;
	private String paymentTerm;
	private String contractNo;
	private String legacyCustomerCode;
    
    /*Ends here*/

    /**
     * 
     */
   

    public Integer getCustomerId() {
        return customerId;
    }


    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }


    public String getCustomerCode() {
        return customerCode;
    }


    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }


    public String getBusinessName() {
        return businessName;
    }


    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }


    public String getFirstName() {
        return firstName;
    }


    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    public String getLastName() {
        return lastName;
    }


    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    public String getPhone() {
        return phone;
    }


    public void setPhone(String phone) {
        this.phone = phone;
    }


    public String getMobile() {
        return mobile;
    }


    public void setMobile(String mobile) {
        this.mobile = mobile;
    }


    public String getFax() {
        return fax;
    }


    public void setFax(String fax) {
        this.fax = fax;
    }


    public String getStatus() {
        return status;
    }


    public void setStatus(String status) {
        this.status = status;
    }


    public String getEmail() {
        return email;
    }


    public void setEmail(String email) {
        this.email = email;
    }


    public String getDescription() {
        return description;
    }


    public void setDescription(String description) {
        this.description = description;
    }

    public String getCity() {
        return city;
    }


    public void setCity(String city) {
        this.city = city;
    }

 

	public String getDistributionChannels() {
		return distributionChannels;
	}


	public void setDistributionChannels(String distributionChannels) {
		this.distributionChannels = distributionChannels;
	}

	public String getTanNo() {
		return tanNo;
	}


	public void setTanNo(String tanNo) {
		this.tanNo = tanNo;
	}


	public String getPanNo() {
		return panNo;
	}


	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}


	

	

	public String getBusinessType() {
		return businessType;
	}


	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}



	public String getBillingCycle() {
		return billingCycle;
	}


	public void setBillingCycle(String billingCycle) {
		this.billingCycle = billingCycle;
	}


	public String getPaymentTerm() {
		return paymentTerm;
	}


	public void setPaymentTerm(String paymentTerm) {
		this.paymentTerm = paymentTerm;
	}


	public String getContractNo() {
		return contractNo;
	}


	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}


	@Override
    public String toString() {
	return "CustomerDO [customerId=" + customerId + ", customerCode="
		+ customerCode + ", businessName=" + businessName
		+ ", firstName=" + firstName + ", lastName=" + lastName
		+ ", customerType=" + customerType + ", phone=" + phone
		+ ", mobile=" + mobile + ", status=" + status + ", email="
		+ email + ", city=" + city + "]";
    }


	/**
	 * @return the officeMappedDO
	 */
	public OfficeDO getOfficeMappedDO() {
		return officeMappedDO;
	}


	/**
	 * @param officeMappedDO the officeMappedDO to set
	 */
	public void setOfficeMappedDO(OfficeDO officeMappedDO) {
		this.officeMappedDO = officeMappedDO;
	}


	/**
	 * @return the salesOfficeDO
	 */
	public OfficeDO getSalesOfficeDO() {
		return salesOfficeDO;
	}


	/**
	 * @param salesOfficeDO the salesOfficeDO to set
	 */
	public void setSalesOfficeDO(OfficeDO salesOfficeDO) {
		this.salesOfficeDO = salesOfficeDO;
	}


	/**
	 * @return the salesPersonDO
	 */
	public EmployeeDO getSalesPersonDO() {
		return salesPersonDO;
	}


	/**
	 * @param salesPersonDO the salesPersonDO to set
	 */
	public void setSalesPersonDO(EmployeeDO salesPersonDO) {
		this.salesPersonDO = salesPersonDO;
	}


	/**
	 * @return the industryCategoryDO
	 */
	public RateIndustryCategoryDO getIndustryCategoryDO() {
		return industryCategoryDO;
	}


	/**
	 * @param industryCategoryDO the industryCategoryDO to set
	 */
	public void setIndustryCategoryDO(RateIndustryCategoryDO industryCategoryDO) {
		this.industryCategoryDO = industryCategoryDO;
	}


	/**
	 * @return the industryTypeDO
	 */
	public RateIndustryTypeDO getIndustryTypeDO() {
		return industryTypeDO;
	}


	/**
	 * @param industryTypeDO the industryTypeDO to set
	 */
	public void setIndustryTypeDO(RateIndustryTypeDO industryTypeDO) {
		this.industryTypeDO = industryTypeDO;
	}


	/**
	 * @return the customerCategoryDO
	 */
	public RateCustomerCategoryDO getCustomerCategoryDO() {
		return customerCategoryDO;
	}


	/**
	 * @param customerCategoryDO the customerCategoryDO to set
	 */
	public void setCustomerCategoryDO(RateCustomerCategoryDO customerCategoryDO) {
		this.customerCategoryDO = customerCategoryDO;
	}


	/**
	 * @return the addressDO
	 */
	public AddressDO getAddressDO() {
		return addressDO;
	}


	/**
	 * @param addressDO the addressDO to set
	 */
	public void setAddressDO(AddressDO addressDO) {
		this.addressDO = addressDO;
	}


	/**
	 * @return the primaryContactDO
	 */
	public ContactDO getPrimaryContactDO() {
		return primaryContactDO;
	}


	/**
	 * @param primaryContactDO the primaryContactDO to set
	 */
	public void setPrimaryContactDO(ContactDO primaryContactDO) {
		this.primaryContactDO = primaryContactDO;
	}


	/**
	 * @return the secondaryContactDO
	 */
	public ContactDO getSecondaryContactDO() {
		return secondaryContactDO;
	}


	/**
	 * @param secondaryContactDO the secondaryContactDO to set
	 */
	public void setSecondaryContactDO(ContactDO secondaryContactDO) {
		this.secondaryContactDO = secondaryContactDO;
	}


	/**
	 * @return the groupKeyDO
	 */
	public CustomerGroupDO getGroupKeyDO() {
		return groupKeyDO;
	}


	/**
	 * @param groupKeyDO the groupKeyDO to set
	 */
	public void setGroupKeyDO(CustomerGroupDO groupKeyDO) {
		this.groupKeyDO = groupKeyDO;
	}


	/**
	 * @return the customerType
	 */
	public CustomerTypeDO getCustomerType() {
		return customerType;
	}


	/**
	 * @param customerType the customerType to set
	 */
	public void setCustomerType(CustomerTypeDO customerType) {
		this.customerType = customerType;
	}


	/**
	 * @return the legacyCustomerCode
	 */
	public String getLegacyCustomerCode() {
		return legacyCustomerCode;
	}


	/**
	 * @param legacyCustomerCode the legacyCustomerCode to set
	 */
	public void setLegacyCustomerCode(String legacyCustomerCode) {
		this.legacyCustomerCode = legacyCustomerCode;
	}

   
}
