package com.ff.domain.business;

import java.util.Date;

import com.capgemini.lbs.framework.domain.CGFactDO;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : FirstFlight
//  @ File Name : CustomerDO.java
//  @ Date : 10/4/2012
//  @ Author : 
//
//

public class CustomerWrapperDO extends CGFactDO {

    /**
     * 
     */
    private static final long serialVersionUID = 375899922121291808L;
    
    
	private Date createdDate;
	private String contractNo;
	private String regionName;
	private String station;
	private String customerName;
	private String salesOfficeName;
	private String salesPerson;
	private String groupKey;
	private String status;
	
	
	
	public CustomerWrapperDO(Date createdDate, String contractNo,
			String regionName, String station, String customerName,
			String salesOfficeName, String salesPerson, String groupKey,
			String status) {
		super();
		this.createdDate = createdDate;
		this.contractNo = contractNo;
		this.regionName = regionName;
		this.station = station;
		this.customerName = customerName;
		this.salesOfficeName = salesOfficeName;
		this.salesPerson = salesPerson;
		this.groupKey = groupKey;
		this.status = status;
	}
	/**
	 * @return the createdDate
	 */
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * @param createdDate the createdDate to set
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	/**
	 * @return the contractNo
	 */
	public String getContractNo() {
		return contractNo;
	}
	/**
	 * @param contractNo the contractNo to set
	 */
	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}
	/**
	 * @return the regionName
	 */
	public String getRegionName() {
		return regionName;
	}
	/**
	 * @param regionName the regionName to set
	 */
	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}
	/**
	 * @return the station
	 */
	public String getStation() {
		return station;
	}
	/**
	 * @param station the station to set
	 */
	public void setStation(String station) {
		this.station = station;
	}
	/**
	 * @return the customerName
	 */
	public String getCustomerName() {
		return customerName;
	}
	/**
	 * @param customerName the customerName to set
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	/**
	 * @return the salesOfficeName
	 */
	public String getSalesOfficeName() {
		return salesOfficeName;
	}
	/**
	 * @param salesOfficeName the salesOfficeName to set
	 */
	public void setSalesOfficeName(String salesOfficeName) {
		this.salesOfficeName = salesOfficeName;
	}
	/**
	 * @return the salesPerson
	 */
	public String getSalesPerson() {
		return salesPerson;
	}
	/**
	 * @param salesPerson the salesPerson to set
	 */
	public void setSalesPerson(String salesPerson) {
		this.salesPerson = salesPerson;
	}
	/**
	 * @return the groupKey
	 */
	public String getGroupKey() {
		return groupKey;
	}
	/**
	 * @param groupKey the groupKey to set
	 */
	public void setGroupKey(String groupKey) {
		this.groupKey = groupKey;
	}
	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}
	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}
    
   }
