package com.ff.domain.business;



//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : FirstFlight
//  @ File Name : CustomerDO.java
//  @ Date : 10/4/2012
//  @ Author : 
//
//

public class CustomerDO extends BaseCustomerDO{

	private static final long serialVersionUID = 375899922121291808L;
    public CustomerDO() {
	super();
    }


    	
}
