/*Sami - Artifact artf3519535 : Partially approved PR issue*/
USE CorpUDAAN;
INSERT INTO ff_d_std_type (ID,STD_TYPE_CODE,  DESCRIPTION,  PARENT_TYPE,  TYPE_NAME,  CUR_STATUS,  DT_TO_BRANCH )
 VALUES (287,'PAPPROVED','PARTIAL APPROVED','STOCK_MODULE','STOCK_REQ_STATUS','A','N');