/*Niharika - artf3519255*/
Use CorpUDAAN;
ALTER TABLE ff_f_service_request_complaint_legal
  MODIFY INVESTIGATION_FEEDBACK VARCHAR(500) DEFAULT NULL,
  MODIFY REMARK VARCHAR(500) DEFAULT NULL,
  MODIFY HEARING1 VARCHAR(500) DEFAULT NULL,
  MODIFY HEARING2 VARCHAR(500) DEFAULT NULL,
  MODIFY HEARING3 VARCHAR(500) DEFAULT NULL,
  MODIFY HEARING4 VARCHAR(500) DEFAULT NULL,
  MODIFY HEARING5 VARCHAR(500) DEFAULT NULL,
  MODIFY HEARING6 VARCHAR(500) DEFAULT NULL;
/*Himal - artf3519255*/  
ALTER TABLE   ff_f_service_request_followup MODIFY FOLLOWUP_NOTE VARCHAR(500) DEFAULT NULL;

ALTER TABLE ff_f_service_request MODIFY	 REMARK	VARCHAR(500) DEFAULT NULL;

ALTER TABLE ff_f_service_request_complaint 
MODIFY	REASON VARCHAR(500) DEFAULT NULL COMMENT 'Complaint Reason',
MODIFY	REMARK VARCHAR(500) DEFAULT NULL,
MODIFY	LIR_REMARKS VARCHAR(500) DEFAULT NULL,
MODIFY	LOST_LETTER_REMARKS VARCHAR(500) DEFAULT NULL;

ALTER TABLE ff_f_service_request_complaint_claim	
MODIFY	REMARKS			VARCHAR(500) DEFAULT NULL,
MODIFY	SALES_MANAGER_FEEDBACK	VARCHAR(500) DEFAULT NULL,
MODIFY	AGM_FEEDBACK		VARCHAR(500) DEFAULT NULL,
MODIFY	CS_MANAGER_FEEDBACK	VARCHAR(500) DEFAULT NULL,
MODIFY	VP_FEEDBACK		VARCHAR(500) DEFAULT NULL;  
