/*Set LAST_GENERATED_SEQUENCE to zero in new branch */

update cg_d_sequence_gen set LAST_GENERATED_SEQUENCE = 0;

/*Script to truncate transaction tables and Set Auto increment to 1*/

set foreign_key_checks=0;
truncate table  ff_d_ba_stock_mapping;
truncate table  ff_d_customer_stock_mapping;
truncate table  ff_d_employee_stock_mapping;
truncate table  ff_d_franchisee_stock_mapping;
truncate table  ff_d_office_stock_mapping;
truncate table  ff_d_outbound_data_packet;
truncate table  ff_d_outbound_office_packet;
truncate table  ff_f_bill;
truncate table  ff_f_billing_consignment;
truncate table  ff_f_billing_consignment_rate;
truncate table  ff_f_billing_consignment_rate_extension;
truncate table  ff_f_billing_consignment_summary;
truncate table  ff_f_billing_stock_issue;
truncate table  ff_f_booking;
truncate table  ff_f_booking_duplicate;
truncate table  ff_f_booking_payment;
truncate table  ff_f_booking_preference_mapping;
truncate table  ff_f_brr_hit_ratio_report_data;
truncate table  ff_f_bulk_booking_vendor_dtls;
truncate table  ff_f_bulk_cn_track;
truncate table  ff_f_child_consignments;
truncate table  ff_f_child_consignments_duplicate;
truncate table  ff_f_collection;
truncate table  ff_f_collection_entries;
truncate table  ff_f_coloader_rates;
truncate table  ff_f_comail;
truncate table  ff_f_comail_manifested;
truncate table  ff_f_consignment;
truncate table  ff_f_consignment_duplicate;
truncate table  ff_f_consignment_manifested;
truncate table  ff_f_consignment_rate;
truncate table  ff_f_consignment_rate_extension;
truncate table  ff_f_consignment_return;
truncate table  ff_f_consignment_return_reason;
truncate table  ff_f_consignments_to_be_tracked;
truncate table  ff_f_customer_Modification;
truncate table  ff_f_customer_vendor;
truncate table  ff_f_delivery;
truncate table  ff_f_delivery_commission_calculation;
truncate table  ff_f_delivery_dtls;
truncate table  ff_f_delivery_navigator;
truncate table  ff_f_expense;
truncate table  ff_f_expense_entries;
truncate table  ff_f_heldup;
truncate table  ff_f_input_for_pickup_commission;
truncate table  ff_f_invoice_run_sheet_detail;
truncate table  ff_f_invoice_run_sheet_header;
truncate table  ff_f_lead;
truncate table  ff_f_lead_competitor;
truncate table  ff_f_liability_entries;
truncate table  ff_f_liability_payment;
truncate table  ff_f_load_connected;
truncate table  ff_f_load_movement;
truncate table  ff_f_manifest;
truncate table  ff_f_manifest_process;
truncate table  ff_f_outmanifest_destination;
truncate table  ff_f_petty_cash;
truncate table  ff_f_pickup_assignment_detail;
truncate table  ff_f_pickup_assignment_header;
truncate table  ff_f_pickup_commission_calculation;
truncate table  ff_f_pickup_runsheet_detail;
truncate table  ff_f_pickup_runsheet_header;
truncate table  ff_f_plan_feedback;
truncate table  ff_f_privilege_card_trans;
truncate table  ff_f_re_billing_consignment;
truncate table  ff_f_re_billing_consignment_rate;
truncate table  ff_f_re_billing_header;
truncate table  ff_f_rev_pickup_order_request_detail;
truncate table  ff_f_rev_pickup_order_request_header;
truncate table  ff_f_rev_pickup_order_to_branch;
truncate table  ff_f_sales_target;
truncate table  ff_f_sap_bill_sales_order;
truncate table  ff_f_sap_billing_consignment_summary;
truncate table  ff_f_sap_co_courier;
truncate table  ff_f_sap_collection;
truncate table  ff_f_sap_coloader_invoice;
truncate table  ff_f_sap_coloader_rates;
truncate table  ff_f_sap_contract;
truncate table  ff_f_sap_customer;
truncate table  ff_f_sap_delivery_commission_calc;
truncate table  ff_f_sap_employee;
truncate table  ff_f_sap_employee_pickup;
truncate table  ff_f_sap_expense;
truncate table  ff_f_sap_item;
truncate table  ff_f_sap_liability_entries;
truncate table  ff_f_sap_liability_payment;
truncate table  ff_f_sap_office;
truncate table  ff_f_sap_outstanding_payment;
truncate table  ff_f_sap_pickup_commission_calculation;
truncate table  ff_f_sap_report;
truncate table  ff_f_sap_staging_bill_sales_order;
truncate table  ff_f_sap_stock_cancellation;
truncate table  ff_f_sap_stock_consolidation;
truncate table  ff_f_sap_stock_issue;
truncate table  ff_f_sap_stock_receipt;
truncate table  ff_f_sap_stock_requisition;
truncate table  ff_f_sap_stock_return;
truncate table  ff_f_sap_stock_transfer;
truncate table  ff_f_sap_vendor;
truncate table  ff_f_service_related_detail;
truncate table  ff_f_service_request;
truncate table  ff_f_service_request_complaint;
truncate table  ff_f_service_request_complaint_claim;
truncate table  ff_f_service_request_complaint_legal;
truncate table  ff_f_service_request_followup;
truncate table  ff_f_service_request_papers;
truncate table  ff_f_sms;
truncate table  ff_f_stock_cancellation;
truncate table  ff_f_stock_consumption_level;
truncate table  ff_f_stock_issue;
truncate table  ff_f_stock_issue_item_dtls;
truncate table  ff_f_stock_payment_detls;
truncate table  ff_f_stock_receipt;
truncate table  ff_f_stock_receipt_item_dtls;
truncate table  ff_f_stock_requisition;
truncate table  ff_f_stock_requisition_item_dtls;
truncate table  ff_f_stock_return;
truncate table  ff_f_stock_return_item_dtls;
truncate table  ff_f_stock_transfer;

/*Set Auto Increment to 1*/
alter table  ff_d_ba_stock_mapping AUTO_INCREMENT=1;
alter table  ff_d_customer_stock_mapping AUTO_INCREMENT=1;
alter table  ff_d_employee_stock_mapping AUTO_INCREMENT=1;
alter table  ff_d_franchisee_stock_mapping AUTO_INCREMENT=1;
alter table  ff_d_office_stock_mapping AUTO_INCREMENT=1;
alter table  ff_d_outbound_data_packet AUTO_INCREMENT=1;
alter table  ff_d_outbound_office_packet AUTO_INCREMENT=1;
alter table  ff_f_bill AUTO_INCREMENT=1;
alter table  ff_f_billing_consignment AUTO_INCREMENT=1;
alter table  ff_f_billing_consignment_rate AUTO_INCREMENT=1;
alter table  ff_f_billing_consignment_rate_extension AUTO_INCREMENT=1;
alter table  ff_f_billing_consignment_summary AUTO_INCREMENT=1;
alter table  ff_f_billing_stock_issue AUTO_INCREMENT=1;
alter table  ff_f_booking AUTO_INCREMENT=1;
alter table  ff_f_booking_duplicate AUTO_INCREMENT=1;
alter table  ff_f_booking_payment AUTO_INCREMENT=1;
alter table  ff_f_booking_preference_mapping AUTO_INCREMENT=1;
alter table  ff_f_brr_hit_ratio_report_data AUTO_INCREMENT=1;
alter table  ff_f_bulk_booking_vendor_dtls AUTO_INCREMENT=1;
alter table  ff_f_bulk_cn_track AUTO_INCREMENT=1;
alter table  ff_f_child_consignments AUTO_INCREMENT=1;
alter table  ff_f_child_consignments_duplicate AUTO_INCREMENT=1;
alter table  ff_f_collection AUTO_INCREMENT=1;
alter table  ff_f_collection_entries AUTO_INCREMENT=1;
alter table  ff_f_coloader_rates AUTO_INCREMENT=1;
alter table  ff_f_comail AUTO_INCREMENT=1;
alter table  ff_f_comail_manifested AUTO_INCREMENT=1;
alter table  ff_f_consignment AUTO_INCREMENT=1;
alter table  ff_f_consignment_duplicate AUTO_INCREMENT=1;
alter table  ff_f_consignment_manifested AUTO_INCREMENT=1;
alter table  ff_f_consignment_rate AUTO_INCREMENT=1;
alter table  ff_f_consignment_rate_extension AUTO_INCREMENT=1;
alter table  ff_f_consignment_return AUTO_INCREMENT=1;
alter table  ff_f_consignment_return_reason AUTO_INCREMENT=1;
alter table  ff_f_consignments_to_be_tracked AUTO_INCREMENT=1;
alter table  ff_f_customer_Modification AUTO_INCREMENT=1;
alter table  ff_f_customer_vendor AUTO_INCREMENT=1;
alter table  ff_f_delivery AUTO_INCREMENT=1;
alter table  ff_f_delivery_commission_calculation AUTO_INCREMENT=1;
alter table  ff_f_delivery_dtls AUTO_INCREMENT=1;
alter table  ff_f_delivery_navigator AUTO_INCREMENT=1;
alter table  ff_f_expense AUTO_INCREMENT=1;
alter table  ff_f_expense_entries AUTO_INCREMENT=1;
alter table  ff_f_heldup AUTO_INCREMENT=1;
alter table  ff_f_input_for_pickup_commission AUTO_INCREMENT=1;
alter table  ff_f_invoice_run_sheet_detail AUTO_INCREMENT=1;
alter table  ff_f_invoice_run_sheet_header AUTO_INCREMENT=1;
alter table  ff_f_lead AUTO_INCREMENT=1;
alter table  ff_f_lead_competitor AUTO_INCREMENT=1;
alter table  ff_f_liability_entries AUTO_INCREMENT=1;
alter table  ff_f_liability_payment AUTO_INCREMENT=1;
alter table  ff_f_load_connected AUTO_INCREMENT=1;
alter table  ff_f_load_movement AUTO_INCREMENT=1;
alter table  ff_f_manifest AUTO_INCREMENT=1;
alter table  ff_f_manifest_process AUTO_INCREMENT=1;
alter table  ff_f_outmanifest_destination AUTO_INCREMENT=1;
alter table  ff_f_petty_cash AUTO_INCREMENT=1;
alter table  ff_f_pickup_assignment_detail AUTO_INCREMENT=1;
alter table  ff_f_pickup_assignment_header AUTO_INCREMENT=1;
alter table  ff_f_pickup_commission_calculation AUTO_INCREMENT=1;
alter table  ff_f_pickup_runsheet_detail AUTO_INCREMENT=1;
alter table  ff_f_pickup_runsheet_header AUTO_INCREMENT=1;
alter table  ff_f_plan_feedback AUTO_INCREMENT=1;
alter table  ff_f_privilege_card_trans AUTO_INCREMENT=1;
alter table  ff_f_re_billing_consignment AUTO_INCREMENT=1;
alter table  ff_f_re_billing_consignment_rate AUTO_INCREMENT=1;
alter table  ff_f_re_billing_header AUTO_INCREMENT=1;
alter table  ff_f_rev_pickup_order_request_detail AUTO_INCREMENT=1;
alter table  ff_f_rev_pickup_order_request_header AUTO_INCREMENT=1;
alter table  ff_f_rev_pickup_order_to_branch AUTO_INCREMENT=1;
alter table  ff_f_sales_target AUTO_INCREMENT=1;
alter table  ff_f_sap_bill_sales_order AUTO_INCREMENT=1;
alter table  ff_f_sap_billing_consignment_summary AUTO_INCREMENT=1;
alter table  ff_f_sap_co_courier AUTO_INCREMENT=1;
alter table  ff_f_sap_collection AUTO_INCREMENT=1;
alter table  ff_f_sap_coloader_invoice AUTO_INCREMENT=1;
alter table  ff_f_sap_coloader_rates AUTO_INCREMENT=1;
alter table  ff_f_sap_contract AUTO_INCREMENT=1;
alter table  ff_f_sap_customer AUTO_INCREMENT=1;
alter table  ff_f_sap_delivery_commission_calc AUTO_INCREMENT=1;
alter table  ff_f_sap_employee AUTO_INCREMENT=1;
alter table  ff_f_sap_employee_pickup AUTO_INCREMENT=1;
alter table  ff_f_sap_expense AUTO_INCREMENT=1;
alter table  ff_f_sap_item AUTO_INCREMENT=1;
alter table  ff_f_sap_liability_entries AUTO_INCREMENT=1;
alter table  ff_f_sap_liability_payment AUTO_INCREMENT=1;
alter table  ff_f_sap_office AUTO_INCREMENT=1;
alter table  ff_f_sap_outstanding_payment AUTO_INCREMENT=1;
alter table  ff_f_sap_pickup_commission_calculation AUTO_INCREMENT=1;
alter table  ff_f_sap_report AUTO_INCREMENT=1;
alter table  ff_f_sap_staging_bill_sales_order AUTO_INCREMENT=1;
alter table  ff_f_sap_stock_cancellation AUTO_INCREMENT=1;
alter table  ff_f_sap_stock_consolidation AUTO_INCREMENT=1;
alter table  ff_f_sap_stock_issue AUTO_INCREMENT=1;
alter table  ff_f_sap_stock_receipt AUTO_INCREMENT=1;
alter table  ff_f_sap_stock_requisition AUTO_INCREMENT=1;
alter table  ff_f_sap_stock_return AUTO_INCREMENT=1;
alter table  ff_f_sap_stock_transfer AUTO_INCREMENT=1;
alter table  ff_f_sap_vendor AUTO_INCREMENT=1;
alter table  ff_f_service_related_detail AUTO_INCREMENT=1;
alter table  ff_f_service_request AUTO_INCREMENT=1;
alter table  ff_f_service_request_complaint AUTO_INCREMENT=1;
alter table  ff_f_service_request_complaint_claim AUTO_INCREMENT=1;
alter table  ff_f_service_request_complaint_legal AUTO_INCREMENT=1;
alter table  ff_f_service_request_followup AUTO_INCREMENT=1;
alter table  ff_f_service_request_papers AUTO_INCREMENT=1;
alter table  ff_f_sms AUTO_INCREMENT=1;
alter table  ff_f_stock_cancellation AUTO_INCREMENT=1;
alter table  ff_f_stock_consumption_level AUTO_INCREMENT=1;
alter table  ff_f_stock_issue AUTO_INCREMENT=1;
alter table  ff_f_stock_issue_item_dtls AUTO_INCREMENT=1;
alter table  ff_f_stock_payment_detls AUTO_INCREMENT=1;
alter table  ff_f_stock_receipt AUTO_INCREMENT=1;
alter table  ff_f_stock_receipt_item_dtls AUTO_INCREMENT=1;
alter table  ff_f_stock_requisition AUTO_INCREMENT=1;
alter table  ff_f_stock_requisition_item_dtls AUTO_INCREMENT=1;
alter table  ff_f_stock_return AUTO_INCREMENT=1;
alter table  ff_f_stock_return_item_dtls AUTO_INCREMENT=1;
alter table  ff_f_stock_transfer AUTO_INCREMENT=1;

set foreign_key_checks=1;