
package com.firstflight.sd.csdtosap.salesorder;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-11-18T11:33:34.903+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDSalesOrderOut_SICSDSalesOrderOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDSalesOrderOut_SICSDSalesOrderOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/SD/CSDToSAP/SalesOrder", "SI_CSD_SalesOrder_OutService");

    private SICSDSalesOrderOut_SICSDSalesOrderOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDSalesOrderOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDSalesOrderOut_SICSDSalesOrderOutPort_Client::main::error::",e);
            }
        }
      
        SICSDSalesOrderOutService ss = new SICSDSalesOrderOutService(wsdlURL, SERVICE_NAME);
        SICSDSalesOrderOut port = ss.getSICSDSalesOrderOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDSalesOrderOut...");
        com.firstflight.sd.csdtosap.salesorder.DTCSDSalesOrder _siCSDSalesOrderOut_mtCSDSalesOrder = new com.firstflight.sd.csdtosap.salesorder.DTCSDSalesOrder();
        java.util.List<com.firstflight.sd.csdtosap.salesorder.DTCSDSalesOrder.SalesOrder> _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrder = new java.util.ArrayList<com.firstflight.sd.csdtosap.salesorder.DTCSDSalesOrder.SalesOrder>();
        com.firstflight.sd.csdtosap.salesorder.DTCSDSalesOrder.SalesOrder _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1 = new com.firstflight.sd.csdtosap.salesorder.DTCSDSalesOrder.SalesOrder();
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setBookingDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-11-18T11:33:34.965+05:30"));
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setCustShipTo("CustShipTo-1185565650");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setDistributionChannel("DistributionChannel425025954");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setCustSoldTo("CustSoldTo2079757711");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setBookingOffice("BookingOffice264913369");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setDestinationBranch("DestinationBranch1015198220");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setTrnNo("TrnNo1999156965");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setMaterial("Material-196142456");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setRTO("RTO932622211");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setQuantity("Quantity-1379674080");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setFright("Fright-2056657433");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setFuelSurcharge("FuelSurcharge-760316713");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setRiskSurcharge("RiskSurcharge-875907237");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setParcelHandlingCharges("ParcelHandlingCharges410134786");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setAirportHandlingCharges("AirportHandlingCharges1093054905");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setDocumentHandlingCharges("DocumentHandlingCharges545007496");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setValueofMaterial("ValueofMaterial-1487961035");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setCODCharges("CODCharges1738434098");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setToPayCharges("ToPayCharges1083147029");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setLCCharges("LCCharges-668334945");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setOthers("Others-1550525891");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setServiceTax("ServiceTax2090158993");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setEducationCess("EducationCess2107568325");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setHighEduCess("HighEduCess658728884");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setStateTax("StateTax-1206128653");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setSurchargeonStateTax("SurchargeonStateTax-475558382");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setGrandTotal("GrandTotal-469308859");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1.setTimestamp("Timestamp2011663813");
        _siCSDSalesOrderOut_mtCSDSalesOrderSalesOrder.add(_siCSDSalesOrderOut_mtCSDSalesOrderSalesOrderVal1);
        _siCSDSalesOrderOut_mtCSDSalesOrder.getSalesOrder().addAll(_siCSDSalesOrderOut_mtCSDSalesOrderSalesOrder);
        port.siCSDSalesOrderOut(_siCSDSalesOrderOut_mtCSDSalesOrder);


        }

        System.exit(0);
    }

}
