
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.sd.csdtosap.salesorder;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-11-18T11:33:34.981+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_SalesOrder_OutService",
                      portName = "SI_CSD_SalesOrder_OutPort",
                      targetNamespace = "http://FirstFlight.com/SD/CSDToSAP/SalesOrder",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FSD%2FCSDToSAP%2FSalesOrder%5ESI_CSD_SalesOrder_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                      endpointInterface = "com.firstflight.sd.csdtosap.salesorder.SICSDSalesOrderOut")
                      
public class SICSDSalesOrderOutImpl implements SICSDSalesOrderOut {

	/** The logger. */
	private final static Logger LOG = LoggerFactory
			.getLogger(SICSDSalesOrderOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.sd.csdtosap.salesorder.SICSDSalesOrderOut#siCSDSalesOrderOut(com.firstflight.sd.csdtosap.salesorder.DTCSDSalesOrder  mtCSDSalesOrder )*
     */
    public void siCSDSalesOrderOut(DTCSDSalesOrder mtCSDSalesOrder) { 
        LOG.info("Executing operation siCSDSalesOrderOut");
        LOG.debug("mtCSDSalesOrder::"+mtCSDSalesOrder);
        try {
        } catch (java.lang.Exception ex) {
        	LOG.error("SICSDSalesOrderOutImpl::siCSDSalesOrderOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
