package com.firstflight.sd.csdtosap.salesorder;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-11-18T11:33:34.981+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/SD/CSDToSAP/SalesOrder", name = "SI_CSD_SalesOrder_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDSalesOrderOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_SalesOrder_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDSalesOrderOut(
        @WebParam(partName = "MT_CSD_SalesOrder", name = "MT_CSD_SalesOrder", targetNamespace = "http://FirstFlight.com/SD/CSDToSAP/SalesOrder")
        DTCSDSalesOrder mtCSDSalesOrder
    );
}
