package com.firstflight.fi.csdtosap.outstandingreport;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-09-19T12:35:34.849+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/FI/CSDToSAP/CustomerOutstandingReport", name = "SI_CSD_CustomerOutstandingReport_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDCustomerOutstandingReportOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_CustomerOutstandingReport_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDCustomerOutstandingReportOut(
        @WebParam(partName = "MT_CSD_CustomerOutstandingReport", name = "MT_CSD_CustomerOutstandingReport", targetNamespace = "http://FirstFlight.com/FI/CSDToSAP/CustomerOutstandingReport")
        DTCSDCustomerOutstandingReport mtCSDCustomerOutstandingReport
    );
}
