
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.fi.csdtosap.outstandingreport;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-09-19T12:35:34.833+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_CustomerOutstandingReport_OutService",
                      portName = "SI_CSD_CustomerOutstandingReport_OutPort",
                      targetNamespace = "http://FirstFlight.com/FI/CSDToSAP/CustomerOutstandingReport",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FFI%2FCSDToSAP%2FCustomerOutstandingReport%5ESI_CSD_CustomerOutstandingReport_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                      endpointInterface = "com.firstflight.fi.csdtosap.customeroutstandingreport.SICSDCustomerOutstandingReportOut")
                      
public class SICSDCustomerOutstandingReportOutImpl implements SICSDCustomerOutstandingReportOut {

	/** The logger. */
	private final static Logger LOG = LoggerFactory
			.getLogger(SICSDCustomerOutstandingReportOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.fi.csdtosap.customeroutstandingreport.SICSDCustomerOutstandingReportOut#siCSDCustomerOutstandingReportOut(com.firstflight.fi.csdtosap.customeroutstandingreport.DTCSDCustomerOutstandingReport  mtCSDCustomerOutstandingReport )*
     */
    public void siCSDCustomerOutstandingReportOut(DTCSDCustomerOutstandingReport mtCSDCustomerOutstandingReport) { 
        LOG.info("Executing operation siCSDCustomerOutstandingReportOut");
        LOG.debug("mtCSDCustomerOutstandingReport::"+mtCSDCustomerOutstandingReport);
        try {
        } catch (java.lang.Exception ex) {
        	LOG.error("SICSDCustomerOutstandingReportOutImpl::siCSDCustomerOutstandingReportOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
