
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.mm.csdtosap.stockreturnfromba;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-09-03T12:29:18.035+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_StockReturnFromBA_OutService",
                      portName = "SI_CSD_StockReturnFromBA_OutPort",
                      targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/StockReturnFromBA",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FStockReturnFromBA%5ESI_CSD_StockReturnFromBA_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                      endpointInterface = "com.firstflight.mm.csdtosap.stockreturnfromba.SICSDStockReturnFromBAOut")
                      
public class SICSDStockReturnFromBAOutImpl implements SICSDStockReturnFromBAOut {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDStockReturnFromBAOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.mm.csdtosap.stockreturnfromba.SICSDStockReturnFromBAOut#siCSDStockReturnFromBAOut(com.firstflight.mm.csdtosap.stockreturnfromba.DTCSDStockReturnFromBA  mtCSDStockReturnFromBA )*
     */
    public void siCSDStockReturnFromBAOut(DTCSDStockReturnFromBA mtCSDStockReturnFromBA) { 
    	LOGGER.info("Executing operation siCSDStockReturnFromBAOut");
    	LOGGER.debug("mtCSDStockReturnFromBA::"+mtCSDStockReturnFromBA);
        try {
        } catch (java.lang.Exception ex) {
        	LOGGER.error("SICSDStockReturnFromBAOutImpl::siCSDStockReturnFromBAOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
