
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.hr.csdtosap.EmpPickUpCommission;

import org.slf4j.Logger;

import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-03-27T15:50:31.238+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_EmpPickUpCommission_OutService",
                      portName = "SI_CSD_EmpPickUpCommission_OutPort",
                      targetNamespace = "http://FirstFlight.com/HR/CSDToSAP/EmpPickUpCommission",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FHR%2FCSDToSAP%2FEmpPickUpCommission%5ESI_CSD_EmpPickUpCommission_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                      endpointInterface = "com.firstflight.hr.csdtosap.emppickupcommission.SICSDEmpPickUpCommissionOut")
                      
public class SICSDEmpPickUpCommissionOutImpl implements SICSDEmpPickUpCommissionOut {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDEmpPickUpCommissionOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.hr.csdtosap.emppickupcommission.SICSDEmpPickUpCommissionOut#siCSDEmpPickUpCommissionOut(com.firstflight.hr.csdtosap.emppickupcommission.DTCSDEmpPickUpCommission  mtCSDEmpPickUpCommission )*
     */
    public void siCSDEmpPickUpCommissionOut(DTCSDEmpPickUpCommission mtCSDEmpPickUpCommission) { 
    	LOGGER.info("Executing operation siCSDEmpPickUpCommissionOut");
    	LOGGER.debug("mtCSDEmpPickUpCommission"+mtCSDEmpPickUpCommission);
        try {
        } catch (java.lang.Exception ex) {
        	LOGGER.error("SICSDEmpPickUpCommissionOutImpl::siCSDEmpPickUpCommissionOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
