
package com.firstflight.hr.csdtosap.EmpPickUpCommission;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-03-27T15:50:31.097+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDEmpPickUpCommissionOut_SICSDEmpPickUpCommissionOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDEmpPickUpCommissionOut_SICSDEmpPickUpCommissionOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/HR/CSDToSAP/EmpPickUpCommission", "SI_CSD_EmpPickUpCommission_OutService");

    private SICSDEmpPickUpCommissionOut_SICSDEmpPickUpCommissionOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDEmpPickUpCommissionOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDEmpPickUpCommissionOut_SICSDEmpPickUpCommissionOutPort_Client::main::error::",e);
            }
        }
      
        SICSDEmpPickUpCommissionOutService ss = new SICSDEmpPickUpCommissionOutService(wsdlURL, SERVICE_NAME);
        SICSDEmpPickUpCommissionOut port = ss.getSICSDEmpPickUpCommissionOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDEmpPickUpCommissionOut...");
        com.firstflight.hr.csdtosap.EmpPickUpCommission.DTCSDEmpPickUpCommission _siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommission = new com.firstflight.hr.csdtosap.EmpPickUpCommission.DTCSDEmpPickUpCommission();
        java.util.List<com.firstflight.hr.csdtosap.EmpPickUpCommission.DTCSDEmpPickUpCommission.PickUpCommission> _siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommissionPickUpCommission = new java.util.ArrayList<com.firstflight.hr.csdtosap.EmpPickUpCommission.DTCSDEmpPickUpCommission.PickUpCommission>();
        com.firstflight.hr.csdtosap.EmpPickUpCommission.DTCSDEmpPickUpCommission.PickUpCommission _siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommissionPickUpCommissionVal1 = new com.firstflight.hr.csdtosap.EmpPickUpCommission.DTCSDEmpPickUpCommission.PickUpCommission();
        _siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommissionPickUpCommissionVal1.setEmployeeCode("EmployeeCode-1551227555");
        _siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommissionPickUpCommissionVal1.setPrdGrp("PrdGrp109410800");
        _siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommissionPickUpCommissionVal1.setPickUpCount("PickUpCount-172667810");
        _siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommissionPickUpCommissionVal1.setNetValue("NetValue-1665309889");
        _siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommissionPickUpCommissionVal1.setCalculatedFor(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-03-27T15:50:31.222+05:30"));
        _siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommissionPickUpCommission.add(_siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommissionPickUpCommissionVal1);
        _siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommission.getPickUpCommission().addAll(_siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommissionPickUpCommission);
        port.siCSDEmpPickUpCommissionOut(_siCSDEmpPickUpCommissionOut_mtCSDEmpPickUpCommission);


        }

        System.exit(0);
    }

}
