package com.firstflight.hr.csdtosap.EmpPickUpCommission;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-03-27T15:50:31.253+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/HR/CSDToSAP/EmpPickUpCommission", name = "SI_CSD_EmpPickUpCommission_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDEmpPickUpCommissionOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_EmpPickUpCommission_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDEmpPickUpCommissionOut(
        @WebParam(partName = "MT_CSD_EmpPickUpCommission", name = "MT_CSD_EmpPickUpCommission", targetNamespace = "http://FirstFlight.com/HR/CSDToSAP/EmpPickUpCommission")
        DTCSDEmpPickUpCommission mtCSDEmpPickUpCommission
    );
}
