package com.firstflight.hr.csdtosap.EmpPickUpCommission;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-03-27T15:50:31.253+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "SI_CSD_EmpPickUpCommission_OutService", 
                  wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FHR%2FCSDToSAP%2FEmpPickUpCommission%5ESI_CSD_EmpPickUpCommission_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                  targetNamespace = "http://FirstFlight.com/HR/CSDToSAP/EmpPickUpCommission") 
public class SICSDEmpPickUpCommissionOutService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://FirstFlight.com/HR/CSDToSAP/EmpPickUpCommission", "SI_CSD_EmpPickUpCommission_OutService");
    public final static QName SICSDEmpPickUpCommissionOutPort = new QName("http://FirstFlight.com/HR/CSDToSAP/EmpPickUpCommission", "SI_CSD_EmpPickUpCommission_OutPort");
    static {
        URL url = null;
        try {
            url = new URL("http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FHR%2FCSDToSAP%2FEmpPickUpCommission%5ESI_CSD_EmpPickUpCommission_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SICSDEmpPickUpCommissionOutService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FHR%2FCSDToSAP%2FEmpPickUpCommission%5ESI_CSD_EmpPickUpCommission_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface");
        }
        WSDL_LOCATION = url;
    }

    public SICSDEmpPickUpCommissionOutService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SICSDEmpPickUpCommissionOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICSDEmpPickUpCommissionOutService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDEmpPickUpCommissionOutService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDEmpPickUpCommissionOutService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDEmpPickUpCommissionOutService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SICSDEmpPickUpCommissionOut
     */
    @WebEndpoint(name = "SI_CSD_EmpPickUpCommission_OutPort")
    public SICSDEmpPickUpCommissionOut getSICSDEmpPickUpCommissionOutPort() {
        return super.getPort(SICSDEmpPickUpCommissionOutPort, SICSDEmpPickUpCommissionOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICSDEmpPickUpCommissionOut
     */
    @WebEndpoint(name = "SI_CSD_EmpPickUpCommission_OutPort")
    public SICSDEmpPickUpCommissionOut getSICSDEmpPickUpCommissionOutPort(WebServiceFeature... features) {
        return super.getPort(SICSDEmpPickUpCommissionOutPort, SICSDEmpPickUpCommissionOut.class, features);
    }

}
