package com.firstflight.mm.csdtosap.goodsreceipts;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-09-03T12:20:20.052+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/GoodsReceipt", name = "SI_CSD_GoodsReceipt_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDGoodsReceiptOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_GoodsReceipt_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDGoodsReceiptOut(
        @WebParam(partName = "MT_CSD_GoodsReceipt", name = "MT_CSD_GoodsReceipt", targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/GoodsReceipt")
        DTCSDGoodsReceipt mtCSDGoodsReceipt
    );
}
