
package com.firstflight.mm.csdtosap.goodsreceipts;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-09-03T12:20:19.865+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDGoodsReceiptOut_SICSDGoodsReceiptOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDGoodsReceiptOut_SICSDGoodsReceiptOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/MM/CSDToSAP/GoodsReceipt", "SI_CSD_GoodsReceipt_OutService");

    private SICSDGoodsReceiptOut_SICSDGoodsReceiptOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDGoodsReceiptOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDGoodsReceiptOut_SICSDGoodsReceiptOutPort_Client::main::error::",e);
            }
        }
      
        SICSDGoodsReceiptOutService ss = new SICSDGoodsReceiptOutService(wsdlURL, SERVICE_NAME);
        SICSDGoodsReceiptOut port = ss.getSICSDGoodsReceiptOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDGoodsReceiptOut...");
        com.firstflight.mm.csdtosap.goodsreceipts.DTCSDGoodsReceipt _siCSDGoodsReceiptOut_mtCSDGoodsReceipt = new com.firstflight.mm.csdtosap.goodsreceipts.DTCSDGoodsReceipt();
        java.util.List<com.firstflight.mm.csdtosap.goodsreceipts.DTCSDGoodsReceipt.GoodsReceipt> _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceipt = new java.util.ArrayList<com.firstflight.mm.csdtosap.goodsreceipts.DTCSDGoodsReceipt.GoodsReceipt>();
        com.firstflight.mm.csdtosap.goodsreceipts.DTCSDGoodsReceipt.GoodsReceipt _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1 = new com.firstflight.mm.csdtosap.goodsreceipts.DTCSDGoodsReceipt.GoodsReceipt();
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setTimestamp("Timestamp-2137562335");
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setSAPStatus("SAPStatus-724896315");
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setROWNUMBER(new java.math.BigInteger("8638684790047146700135987940176315233"));
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setRECEIVEDDATE(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-05-17T11:47:27.923+05:30"));
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setREQUISITIONNUMBER("REQUISITIONNUMBER-1963228360");
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setITEMTYPECODE("ITEMTYPECODE-1251418467");
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setITEMCODE("ITEMCODE2078551527");
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setDESCRIPTION("DESCRIPTION1559255227");
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setUNITOFMEASURE("UNITOFMEASURE-651065205");
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setRECEIVEDQUANTITY(new java.math.BigInteger("34519136366724433383620664728033445945"));
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1.setACKNOWLEDGEMENTNUMBER("ACKNOWLEDGEMENTNUMBER-248503492");
        _siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceipt.add(_siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceiptVal1);
        _siCSDGoodsReceiptOut_mtCSDGoodsReceipt.getGoodsReceipt().addAll(_siCSDGoodsReceiptOut_mtCSDGoodsReceiptGoodsReceipt);
        port.siCSDGoodsReceiptOut(_siCSDGoodsReceiptOut_mtCSDGoodsReceipt);


        }

        System.exit(0);
    }

}
