
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.mm.csdtosap.goodsreceipts;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-09-03T12:20:20.021+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_GoodsReceipt_OutService",
                      portName = "SI_CSD_GoodsReceipt_OutPort",
                      targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/GoodsReceipt",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FGoodsReceipt%5ESI_CSD_GoodsReceipt_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                      endpointInterface = "com.firstflight.mm.csdtosap.goodsreceipt.SICSDGoodsReceiptOut")
                      
public class SICSDGoodsReceiptOutImpl implements SICSDGoodsReceiptOut {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDGoodsReceiptOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.mm.csdtosap.goodsreceipt.SICSDGoodsReceiptOut#siCSDGoodsReceiptOut(com.firstflight.mm.csdtosap.goodsreceipt.DTCSDGoodsReceipt  mtCSDGoodsReceipt )*
     */
    public void siCSDGoodsReceiptOut(DTCSDGoodsReceipt mtCSDGoodsReceipt) { 
    	LOGGER.info("Executing operation siCSDGoodsReceiptOut");
    	  LOGGER.debug("mtCSDGoodsReceipt::"+mtCSDGoodsReceipt);
        try {
        } catch (java.lang.Exception ex) {
        	LOGGER.error("SICSDGoodsReceiptOutImpl::siCSDGoodsReceiptOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
