USE CorpUDAAN;
INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'M001'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('Pune – Aundh','Pune – Aundh','Pune – Aundh','PUNE','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '411007'),(select PINCODE_ID  from ff_d_pincode where pincode = '411007'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('M001',(select  SUM(LAST_GENERATED_SEQUENCE+2) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'M001'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('Pune – Aundh','Pune – Aundh','Pune – Aundh','PUNE','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '411007'),(select PINCODE_ID  from ff_d_pincode where pincode = '411007'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('M001',(select  SUM(LAST_GENERATED_SEQUENCE+3) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'M042'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('Pune – Warje','Pune – Warje','Pune – Warje','PUNE','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '411058'),(select PINCODE_ID  from ff_d_pincode where pincode = '411058'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('M042',(select  SUM(LAST_GENERATED_SEQUENCE+4) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'M025'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('Pune - Paud Road','Pune - Paud Road','Pune - Paud Road','PUNE','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '411029'),(select PINCODE_ID  from ff_d_pincode where pincode = '411029'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('M025',(select  SUM(LAST_GENERATED_SEQUENCE+5) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'M036'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('Pune – Station','Pune – Station','Pune – Station','PUNE','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '411001'),(select PINCODE_ID  from ff_d_pincode where pincode = '411001'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('M036',(select  SUM(LAST_GENERATED_SEQUENCE+6) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D015'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('CP - II','CP - II','CP - II','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110001'),(select PINCODE_ID  from ff_d_pincode where pincode = '110001'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D015',(select  SUM(LAST_GENERATED_SEQUENCE+7) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D028'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('NARAINA','NARAINA','NARAINA','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110028'),(select PINCODE_ID  from ff_d_pincode where pincode = '110028'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D028',(select  SUM(LAST_GENERATED_SEQUENCE+8) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D028'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('NARAINA','NARAINA','NARAINA','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110028'),(select PINCODE_ID  from ff_d_pincode where pincode = '110028'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D028',(select  SUM(LAST_GENERATED_SEQUENCE+9) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D032'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('PEERAGARHI','PEERAGARHI','PEERAGARHI','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110087'),(select PINCODE_ID  from ff_d_pincode where pincode = '110087'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D032',(select  SUM(LAST_GENERATED_SEQUENCE+10) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D036'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('TRANS YAMUNA','TRANS YAMUNA','TRANS YAMUNA','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110092'),(select PINCODE_ID  from ff_d_pincode where pincode = '110092'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D036',(select  SUM(LAST_GENERATED_SEQUENCE+11) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D041'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('PRITAM PURA','PRITAM PURA','PRITAM PURA','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110034'),(select PINCODE_ID  from ff_d_pincode where pincode = '110034'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D041',(select  SUM(LAST_GENERATED_SEQUENCE+12) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D053'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('TILAK NAGAR','TILAK NAGAR','TILAK NAGAR','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110027'),(select PINCODE_ID  from ff_d_pincode where pincode = '110027'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D053',(select  SUM(LAST_GENERATED_SEQUENCE+13) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D901'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('ROHINI','ROHINI','ROHINI','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110085'),(select PINCODE_ID  from ff_d_pincode where pincode = '110085'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D901',(select  SUM(LAST_GENERATED_SEQUENCE+14) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D004'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('ROHINI','ROHINI','ROHINI','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110085'),(select PINCODE_ID  from ff_d_pincode where pincode = '110085'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D004',(select  SUM(LAST_GENERATED_SEQUENCE+15) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D004'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('ROHINI','ROHINI','ROHINI','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110085'),(select PINCODE_ID  from ff_d_pincode where pincode = '110085'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D004',(select  SUM(LAST_GENERATED_SEQUENCE+16) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D004'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('ROHINI','ROHINI','ROHINI','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110085'),(select PINCODE_ID  from ff_d_pincode where pincode = '110085'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D004',(select  SUM(LAST_GENERATED_SEQUENCE+17) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D905'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('MJR CLIENTS','MJR CLIENTS','MJR CLIENTS','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '110002'),(select PINCODE_ID  from ff_d_pincode where pincode = '110002'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D905',(select  SUM(LAST_GENERATED_SEQUENCE+18) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D905'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('MJR CLIENTS','MJR CLIENTS','MJR CLIENTS','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '122001'),(select PINCODE_ID  from ff_d_pincode where pincode = '122001'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D905',(select  SUM(LAST_GENERATED_SEQUENCE+19) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D905'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('MJR CLIENTS','MJR CLIENTS','MJR CLIENTS','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '122001'),(select PINCODE_ID  from ff_d_pincode where pincode = '122001'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D905',(select  SUM(LAST_GENERATED_SEQUENCE+20) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D905'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('MJR CLIENTS','MJR CLIENTS','MJR CLIENTS','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '122001'),(select PINCODE_ID  from ff_d_pincode where pincode = '122001'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D905',(select  SUM(LAST_GENERATED_SEQUENCE+21) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D905'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('MJR CLIENTS','MJR CLIENTS','MJR CLIENTS','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '122001'),(select PINCODE_ID  from ff_d_pincode where pincode = '122001'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D905',(select  SUM(LAST_GENERATED_SEQUENCE+22) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D905'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('MJR CLIENTS','MJR CLIENTS','MJR CLIENTS','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '122001'),(select PINCODE_ID  from ff_d_pincode where pincode = '122001'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D905',(select  SUM(LAST_GENERATED_SEQUENCE+23) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');

INSERT INTO ff_d_pickup_delivery_contract (CUSTOMER_ID,OFFICE_ID,CONTRACT_TYPE,STATUS,CREATED_BY,UPDATE_BY,DT_TO_BRANCH) values (45444,(select office_id from ff_d_office where office_code = 'D905'),'P','A',28,28,'N');
INSERT INTO ff_d_address  (NAME,ADDRESS1,ADDRESS2,ADDRESS3,CONTACT_PERSON,DESIGNATION,STATUS,CITY,PINCODE,DT_TO_BRANCH) values ('MJR CLIENTS','MJR CLIENTS','MJR CLIENTS','Delhi','NA','NA','A',(select CITY_ID from ff_d_pincode where pincode = '122001'),(select PINCODE_ID  from ff_d_pincode where pincode = '122001'),'N');
INSERT INTO ff_d_pickup_delivery_location(CONTRACT_ID,ADDRESS,LOCATION_CODE,DT_TO_BRANCH)  values ((select max(CONTRACT_ID) from ff_d_pickup_delivery_contract) ,(select max(ADDRESS_ID) from ff_d_address) ,concat('D905',(select  SUM(LAST_GENERATED_SEQUENCE+24) from cg_d_sequence_gen where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE')),'N');
INSERT INTO ff_d_contract_payment_billing_location (PICKUP_DELIVERY_LOCATION,SHIPPED_TO_CODE,RATE_CONTRACT,CREATED_BY,UPDATE_BY,DT_TO_BRANCH,STATUS) values ((select max(LOCATION_ID) from ff_d_pickup_delivery_location ),'1037283',45445,28,28,'N','A');



update cg_d_sequence_gen set LAST_GENERATED_SEQUENCE = LAST_GENERATED_SEQUENCE+23 where PROCESS_REQUESTING = 'CONTRACT_CUST_CODE';

update ff_d_rate_contract set DT_TO_BRANCH = 'N';