ALTER TABLE `CorpUDAAN`.`ff_f_collection` MODIFY COLUMN `TOTAL_COLLECTION_AMOUNT` DOUBLE(20,2) DEFAULT '0.00';

ALTER TABLE `CorpUDAAN`.`ff_f_collection_entries` MODIFY COLUMN `BILL_AMOUNT` DOUBLE(20,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_collection_entries` MODIFY COLUMN `RECEIVED_AMOUNT` DOUBLE(20,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_collection_entries` MODIFY COLUMN `TDS_AMOUNT` DOUBLE(20,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_collection_entries` MODIFY COLUMN `DEDUCTION` DOUBLE(20,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_collection_entries` MODIFY COLUMN `TOTAL_BILL_AMOUNT` DOUBLE(20,2) DEFAULT '0.00';

ALTER TABLE `CorpUDAAN`.`ff_f_liability_payment` MODIFY COLUMN `LIABILTIY_AMOUNT` DOUBLE(20,2) DEFAULT '0.00';

ALTER TABLE `CorpUDAAN`.`ff_f_liability_entries` MODIFY COLUMN `COD_LC_AMT` DOUBLE(20,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_liability_entries` MODIFY COLUMN `COLLECTED_AMT` DOUBLE(20,2) DEFAULT '0.00';
ALTER TABLE `CorpUDAAN`.`ff_f_liability_entries` MODIFY COLUMN `PAID_AMT` DOUBLE(20,2) DEFAULT '0.00';


