package com.firstflight.hr.csdtosap.emppickndelivercount;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-01-11T12:56:52.977+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/HR/CSDToSAP/EmpPickNDeliverCount", name = "SI_CSD_EmpPickNDeliverCount_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDEmpPickNDeliverCountOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_EmpPickNDeliverCount_In", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDEmpPickNDeliverCountIn(
        @WebParam(partName = "MT_CSD_EmpPickNDeliverCount", name = "MT_CSD_EmpPickNDeliverCount", targetNamespace = "http://FirstFlight.com/HR/CSDToSAP/EmpPickNDeliverCount")
        DTCSDEmpPickNDeliverCount mtCSDEmpPickNDeliverCount
    );
}
