/**
 * 
 */
package com.ff.to.stockmanagement;

import com.capgemini.lbs.framework.to.CGBaseTO;

/**
 * The Class StockIssueValidationTO.
 *
 * @author mohammes
 */
public class StockIssueValidationTO extends CGBaseTO {

/** The Constant serialVersionUID. */
private static final long serialVersionUID = 8609608449173778395L;

/** The stock item number. */
private String stockItemNumber;//Serial(consignment number to be validated ) (User input)

/** The issued to party type. */
private String issuedTOPartyType;//BO/EMP/FR/Customer/BA etc (Optional Mandatory User input)

/** The issued to party id. */
private Integer issuedTOPartyId;//BO ID /EMP ID/FR ID/customer ID/BA ID (Optional Mandatory User input)

/** The series type. */
private String seriesType;  // Type of the given number(series) ( Mandatory User input)


/** The is issued. */
private Boolean isIssued=Boolean.FALSE; // Whether the stock item is issued or not  (program Outcome)

/** The is issued to party. */
private Boolean isIssuedTOParty=Boolean.FALSE; // whether the stock item is issued to the input party (program Outcome)

/** The issued to. */
private StockUserTO issuedTO; // the party to whom the stock is actually issued (program Outcome)


/** The region code. */
private String regionCode;  // logged in office Region Code (Optional Mandatory User input )

/** The rho code. */
private String rhoCode;  // logged in office RHO Code (Optional Mandatory User input )

/** The city code. */
private String cityCode;  // logged in office City Code (Optional Mandatory User input)

/** The office code. */
private String officeCode; //logged in office Code

/** The office product code. */
private String officeProductCode;//contains Plant +Product (program generated value)

/** The leaf. */
private Long leaf;//leaf details (program generated value)

/** The series length. */
private int seriesLength;//leaf details (program generated value)

private int expectedSeriesLength;

private Integer itemId;//generated by system

private Integer issuingOfficeId;

/** issued To Pickup Boy. */
private String issuedToPickupBoy; //consg is issued to pickup boy or not

private Integer loggedInCityId;//for BA Booking this should not be null



/**
 * Gets the stock item number.
 *
 * @return the stock item number
 */
public String getStockItemNumber() {
	return stockItemNumber;
}

/**
 * Sets the stock item number.
 *
 * @param stockItemNumber the new stock item number
 */
public void setStockItemNumber(String stockItemNumber) {
	this.stockItemNumber = stockItemNumber;
}

/**
 * Gets the issued to party type.
 *
 * @return the issued to party type
 */
public String getIssuedTOPartyType() {
	return issuedTOPartyType;
}

/**
 * Sets the issued to party type.
 *
 * @param issuedTOPartyType the new issued to party type
 */
public void setIssuedTOPartyType(String issuedTOPartyType) {
	this.issuedTOPartyType = issuedTOPartyType;
}

/**
 * Gets the issued to party id.
 *
 * @return the issued to party id
 */
public Integer getIssuedTOPartyId() {
	return issuedTOPartyId;
}

/**
 * Sets the issued to party id.
 *
 * @param issuedTOPartyId the new issued to party id
 */
public void setIssuedTOPartyId(Integer issuedTOPartyId) {
	this.issuedTOPartyId = issuedTOPartyId;
}

/**
 * Gets the checks if is issued.
 *
 * @return the checks if is issued
 */
public Boolean getIsIssued() {
	return isIssued;
}

/**
 * Sets the checks if is issued.
 *
 * @param isIssued the new checks if is issued
 */
public void setIsIssued(Boolean isIssued) {
	this.isIssued = isIssued;
}

/**
 * Gets the checks if is issued to party.
 *
 * @return the checks if is issued to party
 */
public Boolean getIsIssuedTOParty() {
	return isIssuedTOParty;
}

/**
 * Sets the checks if is issued to party.
 *
 * @param isIssuedTOParty the new checks if is issued to party
 */
public void setIsIssuedTOParty(Boolean isIssuedTOParty) {
	this.isIssuedTOParty = isIssuedTOParty;
}

/**
 * Gets the issued to.
 *
 * @return the issued to
 */
public StockUserTO getIssuedTO() {
	return issuedTO;
}

/**
 * Sets the issued to.
 *
 * @param issuedTO the new issued to
 */
public void setIssuedTO(StockUserTO issuedTO) {
	this.issuedTO = issuedTO;
}

/**
 * Gets the office product code.
 *
 * @return the office product code
 */
public String getOfficeProductCode() {
	return officeProductCode;
}

/**
 * Sets the office product code.
 *
 * @param officeProductCode the new office product code
 */
public void setOfficeProductCode(String officeProductCode) {
	this.officeProductCode = officeProductCode;
}

/**
 * Gets the leaf.
 *
 * @return the leaf
 */
public Long getLeaf() {
	return leaf;
}

/**
 * Sets the leaf.
 *
 * @param leaf the new leaf
 */
public void setLeaf(Long leaf) {
	this.leaf = leaf;
}

/**
 * Gets the region code.
 *
 * @return the regionCode
 */
public String getRegionCode() {
	return regionCode;
}

/**
 * Sets the region code.
 *
 * @param regionCode the regionCode to set
 */
public void setRegionCode(String regionCode) {
	this.regionCode = regionCode;
}

/**
 * Gets the series type.
 *
 * @return the seriesType
 */
public String getSeriesType() {
	return seriesType;
}

/**
 * Sets the series type.
 *
 * @param seriesType the seriesType to set
 */
public void setSeriesType(String seriesType) {
	this.seriesType = seriesType;
}

/**
 * Gets the series length.
 *
 * @return the seriesLength
 */
public int getSeriesLength() {
	return seriesLength;
}

/**
 * Sets the series length.
 *
 * @param seriesLength the seriesLength to set
 */
public void setSeriesLength(int seriesLength) {
	this.seriesLength = seriesLength;
}

/**
 * Gets the city code.
 *
 * @return the cityCode
 */
public String getCityCode() {
	return cityCode;
}

/**
 * Sets the city code.
 *
 * @param cityCode the cityCode to set
 */
public void setCityCode(String cityCode) {
	this.cityCode = cityCode;
}

/**
 * Gets the rho code.
 *
 * @return the rhoCode
 */
public String getRhoCode() {
	return rhoCode;
}

/**
 * Sets the rho code.
 *
 * @param rhoCode the rhoCode to set
 */
public void setRhoCode(String rhoCode) {
	this.rhoCode = rhoCode;
}

/**
 * Gets the office code.
 *
 * @return the officeCode
 */
public String getOfficeCode() {
	return officeCode;
}

/**
 * Sets the office code.
 *
 * @param officeCode the officeCode to set
 */
public void setOfficeCode(String officeCode) {
	this.officeCode = officeCode;
}

/**
 * @return the expectedSeriesLength
 */
public int getExpectedSeriesLength() {
	return expectedSeriesLength;
}

/**
 * @param expectedSeriesLength the expectedSeriesLength to set
 */
public void setExpectedSeriesLength(int expectedSeriesLength) {
	this.expectedSeriesLength = expectedSeriesLength;
}

/**
 * @return the itemId
 */
public Integer getItemId() {
	return itemId;
}

/* (non-Javadoc)
 * @see java.lang.Object#toString()
 */
@Override
public String toString() {
	return "\t Input details of StockIssueValidationTO details [stockItemNumber=" + stockItemNumber
			+ ", issuedTOPartyType=" + issuedTOPartyType + ", issuedTOPartyId="
			+ issuedTOPartyId + ", seriesType=" + seriesType + ", officeCode="
			+ officeCode + ", leaf=" + leaf + ", seriesLength=" + seriesLength
			+ ", expectedSeriesLength=" + expectedSeriesLength + ", itemId="
			+ itemId + "]";
}

/**
 * @param itemId the itemId to set
 */
public void setItemId(Integer itemId) {
	this.itemId = itemId;
}

/**
 * @return the issuingOfficeId
 */
public Integer getIssuingOfficeId() {
	return issuingOfficeId;
}

/**
 * @param issuingOfficeId the issuingOfficeId to set
 */
public void setIssuingOfficeId(Integer issuingOfficeId) {
	this.issuingOfficeId = issuingOfficeId;
}

/**
 * @return the issuedToPickupBoy
 */
public String getIssuedToPickupBoy() {
	return issuedToPickupBoy;
}

/**
 * @param issuedToPickupBoy the issuedToPickupBoy to set
 */
public void setIssuedToPickupBoy(String issuedToPickupBoy) {
	this.issuedToPickupBoy = issuedToPickupBoy;
}

/**
 * @return the loggedInCityId
 */
public Integer getLoggedInCityId() {
	return loggedInCityId;
}

/**
 * @param loggedInCityId the loggedInCityId to set
 */
public void setLoggedInCityId(Integer loggedInCityId) {
	this.loggedInCityId = loggedInCityId;
}



}
