package com.ff.web.manifest.constants;

public interface ManifestErrorCodesConstants {
	String CONSGNMENT_MANIFESTED = "M001";
	String CONSG_NOT_FOUND = "M002";
	String PIN_NOT_SERVICE_FFCL = "M003";
	String PIN_NOT_SERVICE_DEST = "M004";
	String MANIFEST_SAVED_SUCCESSFULLY = "M005";
	String CONSG_MANIFEST_NOT_FOUND = "M006";
	String MANIFEST_NOT_ISSUED_REGION = "M007";
	String IS_MANIFESTED = "M008";
	String CONSGNMENT_UPDATION_FAIL = "M009";
	String CONSGNMENT_DTLS_NOT_EXIST = "M010";
	String INVALID_REGION = "M011";
	String PRODUCT_NOT_ALLOWED = "M012";
	String MANIFEST_CLOSED_SUCCESSFULLY = "M013";
	String MANIFEST_NOT_SAVED = "M014";
	String UNKNOWN_EXCEPTION_OCURRED = "M015";
	String ALLOW_PARCEL_TYPE_CONSG = "M016";
	String ALLOW_DOX_TYPE_CONSG = "M020";
	String PACKET_PARCEL_CONSIGNMENT_EXIST = "M038";
	String MANIFEST_ALREADY_EXISTS = "M039";
	String CONTENTS_MANDATORY_FOR_PARCEL_MANIFEST = "M040";
	String MANIFEST_DETAILS_NOT_FOUND = "M041";
	String MANIFEST_SAVED_CLOSED_SUCCESSFULLY = "M042";
	String MANIFEST_ALREADY_CLOSED = "M048";
	String MANIFEST_NOT_CLOSED = "M047";
	String MANIFEST_SEARCH_DETAILS_NOT_FOUND = "M045";
	String NO_ROUTE_FOR_ORIGIN_DEST = "M046";
	String CN_NOT_IN_MANIFESTED = "M044";
	String CN_NOTBOOKED_NOR_IN_MANIFESTED = "M049";
	String MANIFEST_INVALID = "M050";
	String MANIFEST_ALREADY_EMBEDDED = "M051";
	String DESTINATION_NOT_SERVICED = "M052";
	String NO_ROUTE_FOUND = "M053";
	String ROUTE_FOUND = "M054";
	String BAG_LOCK_ALREADY_USED = "M055";
	String INVALID_RADIO_FREQUENCY = "M056";
	String INVALID_OFFICE = "M057";
	String CONSG_STATUS_NULL = "M060";
	String TRANSHIPMENT_CITY_DTLS_NOT_EXIST = "M061";
	String CN_NOTBOOKED_IN_OPERATING_OFFICE = "M065";
	String INVALID_THIRD_PARTY_TYPE_MANIFEST = "M068";
	String CN_ALREADY_IN_DRS_PROCESS = "M071";
	String NOT_VALID_PINCODE = "B001";
	String INVALID_CONSIGNMENT_NUMBER = "RHM001";

	String PACKET_IS_EMBEDDED = "OMBPL001";
	String INVALIED_BPL_OUT_MANIFEST_DOX = "OMBPL002";
	String MANIFEST_NO_IS_NOT_CLOSED = "OMBPL003";

	String MISROUTE_DETAILS_NOT_AVAILABLE = "MIS001";
	String DETAILS_DOES_NOT_EXIST = "MIS002";
	String CONSG_TYPE_DTLS_NOT_EXIST = "MIS003";
	String MISROUTE_TYPE_DTLS_NOT_EXIST = "MIS004";
	String REGION_DTLS_NOT_EXIST = "MIS005";
	String MANIFEST_NOT_IN_MANIFESTED = "MIS006";
	String MANIFEST_DTLS_NOT_FOUND = "MIS007";
	String MANIFEST_NO_USED_TO_CREATE_ANOTHER = "MIS008";
	String CONSIGNMENT_CANNOT_BE_MISROUTED = "MIS009";
	String CONSIGNMENT_NOT_IN_PICKUP = "MIS010";
	String OFFICE_DTLS_NOT_EXIST = "MIS011";
	String CITY_DTLS_NOT_EXIST = "MIS012";
	String INVALID_CONG_TYPE = "MIS013";
	String DRS_PREPARED_ALREADY_FOR_CONSG = "MIS014";
	String DRS_CONSG_DELIVERED = "MIS015";
	String DRS_CONSG_PENDING = "MIS016";

	String DB_ERR_PLS_TRY_AGAIN = "E0002";
	String LOAD_NO_NOT_POPULATED = "TP001";
	String CONFIG_PARAM_NOT_SET_FOR_TPBP = "TP002";
	String THIRD_PARTY_TYPE_NOT_POPULATED = "TP003";
	String THIRD_PARTY_NAME_NOT_POPULATED = "TP004";

	/* Out Manifest Rate Calculation */
	String RATE_NOT_CALC_FOR_CN = "OMRC001";
	String RATE_NOT_CALC_FOR_CN_2 = "OMRC002";
	String POSSIBLE_OPERATION_PERFORMED_ON_MANIFEST = "MIS017";
	String MANIFEST_ALREADY_OUT_MANIFESTED = "MIS018";

	String CN_IS_ALREADY_MISROUTE = "M062";
	String SCANNED_MANIFEST_NO_NOT_VALID = "M063";
	String CN_ALREADY_RTO = "M064";
	String CN_ALREADY_DELIVERED = "M066";
	String CONSIGNMENT_STOPDELV = "M067";
	String CONSIGNMENT_IS_CHILD_CN = "M070";

}
