/**
 * 
 */
package com.ff.to.drs;

import java.util.Map;

import com.capgemini.lbs.framework.to.CGBaseTO;

/**
 * The Class AbstractDeliveryTO.
 *
 * @author mohammes
 */
public abstract class AbstractDeliveryTO extends CGBaseTO{

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 6251901714852668094L;
	
	
	/** The login office id. */
	private Integer loginOfficeId;
	
	/** The login office code. */
	private String loginOfficeCode;
	
	/** The login office name. */
	private String loginOfficeName;
	
	
	/** The login region id. */
	private Integer loginRegionId;
	
	
	/** The login region code. */
	private String loginRegionCode;
	
	/** The login city id. */
	private Integer loginCityId;
	
	
	/** The login city code. */
	private String loginCityCode;
	
	/** The drs number. */
	private String drsNumber;
	
	/** The load number. */
	private Integer loadNumber;
	
	/** The yp drs. */
	private String ypDrs;
	
	/** The drs date time str. */
	private String drsDateTimeStr;
	
	/** The drs for. */
	private String drsFor;
	
	/** The consignment type. */
	private String consignmentType;//DOx or PPX
	
	
	
	/** it's for Out-Time date(DDMMYYYYonly) in the screen*/
	private String fsOutTimeDateStr;
	
	
	/** it's for Out-Time in minutes(MM) in the screen*/
	private String fsOutTimeMMStr;
	
	/** it's for Out-Time in HR(HH) in the screen*/
	private String fsOutTimeHHStr;
	
	/** it's for in-time date(DDMMYYYYonly) in the screen*/
	private String fsInTimeDateStr;
	/** it's for in-time MIN(MM) in the screen*/
	private String fsInTimeMMStr;
	/** it's for in-time MIN(HH) in the screen*/
	private String fsInTimeHHStr;
	
	
	
	
	
	/** The drs screen Code. */
	private String drsScreenCode;
	
	/** The drs party id. */
	private Integer drsPartyId;
	
	/** The consigmnt type ppx. */
	private String consigmntTypePpx;
	
	/** The consigmnt type dox. */
	private String consigmntTypeDox;
	
	/** The delivery id. */
	private Long deliveryId;
	
	/** The update delivered url. */
	private String updateDeliveredUrl;
	
	/** The drs office name.  Login User Branch/Hub detail*/
	private String drsOfficeName;
	
	/** The logged in user id. */
	private Integer loggedInUserId;
	
	/** The created by user id. */
	private Integer createdByUserId;
	
	private String canCreateRows;
	
	/** The drs type. It tells whether its a DRS Preparation /updatation
	 * P-preparation
	 * U-update
	 * */
	private String drsType;
	
	
	/** The manifest drs type.  It's refers to the screen dropdown value*/
	private String manifestDrsType;
	
	/** The manifest drs type drs. it's constant for manifestDrsType DRS */
	private String manifestDrsTypeDrs;
	
	/** The manifest drs type drs. it's constant for manifestDrsType Manifest */
	private String manifestDrsTypeMnfst;
	
	/** The pending drs screen code. It' for alert purpose */
	private String pendingDrsScreenCode;
	
	private String autoGeneratedManualDrsNumber;
	
	
	
	/** The manifest type for validations. */
	private String manifestDirection;
	
	/** The process code. it's used at the time validations*/
	private String processCode;
	
	/** The query name. */
	private String queryName;
	
	private String loggedInOfficeType;
	
	/**
	 * @return the fsInTimeDateStr
	 */
	public String getFsInTimeDateStr() {
		return fsInTimeDateStr;
	}

	

	/**
	 * @param fsInTimeDateStr the fsInTimeDateStr to set
	 */
	public void setFsInTimeDateStr(String fsInTimeDateStr) {
		this.fsInTimeDateStr = fsInTimeDateStr;
	}

	

	private String dlvTypeOffice;
	
	private String companySealAndSign;
	
	private String dlvTypeNonDlv;
	
	
	/** The consignment number. : it's Only for validations purpose
	 *  please donot use this property anywhere except for consignment validations
	 *  */
	private String consignmentNumber;
	
	/** The is drs dicarded. */
	private String isDrsDicarded;
	
	/** The series q. */
	private String seriesQ;
	
	/** The series c. */
	private String seriesC;
	
	/** The series d. */
	private String seriesD;
	
	/** The series L. */
	private String seriesL;
	
	/** The series T. */
	private String seriesT;
	
	
	/** The party type map.  For Employee/DA code in the Screen*/
	private Map<Integer,String> partyTypeMap;
	
	/** The drs status.
	 * DRS Status Open(DRS prepared)
	 * /updated(updated all un delivered cns)
	 * /closed (updated all delivered cns 
	 * &process compltd) */
	private String drsStatus;//Open/update or closed
	
	private String drsStatusUpdate;//update
	
	private String drsStatusClosed;
	
	/** The allowed series. it holds Cnote  product details which are allowed in the respective screens */
	private String allowedSeries;
	
	/** The is normal cnote allowed. */
	private String isNormalCnoteAllowed="N";
	
	/** The comail product. */
	private String comailStartsWith;
	
	
	/** The flag yes. */
	private String flagYes;
	
	
		/** The flag no. */
	private String flagNo;
	
	/** The consg num length. */
	private Integer consgNumLength;
	
	/**
	 * @return the canCreateRows
	 */
	public String getCanCreateRows() {
		return canCreateRows;
	}

	/**
	 * @param canCreateRows the canCreateRows to set
	 */
	public void setCanCreateRows(String canCreateRows) {
		this.canCreateRows = canCreateRows;
	}

	/** The comail length. */
	private Integer comailLength;
	
	/**
	 * @return the manifestDrsTypeDrs
	 */
	public String getManifestDrsTypeDrs() {
		return manifestDrsTypeDrs;
	}

	/**
	 * @return the pendingDrsScreenCode
	 */
	public String getPendingDrsScreenCode() {
		return pendingDrsScreenCode;
	}

	/**
	 * @param pendingDrsScreenCode the pendingDrsScreenCode to set
	 */
	public void setPendingDrsScreenCode(String pendingDrsScreenCode) {
		this.pendingDrsScreenCode = pendingDrsScreenCode;
	}

	/**
	 * @return the manifestDrsTypeMnfst
	 */
	public String getManifestDrsTypeMnfst() {
		return manifestDrsTypeMnfst;
	}

	/**
	 * @param manifestDrsTypeDrs the manifestDrsTypeDrs to set
	 */
	public void setManifestDrsTypeDrs(String manifestDrsTypeDrs) {
		this.manifestDrsTypeDrs = manifestDrsTypeDrs;
	}

	/**
	 * @param manifestDrsTypeMnfst the manifestDrsTypeMnfst to set
	 */
	public void setManifestDrsTypeMnfst(String manifestDrsTypeMnfst) {
		this.manifestDrsTypeMnfst = manifestDrsTypeMnfst;
	}

	/** The success message. once data saved/updated , programmer need to inspect this property for message */
	private String successMessage;
	
	/** The reasons for mis card. :: It holds All reason Codes for which 
	 * Missed you card number is required and it comes from config params */
	private String reasonsForMisCard;
	
	private Boolean isPricingInfoRequired = false;
	
	//For FS IN/out and dlv date/time validations start
	/** The current date str. */
	private String currentDateStr;
	
	/** The current time str. */
	private String currentTimeStr;
	
	/** The created date str. */
	private String createdDateStr;
	
	/** The created time str. */
	private String createdTimeStr;
	
	/** The updated date str. */
	private String updatedDateStr;
	
	/** The updated time str. */
	private String updatedTimeStr;
	//For FS IN/out and dlv date/time validations END
	
	/** The max allowed rows. */
	private Integer maxAllowedRows;
	
	/** The max allowed print rows. */
	private Integer maxAllowedPrintRows;
	//For Grid Data
	
	/** The row count. */
	public int rowCount;
	
	/** The can update. */
	public  String canUpdate;
	
	/** The row id. */
	private  Integer  rowId [] = new Integer[rowCount];
	
	/** The row delivery detail id. */
	private  Long  rowDeliveryDetailId [] = new Long[rowCount];
	
	/** The row origin city. */
	private  Integer  rowOriginCityId [] = new Integer[rowCount];
	/** The row origin city Code */
	private  String  rowOriginCityCode [] = new String[rowCount];
	
	/** The row consignment number. */
	private  String  rowConsignmentNumber [] = new String[rowCount];
	
	private  Integer  rowConsignmentId [] = new Integer[rowCount];
	
	private  Integer  rowPendingReasonId [] = new Integer[rowCount];
	
	private  String  rowMissedCardNumber [] = new String[rowCount];
	

	private  String  rowRemarks [] = new String[rowCount];
	
	private Integer rowAttemptNumber[]= new Integer[rowCount];
	
	private String rowContactNumber[]= new String[rowCount];
	
	private String rowReceiverName[]= new String[rowCount];
	
	private String rowDeliveryType[]= new String[rowCount];
	
	

	//private String rowDeliveryTime[]= new String[rowCount];
	
	private String rowDeliveryTimeInHH[]= new String[rowCount];
	private String rowDeliveryTimeInMM[]= new String[rowCount];
	
	private String rowCompanySealSign[]= new String[rowCount];
	
	private  Integer rowNoOfPieces[]=new Integer[rowCount];
	
	private String rowParentChildCnType[]= new String[rowCount];
	
	private Integer rowRelationId [] = new Integer[rowCount];
	
	/**
	 *  The Row IdentityProofId
	 */
	private Integer rowIdentityProofId [] = new Integer[rowCount];
	
	private String rowIdNumber []= new String[rowCount];
	private String rowDeliveryStatus []= new String[rowCount];
	
	/** The pending status. */
	private String pendingStatus;
	
	/** The delivered status. */
	private String deliveredStatus;

	/**
	 * Gets the drs number.
	 *
	 * @return the drsNumber
	 */
	public String getDrsNumber() {
		return drsNumber;
	}
	
	/**
	 * Gets the load number.
	 *
	 * @return the loadNumber
	 */
	public Integer getLoadNumber() {
		return loadNumber;
	}
	
	/**
	 * Gets the yp drs.
	 *
	 * @return the ypDrs
	 */
	public String getYpDrs() {
		return ypDrs;
	}
	
	/**
	 * Gets the drs date time str.
	 *
	 * @return the drsDateTimeStr
	 */
	public String getDrsDateTimeStr() {
		return drsDateTimeStr;
	}
	
	/**
	 * Gets the drs for.
	 *
	 * @return the drsFor
	 */
	public String getDrsFor() {
		return drsFor;
	}
	
	/**
	 * Gets the consignment type.
	 *
	 * @return the consignmentType
	 */
	public String getConsignmentType() {
		return consignmentType;
	}
	
	
	
	
	/**
	 * Gets the drs party id.
	 *
	 * @return the drsPartyId
	 */
	public Integer getDrsPartyId() {
		return drsPartyId;
	}
	
	
	
	
	/**
	 * Sets the drs number.
	 *
	 * @param drsNumber the drsNumber to set
	 */
	public void setDrsNumber(String drsNumber) {
		this.drsNumber = drsNumber;
	}
	
	/**
	 * Sets the load number.
	 *
	 * @param loadNumber the loadNumber to set
	 */
	public void setLoadNumber(Integer loadNumber) {
		this.loadNumber = loadNumber;
	}
	
	/**
	 * Sets the yp drs.
	 *
	 * @param ypDrs the ypDrs to set
	 */
	public void setYpDrs(String ypDrs) {
		this.ypDrs = ypDrs;
	}
	
	/**
	 * Sets the drs date time str.
	 *
	 * @param drsDateTimeStr the drsDateTimeStr to set
	 */
	public void setDrsDateTimeStr(String drsDateTimeStr) {
		this.drsDateTimeStr = drsDateTimeStr;
	}
	
	/**
	 * Sets the drs for.
	 *
	 * @param drsFor the drsFor to set
	 */
	public void setDrsFor(String drsFor) {
		this.drsFor = drsFor;
	}
	
	/**
	 * Sets the consignment type.
	 *
	 * @param consignmentType the consignmentType to set
	 */
	public void setConsignmentType(String consignmentType) {
		this.consignmentType = consignmentType;
	}
	
	
	/**
	 * Sets the drs party id.
	 *
	 * @param drsPartyId the drsPartyId to set
	 */
	public void setDrsPartyId(Integer drsPartyId) {
		this.drsPartyId = drsPartyId;
	}
	
	

	/**
	 * Gets the login office code.
	 *
	 * @return the loginOfficeCode
	 */
	public String getLoginOfficeCode() {
		return loginOfficeCode;
	}

	/**
	 * Gets the login office name.
	 *
	 * @return the loginOfficeName
	 */
	public String getLoginOfficeName() {
		return loginOfficeName;
	}

	/**
	 * Sets the login office code.
	 *
	 * @param loginOfficeCode the loginOfficeCode to set
	 */
	public void setLoginOfficeCode(String loginOfficeCode) {
		this.loginOfficeCode = loginOfficeCode;
	}

	/**
	 * Sets the login office name.
	 *
	 * @param loginOfficeName the loginOfficeName to set
	 */
	public void setLoginOfficeName(String loginOfficeName) {
		this.loginOfficeName = loginOfficeName;
	}
	
	/**
	 * Gets the login office id.
	 *
	 * @return the loginOfficeId
	 */
	public Integer getLoginOfficeId() {
		return loginOfficeId;
	}
	
	/**
	 * Sets the login office id.
	 *
	 * @param loginOfficeId the loginOfficeId to set
	 */
	public void setLoginOfficeId(Integer loginOfficeId) {
		this.loginOfficeId = loginOfficeId;
	}
	
	/**
	 * Gets the consigmnt type ppx.
	 *
	 * @return the consigmntTypePpx
	 */
	public String getConsigmntTypePpx() {
		return consigmntTypePpx;
	}
	
	/**
	 * Sets the consigmnt type ppx.
	 *
	 * @param consigmntTypePpx the consigmntTypePpx to set
	 */
	public void setConsigmntTypePpx(String consigmntTypePpx) {
		this.consigmntTypePpx = consigmntTypePpx;
	}
	
	/**
	 * Gets the consigmnt type dox.
	 *
	 * @return the consigmntTypeDox
	 */
	public String getConsigmntTypeDox() {
		return consigmntTypeDox;
	}
	
	/**
	 * Sets the consigmnt type dox.
	 *
	 * @param consigmntTypeDox the consigmntTypeDox to set
	 */
	public void setConsigmntTypeDox(String consigmntTypeDox) {
		this.consigmntTypeDox = consigmntTypeDox;
	}
	
	/**
	 * Gets the delivery id.
	 *
	 * @return the deliveryId
	 */
	public Long getDeliveryId() {
		return deliveryId;
	}
	
	public Integer[] getRowIdentityProofId() {
		return rowIdentityProofId;
	}

	public void setRowIdentityProofId(Integer[] rowIdentityProofId) {
		this.rowIdentityProofId = rowIdentityProofId;
	}

	public String[] getRowIdNumber() {
		return rowIdNumber;
	}

	public void setRowIdNumber(String[] rowIdNumber) {
		this.rowIdNumber = rowIdNumber;
	}

	/**
	 * Gets the row count.
	 *
	 * @return the rowCount
	 */
	public int getRowCount() {
		return rowCount;
	}
	
	/**
	 * Gets the row id.
	 *
	 * @return the rowId
	 */
	public Integer[] getRowId() {
		return rowId;
	}
	
	/**
	 * @return the rowPendingReasonId
	 */
	public Integer[] getRowPendingReasonId() {
		return rowPendingReasonId;
	}

	/**
	 * @return the rowMissedCardNumber
	 */
	public String[] getRowMissedCardNumber() {
		return rowMissedCardNumber;
	}

	/**
	 * @param rowPendingReasonId the rowPendingReasonId to set
	 */
	public void setRowPendingReasonId(Integer[] rowPendingReasonId) {
		this.rowPendingReasonId = rowPendingReasonId;
	}

	/**
	 * @param rowMissedCardNumber the rowMissedCardNumber to set
	 */
	public void setRowMissedCardNumber(String[] rowMissedCardNumber) {
		this.rowMissedCardNumber = rowMissedCardNumber;
	}

	/**
	 * Gets the row delivery detail id.
	 *
	 * @return the rowDeliveryDetailId
	 */
	public Long[] getRowDeliveryDetailId() {
		return rowDeliveryDetailId;
	}
	
	
	
	/**
	 * Sets the delivery id.
	 *
	 * @param deliveryId the deliveryId to set
	 */
	public void setDeliveryId(Long deliveryId) {
		this.deliveryId = deliveryId;
	}
	
	/**
	 * Sets the row count.
	 *
	 * @param rowCount the rowCount to set
	 */
	public void setRowCount(int rowCount) {
		this.rowCount = rowCount;
	}
	
	/**
	 * Sets the row id.
	 *
	 * @param rowId the rowId to set
	 */
	public void setRowId(Integer[] rowId) {
		this.rowId = rowId;
	}
	
	/**
	 * Sets the row delivery detail id.
	 *
	 * @param rowDeliveryDetailId the rowDeliveryDetailId to set
	 */
	public void setRowDeliveryDetailId(Long[] rowDeliveryDetailId) {
		this.rowDeliveryDetailId = rowDeliveryDetailId;
	}
	
	
	
	/**
	 * Sets the row consignment number.
	 *
	 * @param rowConsignmentNumber the rowConsignmentNumber to set
	 */
	public void setRowConsignmentNumber(String[] rowConsignmentNumber) {
		this.rowConsignmentNumber = rowConsignmentNumber;
	}

	/**
	 * @return the loginRegionId
	 */
	public Integer getLoginRegionId() {
		return loginRegionId;
	}

	/**
	 * @return the loginRegionCode
	 */
	public String getLoginRegionCode() {
		return loginRegionCode;
	}

	/**
	 * @return the loginCityId
	 */
	public Integer getLoginCityId() {
		return loginCityId;
	}

	/**
	 * @return the loginCityCode
	 */
	public String getLoginCityCode() {
		return loginCityCode;
	}

	/**
	 * @return the updateDeliveredUrl
	 */
	public String getUpdateDeliveredUrl() {
		return updateDeliveredUrl;
	}

	/**
	 * @param loginRegionId the loginRegionId to set
	 */
	public void setLoginRegionId(Integer loginRegionId) {
		this.loginRegionId = loginRegionId;
	}

	/**
	 * @param loginRegionCode the loginRegionCode to set
	 */
	public void setLoginRegionCode(String loginRegionCode) {
		this.loginRegionCode = loginRegionCode;
	}

	/**
	 * @param loginCityId the loginCityId to set
	 */
	public void setLoginCityId(Integer loginCityId) {
		this.loginCityId = loginCityId;
	}

	/**
	 * @param loginCityCode the loginCityCode to set
	 */
	public void setLoginCityCode(String loginCityCode) {
		this.loginCityCode = loginCityCode;
	}

	/**
	 * @param updateDeliveredUrl the updateDeliveredUrl to set
	 */
	public void setUpdateDeliveredUrl(String updateDeliveredUrl) {
		this.updateDeliveredUrl = updateDeliveredUrl;
	}

	/**
	 * @return the rowOriginCityId
	 */
	public Integer[] getRowOriginCityId() {
		return rowOriginCityId;
	}

	/**
	 * @return the rowConsignmentNumber
	 */
	public String[] getRowConsignmentNumber() {
		return rowConsignmentNumber;
	}

	/**
	 * @param rowOriginCityId the rowOriginCityId to set
	 */
	public void setRowOriginCityId(Integer[] rowOriginCityId) {
		this.rowOriginCityId = rowOriginCityId;
	}

	/**
	 * @return the rowOriginCityCode
	 */
	public String[] getRowOriginCityCode() {
		return rowOriginCityCode;
	}

	
	/**
	 * @param rowOriginCityCode the rowOriginCityCode to set
	 */
	public void setRowOriginCityCode(String[] rowOriginCityCode) {
		this.rowOriginCityCode = rowOriginCityCode;
	}

	/**
	 * @return the drsOfficeName
	 */
	public String getDrsOfficeName() {
		return drsOfficeName;
	}

	/**
	 * @return the loggedInUserId
	 */
	public Integer getLoggedInUserId() {
		return loggedInUserId;
	}

	/**
	 * @return the createdByUserId
	 */
	public Integer getCreatedByUserId() {
		return createdByUserId;
	}

	/**
	 * @param loggedInUserId the loggedInUserId to set
	 */
	public void setLoggedInUserId(Integer loggedInUserId) {
		this.loggedInUserId = loggedInUserId;
	}

	/**
	 * @param createdByUserId the createdByUserId to set
	 */
	public void setCreatedByUserId(Integer createdByUserId) {
		this.createdByUserId = createdByUserId;
	}

	/**
	 * @param drsOfficeName the drsOfficeName to set
	 */
	public void setDrsOfficeName(String drsOfficeName) {
		this.drsOfficeName = drsOfficeName;
	}

	/**
	 * @return the rowConsignmentId
	 */
	public Integer[] getRowConsignmentId() {
		return rowConsignmentId;
	}

	/**
	 * @param rowConsignmentId the rowConsignmentId to set
	 */
	public void setRowConsignmentId(Integer[] rowConsignmentId) {
		this.rowConsignmentId = rowConsignmentId;
	}

	/**
	 * @return the drsScreenCode
	 */
	public String getDrsScreenCode() {
		return drsScreenCode;
	}

	/**
	 * @return the drsType
	 */
	public String getDrsType() {
		return drsType;
	}

	/**
	 * @param drsScreenCode the drsScreenCode to set
	 */
	public void setDrsScreenCode(String drsScreenCode) {
		this.drsScreenCode = drsScreenCode;
	}

	/**
	 * @param drsType the drsType to set
	 */
	public void setDrsType(String drsType) {
		this.drsType = drsType;
	}

	/**
	 * @return the consignmentNumber
	 */
	public String getConsignmentNumber() {
		return consignmentNumber;
	}

	/**
	 * @param consignmentNumber the consignmentNumber to set
	 */
	public void setConsignmentNumber(String consignmentNumber) {
		this.consignmentNumber = consignmentNumber;
	}

	/**
	 * @return the canUpdate
	 */
	public String getCanUpdate() {
		return canUpdate;
	}

	/**
	 * @param canUpdate the canUpdate to set
	 */
	public void setCanUpdate(String canUpdate) {
		this.canUpdate = canUpdate;
	}

	/**
	 * @return the isDrsDicarded
	 */
	public String getIsDrsDicarded() {
		return isDrsDicarded;
	}

	/**
	 * @param isDrsDicarded the isDrsDicarded to set
	 */
	public void setIsDrsDicarded(String isDrsDicarded) {
		this.isDrsDicarded = isDrsDicarded;
	}

	/**
	 * @return the partyTypeMap
	 */
	public Map<Integer, String> getPartyTypeMap() {
		return partyTypeMap;
	}

	/**
	 * @param partyTypeMap the partyTypeMap to set
	 */
	public void setPartyTypeMap(Map<Integer, String> partyTypeMap) {
		this.partyTypeMap = partyTypeMap;
	}

	

	

	/**
	 * @return the drsStatus
	 */
	public String getDrsStatus() {
		return drsStatus;
	}

	/**
	 * @param drsStatus the drsStatus to set
	 */
	public void setDrsStatus(String drsStatus) {
		this.drsStatus = drsStatus;
	}

	/**
	 * @return the allowedSeries
	 */
	public String getAllowedSeries() {
		return allowedSeries;
	}

	/**
	 * @param allowedSeries the allowedSeries to set
	 */
	public void setAllowedSeries(String allowedSeries) {
		this.allowedSeries = allowedSeries;
	}

	/**
	 * @return the isNormalCnoteAllowed
	 */
	public String getIsNormalCnoteAllowed() {
		return isNormalCnoteAllowed;
	}

	

	/**
	 * @return the flagYes
	 */
	public String getFlagYes() {
		return flagYes;
	}

	/**
	 * @return the flagNo
	 */
	public String getFlagNo() {
		return flagNo;
	}

	/**
	 * @param flagYes the flagYes to set
	 */
	public void setFlagYes(String flagYes) {
		this.flagYes = flagYes;
	}

	/**
	 * @param flagNo the flagNo to set
	 */
	public void setFlagNo(String flagNo) {
		this.flagNo = flagNo;
	}

	/**
	 * @param isNormalCnoteAllowed the isNormalCnoteAllowed to set
	 */
	public void setIsNormalCnoteAllowed(String isNormalCnoteAllowed) {
		this.isNormalCnoteAllowed = isNormalCnoteAllowed;
	}

	/**
	 * @return the consgNumLength
	 */
	public Integer getConsgNumLength() {
		return consgNumLength;
	}

	/**
	 * @return the comailLength
	 */
	public Integer getComailLength() {
		return comailLength;
	}

	/**
	 * @param consgNumLength the consgNumLength to set
	 */
	public void setConsgNumLength(Integer consgNumLength) {
		this.consgNumLength = consgNumLength;
	}

	/**
	 * @param comailLength the comailLength to set
	 */
	public void setComailLength(Integer comailLength) {
		this.comailLength = comailLength;
	}

	/**
	 * @return the rowRemarks
	 */
	public String[] getRowRemarks() {
		return rowRemarks;
	}

	/**
	 * @param rowRemarks the rowRemarks to set
	 */
	public void setRowRemarks(String[] rowRemarks) {
		this.rowRemarks = rowRemarks;
	}

	/**
	 * @return the rowAttemptNumber
	 */
	public Integer[] getRowAttemptNumber() {
		return rowAttemptNumber;
	}

	/**
	 * @param rowAttemptNumber the rowAttemptNumber to set
	 */
	public void setRowAttemptNumber(Integer[] rowAttemptNumber) {
		this.rowAttemptNumber = rowAttemptNumber;
	}

	/**
	 * @return the reasonsForMisCard
	 */
	public String getReasonsForMisCard() {
		return reasonsForMisCard;
	}

	/**
	 * @return the comailStartsWith
	 */
	public String getComailStartsWith() {
		return comailStartsWith;
	}

	/**
	 * @param comailStartsWith the comailStartsWith to set
	 */
	public void setComailStartsWith(String comailStartsWith) {
		this.comailStartsWith = comailStartsWith;
	}

	/**
	 * @param reasonsForMisCard the reasonsForMisCard to set
	 */
	public void setReasonsForMisCard(String reasonsForMisCard) {
		this.reasonsForMisCard = reasonsForMisCard;
	}

	/**
	 * @return the rowContactNumber
	 */
	public String[] getRowContactNumber() {
		return rowContactNumber;
	}

	/**
	 * @return the rowReceiverName
	 */
	public String[] getRowReceiverName() {
		return rowReceiverName;
	}

	/**
	 * @return the rowDeliveryType
	 */
	public String[] getRowDeliveryType() {
		return rowDeliveryType;
	}

	
	/**
	 * @param rowContactNumber the rowContactNumber to set
	 */
	public void setRowContactNumber(String[] rowContactNumber) {
		this.rowContactNumber = rowContactNumber;
	}

	/**
	 * @param rowReceiverName the rowReceiverName to set
	 */
	public void setRowReceiverName(String[] rowReceiverName) {
		this.rowReceiverName = rowReceiverName;
	}

	/**
	 * @param rowDeliveryType the rowDeliveryType to set
	 */
	public void setRowDeliveryType(String[] rowDeliveryType) {
		this.rowDeliveryType = rowDeliveryType;
	}

	
	/**
	 * @return the rowCompanySealSign
	 */
	public String[] getRowCompanySealSign() {
		return rowCompanySealSign;
	}

	/**
	 * @param rowCompanySealSign the rowCompanySealSign to set
	 */
	public void setRowCompanySealSign(String[] rowCompanySealSign) {
		this.rowCompanySealSign = rowCompanySealSign;
	}

	/**
	 * @return the dlvTypeOffice
	 */
	public String getDlvTypeOffice() {
		return dlvTypeOffice;
	}

	/**
	 * @return the dlvTypeNonDlv
	 */
	public String getDlvTypeNonDlv() {
		return dlvTypeNonDlv;
	}

	/**
	 * @param dlvTypeOffice the dlvTypeOffice to set
	 */
	public void setDlvTypeOffice(String dlvTypeOffice) {
		this.dlvTypeOffice = dlvTypeOffice;
	}

	/**
	 * @param dlvTypeNonDlv the dlvTypeNonDlv to set
	 */
	public void setDlvTypeNonDlv(String dlvTypeNonDlv) {
		this.dlvTypeNonDlv = dlvTypeNonDlv;
	}

	/**
	 * @return the drsStatusUpdate
	 */
	public String getDrsStatusUpdate() {
		return drsStatusUpdate;
	}

	/**
	 * @param drsStatusUpdate the drsStatusUpdate to set
	 */
	public void setDrsStatusUpdate(String drsStatusUpdate) {
		this.drsStatusUpdate = drsStatusUpdate;
	}

	/**
	 * @return the seriesC
	 */
	public String getSeriesC() {
		return seriesC;
	}

	/**
	 * @param seriesC the seriesC to set
	 */
	public void setSeriesC(String seriesC) {
		this.seriesC = seriesC;
	}

	
	
	/**
	 * @return the successMessage
	 */
	public String getSuccessMessage() {
		return successMessage;
	}

	/**
	 * @param successMessage the successMessage to set
	 */
	public void setSuccessMessage(String successMessage) {
		this.successMessage = successMessage;
	}
	
	/**
	 * @return the seriesQ
	 */
	public String getSeriesQ() {
		return seriesQ;
	}

	/**
	 * @param seriesQ the seriesQ to set
	 */
	public void setSeriesQ(String seriesQ) {
		this.seriesQ = seriesQ;
	}

	/**
	 * @return the isPricingInfoRequired
	 */
	public Boolean getIsPricingInfoRequired() {
		return isPricingInfoRequired;
	}

	/**
	 * @param isPricingInfoRequired the isPricingInfoRequired to set
	 */
	public void setIsPricingInfoRequired(Boolean isPricingInfoRequired) {
		this.isPricingInfoRequired = isPricingInfoRequired;
	}

	public String getSeriesD() {
		return seriesD;
	}

	public void setSeriesD(String seriesD) {
		this.seriesD = seriesD;
	}

	public String getSeriesL() {
		return seriesL;
	}

	public void setSeriesL(String seriesL) {
		this.seriesL = seriesL;
	}

	public String getSeriesT() {
		return seriesT;
	}

	public void setSeriesT(String seriesT) {
		this.seriesT = seriesT;
	}

	/**
	 * @return the rowNoOfPieces
	 */
	public Integer[] getRowNoOfPieces() {
		return rowNoOfPieces;
	}

	/**
	 * @param rowNoOfPieces the rowNoOfPieces to set
	 */
	public void setRowNoOfPieces(Integer[] rowNoOfPieces) {
		this.rowNoOfPieces = rowNoOfPieces;
	}

	/**
	 * @return the rowParentChildCnType
	 */
	public String[] getRowParentChildCnType() {
		return rowParentChildCnType;
	}

	/**
	 * @param rowParentChildCnType the rowParentChildCnType to set
	 */
	public void setRowParentChildCnType(String[] rowParentChildCnType) {
		this.rowParentChildCnType = rowParentChildCnType;
	}

	/**
	 * @return the currentDateStr
	 */
	public String getCurrentDateStr() {
		return currentDateStr;
	}

	/**
	 * @return the currentTimeStr
	 */
	public String getCurrentTimeStr() {
		return currentTimeStr;
	}

	/**
	 * @return the createdDateStr
	 */
	public String getCreatedDateStr() {
		return createdDateStr;
	}

	/**
	 * @return the createdTimeStr
	 */
	public String getCreatedTimeStr() {
		return createdTimeStr;
	}

	/**
	 * @return the updatedDateStr
	 */
	public String getUpdatedDateStr() {
		return updatedDateStr;
	}

	/**
	 * @return the updatedTimeStr
	 */
	public String getUpdatedTimeStr() {
		return updatedTimeStr;
	}

	/**
	 * @param currentDateStr the currentDateStr to set
	 */
	public void setCurrentDateStr(String currentDateStr) {
		this.currentDateStr = currentDateStr;
	}

	/**
	 * @param currentTimeStr the currentTimeStr to set
	 */
	public void setCurrentTimeStr(String currentTimeStr) {
		this.currentTimeStr = currentTimeStr;
	}

	/**
	 * @param createdDateStr the createdDateStr to set
	 */
	public void setCreatedDateStr(String createdDateStr) {
		this.createdDateStr = createdDateStr;
	}

	/**
	 * @param createdTimeStr the createdTimeStr to set
	 */
	public void setCreatedTimeStr(String createdTimeStr) {
		this.createdTimeStr = createdTimeStr;
	}

	/**
	 * @param updatedDateStr the updatedDateStr to set
	 */
	public void setUpdatedDateStr(String updatedDateStr) {
		this.updatedDateStr = updatedDateStr;
	}

	/**
	 * @param updatedTimeStr the updatedTimeStr to set
	 */
	public void setUpdatedTimeStr(String updatedTimeStr) {
		this.updatedTimeStr = updatedTimeStr;
	}

	/**
	 * @return the rowRelationId
	 */
	public Integer[] getRowRelationId() {
		return rowRelationId;
	}

	/**
	 * @param rowRelationId the rowRelationId to set
	 */
	public void setRowRelationId(Integer[] rowRelationId) {
		this.rowRelationId = rowRelationId;
	}

	/**
	 * @return the maxAllowedRows
	 */
	public Integer getMaxAllowedRows() {
		return maxAllowedRows;
	}

	/**
	 * @return the maxAllowedPrintRows
	 */
	public Integer getMaxAllowedPrintRows() {
		return maxAllowedPrintRows;
	}

	/**
	 * @param maxAllowedRows the maxAllowedRows to set
	 */
	public void setMaxAllowedRows(Integer maxAllowedRows) {
		this.maxAllowedRows = maxAllowedRows;
	}

	/**
	 * @param maxAllowedPrintRows the maxAllowedPrintRows to set
	 */
	public void setMaxAllowedPrintRows(Integer maxAllowedPrintRows) {
		this.maxAllowedPrintRows = maxAllowedPrintRows;
	}

	/**
	 * @return the companySealAndSign
	 */
	public String getCompanySealAndSign() {
		return companySealAndSign;
	}

	/**
	 * @param companySealAndSign the companySealAndSign to set
	 */
	public void setCompanySealAndSign(String companySealAndSign) {
		this.companySealAndSign = companySealAndSign;
	}

	/**
	 * @return the drsStatusClosed
	 */
	public String getDrsStatusClosed() {
		return drsStatusClosed;
	}

	/**
	 * @param drsStatusClosed the drsStatusClosed to set
	 */
	public void setDrsStatusClosed(String drsStatusClosed) {
		this.drsStatusClosed = drsStatusClosed;
	}

	/**
	 * @return the pendingStatus
	 */
	public String getPendingStatus() {
		return pendingStatus;
	}

	/**
	 * @return the deliveredStatus
	 */
	public String getDeliveredStatus() {
		return deliveredStatus;
	}

	/**
	 * @param pendingStatus the pendingStatus to set
	 */
	public void setPendingStatus(String pendingStatus) {
		this.pendingStatus = pendingStatus;
	}

	/**
	 * @param deliveredStatus the deliveredStatus to set
	 */
	public void setDeliveredStatus(String deliveredStatus) {
		this.deliveredStatus = deliveredStatus;
	}

	/**
	 * @return the manifestDrsType
	 */
	public String getManifestDrsType() {
		return manifestDrsType;
	}

	/**
	 * @return the fsOutTimeDateStr
	 */
	public String getFsOutTimeDateStr() {
		return fsOutTimeDateStr;
	}

	

	/**
	 * @param fsOutTimeDateStr the fsOutTimeDateStr to set
	 */
	public void setFsOutTimeDateStr(String fsOutTimeDateStr) {
		this.fsOutTimeDateStr = fsOutTimeDateStr;
	}

	

	/**
	 * @param manifestDrsType the manifestDrsType to set
	 */
	public void setManifestDrsType(String manifestDrsType) {
		this.manifestDrsType = manifestDrsType;
	}



	/**
	 * @return the fsOutTimeMMStr
	 */
	public String getFsOutTimeMMStr() {
		return fsOutTimeMMStr;
	}



	/**
	 * @param fsOutTimeMMStr the fsOutTimeMMStr to set
	 */
	public void setFsOutTimeMMStr(String fsOutTimeMMStr) {
		this.fsOutTimeMMStr = fsOutTimeMMStr;
	}



	/**
	 * @return the fsOutTimeHHStr
	 */
	public String getFsOutTimeHHStr() {
		return fsOutTimeHHStr;
	}



	/**
	 * @param fsOutTimeHHStr the fsOutTimeHHStr to set
	 */
	public void setFsOutTimeHHStr(String fsOutTimeHHStr) {
		this.fsOutTimeHHStr = fsOutTimeHHStr;
	}



	/**
	 * @return the fsInTimeMMStr
	 */
	public String getFsInTimeMMStr() {
		return fsInTimeMMStr;
	}



	/**
	 * @param fsInTimeMMStr the fsInTimeMMStr to set
	 */
	public void setFsInTimeMMStr(String fsInTimeMMStr) {
		this.fsInTimeMMStr = fsInTimeMMStr;
	}



	/**
	 * @return the fsInTimeHHStr
	 */
	public String getFsInTimeHHStr() {
		return fsInTimeHHStr;
	}



	/**
	 * @param fsInTimeHHStr the fsInTimeHHStr to set
	 */
	public void setFsInTimeHHStr(String fsInTimeHHStr) {
		this.fsInTimeHHStr = fsInTimeHHStr;
	}



	/**
	 * @return the rowDeliveryTimeInHH
	 */
	public String[] getRowDeliveryTimeInHH() {
		return rowDeliveryTimeInHH;
	}



	/**
	 * @param rowDeliveryTimeInHH the rowDeliveryTimeInHH to set
	 */
	public void setRowDeliveryTimeInHH(String[] rowDeliveryTimeInHH) {
		this.rowDeliveryTimeInHH = rowDeliveryTimeInHH;
	}



	/**
	 * @return the rowDeliveryTimeInMM
	 */
	public String[] getRowDeliveryTimeInMM() {
		return rowDeliveryTimeInMM;
	}



	/**
	 * @param rowDeliveryTimeInMM the rowDeliveryTimeInMM to set
	 */
	public void setRowDeliveryTimeInMM(String[] rowDeliveryTimeInMM) {
		this.rowDeliveryTimeInMM = rowDeliveryTimeInMM;
	}



	public String[] getRowDeliveryStatus() {
		return rowDeliveryStatus;
	}



	public void setRowDeliveryStatus(String[] rowDeliveryStatus) {
		this.rowDeliveryStatus = rowDeliveryStatus;
	}



	/**
	 * @return the autoGeneratedManualDrsNumber
	 */
	public String getAutoGeneratedManualDrsNumber() {
		return autoGeneratedManualDrsNumber;
	}



	/**
	 * @param autoGeneratedManualDrsNumber the autoGeneratedManualDrsNumber to set
	 */
	public void setAutoGeneratedManualDrsNumber(String autoGeneratedManualDrsNumber) {
		this.autoGeneratedManualDrsNumber = autoGeneratedManualDrsNumber;
	}






	/**
	 * @return the processCode
	 */
	public String getProcessCode() {
		return processCode;
	}



	/**
	 * @param processCode the processCode to set
	 */
	public void setProcessCode(String processCode) {
		this.processCode = processCode;
	}



	/**
	 * @return the manifestDirection
	 */
	public String getManifestDirection() {
		return manifestDirection;
	}



	/**
	 * @param manifestDirection the manifestDirection to set
	 */
	public void setManifestDirection(String manifestDirection) {
		this.manifestDirection = manifestDirection;
	}



	/**
	 * @return the queryName
	 */
	public String getQueryName() {
		return queryName;
	}



	/**
	 * @param queryName the queryName to set
	 */
	public void setQueryName(String queryName) {
		this.queryName = queryName;
	}



	/**
	 * @return the loggedInOfficeType
	 */
	public String getLoggedInOfficeType() {
		return loggedInOfficeType;
	}



	/**
	 * @param loggedInOfficeType the loggedInOfficeType to set
	 */
	public void setLoggedInOfficeType(String loggedInOfficeType) {
		this.loggedInOfficeType = loggedInOfficeType;
	}



}
