/**
 * 
 */
package com.ff.web.drs.manualdrs.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.capgemini.lbs.framework.constants.FrameworkConstants;
import com.capgemini.lbs.framework.exception.CGBusinessException;
import com.capgemini.lbs.framework.exception.CGSystemException;
import com.capgemini.lbs.framework.utils.CGJasonConverter;
import com.capgemini.lbs.framework.utils.ExceptionUtil;
import com.capgemini.lbs.framework.utils.StringUtil;
import com.ff.to.drs.AbstractDeliveryTO;
import com.ff.to.drs.pending.PendingDrsHeaderTO;
import com.ff.universe.drs.constant.UniversalDeliveryContants;
import com.ff.web.drs.common.action.AbstractDeliveryAction;
import com.ff.web.drs.common.constants.DrsCommonConstants;
import com.ff.web.drs.common.constants.DrsConstants;
import com.ff.web.drs.updation.form.PendingDrsForm;
import com.ff.web.util.UdaanWebErrorConstants;

/**
 * @author mohammes
 *
 */
public class PendingManualDrsAction extends AbstractDeliveryAction {
	/** The Constant LOGGER. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(PendingManualDrsAction.class);
	
	
	
	/**
	 * Name : viewPendingDrsPage
	 * purpose : to view Update DRS for Pending consignments for Manual/Third Party manifest
	 * Input :
	 * return : populate form with default values.
	 *
	 * @param mapping the mapping
	 * @param form the form
	 * @param request the request
	 * @param response the response
	 * @return the action forward
	 */
	public ActionForward viewPendingDrsPage(final ActionMapping mapping, final ActionForm form,
			final HttpServletRequest request, final HttpServletResponse response) {
		LOGGER.debug("PendingManualDrsAction::viewPendingDrsPage ..START");
		final PendingDrsHeaderTO drsTo = new PendingDrsHeaderTO();
		initilaizeForm(drsTo,request);
		setGlobalDetails(request, (AbstractDeliveryTO)drsTo);
		setAutoGeneratedMDrsNumber(drsTo, request);
		((PendingDrsForm) form).setTo(drsTo);
		LOGGER.debug("PendingManualDrsAction::viewPendingDrsPage ..END");
		return mapping.findForward(DrsConstants.SUCCESS_FORWARD);
	}
	
	/**
	 * @param drsTo
	 * @throws CGBusinessException 
	 */
	private void initilaizeForm(final PendingDrsHeaderTO drsTo,final HttpServletRequest request){
		drsTo.setDrsScreenCode(DrsConstants.MANUAL_PENDING_DRS_SCREEN_CODE);
		drsTo.setReasonsForMisCard(getConfigParamValue(request, UniversalDeliveryContants.DRS_MISSED_CARD_REASON));
		drsTo.setDrsType(DrsConstants.DRS_TYPE_UPDATE);
		drsTo.setAllowedSeries(getConfigParamValue(request, UniversalDeliveryContants.MANUAL_DRS_CONFIG_PARAMS_SERIES));
		drsTo.setIsNormalCnoteAllowed(DrsConstants.FLAG_YES);
		setHeaderStandardTypeDetails(request);
		manualDrsDropDown(request);
		prepareConsignmentTypeDetails(request);
		if(drsTo!=null && (StringUtil.isStringEmpty(drsTo.getDrsStatus()) ||(!StringUtil.isStringEmpty(drsTo.getDrsStatus()) && !drsTo.getDrsStatus().equalsIgnoreCase(DrsConstants.DRS_STATUS_CLOSED)))){
			request.setAttribute(DrsConstants.DRS_CLOSE_IS_REQUIRED, DrsConstants.FLAG_YES);
		}
		
	}
	
	public ActionForward searchPendingConsignments(final ActionMapping mapping, final ActionForm form,
			final HttpServletRequest request, final HttpServletResponse response) {
		LOGGER.debug("PendingManualDrsAction::searchPendingConsignments ..START");

		PendingDrsForm drsForm = (PendingDrsForm)form;
		PendingDrsHeaderTO drsTo =(PendingDrsHeaderTO) drsForm.getTo();
		manualDrsService = getManualDrsService();
		final String drsNumber=request.getParameter(DrsCommonConstants.REQ_PARAM_DRS_NUMEBR);
		if(!StringUtil.isStringEmpty(drsNumber)){
			setGlobalDetails(request, (AbstractDeliveryTO)drsTo);
			drsTo.setDrsNumber(drsNumber);
		}
		try {
			manualDrsService.searchPendingConsignments(drsTo);
			//check any warnings/Business Exceptions
			final boolean errorStatus = ExceptionUtil.checkError(drsTo);
			if(errorStatus) {
				//if so extract them and propagate to screen
				ExceptionUtil.prepareActionMessage(drsTo, request);
				saveActionMessage(request);
			}

		} catch (CGBusinessException e) {
			LOGGER.error("PendingManualDrsAction::searchPendingConsignments ..CGBusinessException :",e);
			drsTo= new PendingDrsHeaderTO();
			getBusinessError(request, e);
		} catch (CGSystemException e) {
			LOGGER.error("PendingManualDrsAction::searchPendingConsignments ..CGSystemException :",e);
			drsTo= new PendingDrsHeaderTO();
			getSystemException(request, e);
		}catch (Exception e) {
			drsTo = new PendingDrsHeaderTO();
			LOGGER.error("PendingManualDrsAction::searchPendingConsignments ..Exception :",e);
			getGenericException(request, e);
		}finally{
			initilaizeForm(drsTo, request);
			setGlobalDetails(request, (AbstractDeliveryTO)drsTo);
			setHeaderStandardTypeDetails(request);
		}
		((PendingDrsForm) form).setTo(drsTo);
		LOGGER.debug("PendingManualDrsAction::searchPendingConsignments ..END");
		return mapping.findForward(DrsConstants.SUCCESS_FORWARD);
	}
	
	/**
	 * Save undelivered drs.
	 *
	 * @param mapping the mapping
	 * @param form the form
	 * @param request the request
	 * @param response the response
	 */
	public void saveUndeliveredDrs(final ActionMapping mapping, final ActionForm form,
			final HttpServletRequest request, final HttpServletResponse response) {
		LOGGER.debug("PendingManualDrsAction::updateUndeliveredDrs ..START");
		Boolean result=Boolean.FALSE;

		final PendingDrsForm drsForm = (PendingDrsForm)form;
		final PendingDrsHeaderTO drsTo =(PendingDrsHeaderTO) drsForm.getTo();

		String jsonResult=FrameworkConstants.EMPTY_STRING;
		java.io.PrintWriter out=null;
		try {
			serializer = CGJasonConverter.getJsonObject();
			out=response.getWriter();
			response.setContentType(FrameworkConstants.MIME_TYPE_TEXT_JAVA_SCRIPT);
			manualDrsService = getManualDrsService();
			result = manualDrsService.saveUndeliveredDrsConsg(drsTo);
			if(!result){
				jsonResult = getMessageFromErrorBundle(request,UdaanWebErrorConstants.DRS_NOT_MODIFIED,new String[]{drsTo.getDrsNumber()});
			}else{
				performTwoWayWrite(drsTo);
				drsTo.setSuccessMessage(getMessageFromErrorBundle(request,UdaanWebErrorConstants.DRS_INFO_SAVED,new String[]{drsTo.getDrsNumber(),StringUtil.isEmptyLong(drsTo.getDeliveryId())?"Saved":StringUtil.convertInitialLetterCap(drsTo.getDrsStatus())}));
				jsonResult = serializer.toJSON(drsTo).toString();
			}

		} catch (CGBusinessException e) {
			LOGGER.error("PendingManualDrsAction::saveUndeliveredDrs ..CGBusinessException :",e);
			jsonResult = prepareCommonException(DrsConstants.ERROR_FLAG,getBusinessErrorFromWrapper(request,e));
		}catch (CGSystemException e) {
			LOGGER.error("PendingManualDrsAction::saveUndeliveredDrs ..CGSystemException :",e);
			jsonResult= prepareCommonException(DrsConstants.ERROR_FLAG,getSystemExceptionMessage(request,e));
		}catch (Exception e) {
			LOGGER.error("PendingManualDrsAction::saveUndeliveredDrs ..Exception :",e);
			jsonResult = prepareCommonException(DrsConstants.ERROR_FLAG,getGenericExceptionMessage(request, e));
		}
		finally {
			out.print(jsonResult);
			out.flush();
			out.close();
		}
		LOGGER.debug("PendingManualDrsAction::saveUndeliveredDrs ..END");
	}

}
