/**
 * 
 */
package com.ff.web.util;

/**
 * @author uchauhan
 *
 */
public interface UdaanWebErrorConstants {

	
	String PICKUP_INVALID_DATA = "E0001";
	
	String PICK_UP_RUN_SHEET_UPDATED="P000";
	String PICK_UP_RUN_SHEET_DOES_NOT_EXIST="P001";
	String RUN_SHEET_NOT_GENERATED_FOR_EMP="P002";
	String OFFICE_NOT_HUB="P003";
	String ISSUE_WITH_ORDER_NUMBER_GENERATION="PU0011";
	String CUSTOMER_NOT_CONTRACT_PRODUCT="PU0014";
			
	String DRS_DTLS_NOT_EXIST="DRS001";
	String DRS_PROBLEM_NUMBER_GENERATION ="DRS002";
	String DRS_PREPARED_ALREADY_FOR_CONSG ="DRS003";
	String DRS_INVALID_CONSG_NUMBER ="DRS004";
	String DRS_NOT_MANIFESTED ="DRS005";
	String DRS_NOT_INVALID_CONSG_TYPE ="DRS006";
	String DRS_CONSG_DELIVERED ="DRS007";
	String YP_DRS_IN_VALID_CONSG ="DRS008";
	String DRS_INVALID_USER ="DRS009";
	String DRS_ALREADY_UPDATED ="DRS010";
	String DRS_NO_GENERATED_HERE ="DRS011";
	String DRS_NO_ALREADY_DICARDED ="DRS012";
	
	/** The drs no dicarded. */
	String DRS_NO_DICARDED ="DRS013";
	
	/** The drs info not saved. */
	String DRS_INFO_NOT_SAVED ="DRS014";
	
	/** The drs info saved. expects two place holders number, transaction type (saved,prepared,etc)*/
	String DRS_INFO_SAVED ="DRS015";
	
	/** The drs not modified. */
	String DRS_NOT_MODIFIED = "DRS016";
	
	/** The list drs search msg. */
	String LIST_DRS_SEARCH_MSG = "DRS017";
	
	/** The drs invalid search results. */
	String DRS_INVALID_SEARCH_RESULTS = "DRS018";
	
	/** The drs does not exist. */
	String DRS_DOES_NOT_EXIST = "DRS019";
	
	/** The drs no not belong to consg. */
	String DRS_NO_NOT_BELONG_TO_CONSG = "DRS020";
	
	/** The drs consg already updated. */
	String DRS_CONSG_ALREADY_UPDATED = "DRS021";
	String DRS_PARENT_CONSG_NUMBER = "DRS022";
	String DRS_DTLS_NOT_EXIST_FOR = "DRS023";
	
	/** The drs can not prep for pending cn. */
	String DRS_CAN_NOT_PREP_FOR_PENDING_CN = "DRS024";
	
	String DRS_CAN_NOT_PREP_FOR_OLD_CN = "DRS025";
	String DRS_CAN_NOT_PREP_FOR_NEW_CN_YP = "DRS026";
	String DRS_CAN_NOT_INCLUDE_IN_TODAYS_DRS = "DRS027";
	String DRS_CONSG_NOT_RTOED = "DRS028";
	String DRS_RTO_COD_PENDING_SCREEN = "DRS029";	
	String DRS_NOT_FOUND="DRS030";
	
	String DRS_NOT_FOUND_REASON="DRS031";
	String DRS_NOT_DISCARDED="DRS032";
	String DRS_NOT_DISCARDED_DB_ISSUE="DRS033";
	String DRS_CAN_NOT_EMPTY="DRS034";
	String DRS_NOT_MANIFESTED_IN_OFFICE = "DRS035";
	String ERROR_IN_PRINTING_DRS="DRS045";
	String DRS_TMF_NOT_EXIST="DRS037";
	String DRS_PENDING_DONE_TMF="DRS038";
	String DRS_PENDING_DONE_MDRS="DRS039";
	String DRS_NUMBER_ALREADY_IN_USE="DRS040";
	String DRS_NUMBER_NOT_EMPTY="DRS041";
	String DRS_MANIFEST_DRS_TYPE_INVALID="DRS042";
	String DRS_MANIFEST_DRS_NUMBER_NOT_PREP_HERE="DRS043";
	String DRS_CONSG_RTOED = "DRS044";
	String DRS_ALREADY_IN_MANIFESTED = "DRS045";
	String DRS_MANIFEST_NOT_CLOSED="DRS046";
	String CONSG_NO_NOT_UNDER_MANIFEST="DRS047";
	String DRS_NO_PENDING_CN_EXIST="DRS048";
	String DRS_NO_DRS_CREATED_FOR_FS="DRS049";
	String RTOED_CN_NOT_ALLOWED_IN_DRS="DRS050";
	String DRS_MNFSTD_CITY_NOT_MATCHING_WITH_LOGIN_CITY="DRS051";
	String DRS_BLK_SCRN_NOT_ACCESS="DRS052";
	String CN_HAVE_UPDATED_IN_DRS="DRS053";
	
	
	
	
	
	
	
	
	
	//Common Error Codes
	String DETAILS_NOT_EXIST_FOR_DB_ISSUE  ="E0004";
	String DETAILS_NOT_EXIST  ="E0005";
	String NO_OFFICE_FOUND ="E0006";
	
	String DETAILS_NOT_SAVED_INVALID_DATA="I0002";	
	String NO_EMPLOYEES_FOUND="ERRORMN004";
	String NO_OFFICES_FOUND="ERRORMN002";
	String ERROR_PAGE_LOAD="ERRORGL002";
	
	String CN_STOP_DELIVERY="CN0001";
	
	//Cod Receipt 
	String NO_CN_DETAILS_FOUND="COD001";
	String NO_BOOKING_DETAILS_FOUND="COD002";

	String JOB_DB_ISSUE="JOB001";
	String DETAILS_NOT_FOUND_DB_ISSUE = "JOB002";
	String JOB_PROCESS_DATA ="JOB003";
}
