package com.ff.rate.calculation.constants;

public interface RateCalculationConstants {
	String RATE_COMPONENT_TYPE_COD="CODCG";
	String RATE_COMPONENT_TYPE_OCTROI="OCTRI";
	String RATE_COMPONENT_TYPE_FUEL_SURCHARGE="FSCHG";
	//String RATE_COMPONENT_TYPE_COD="";
	
	String RATE_COMPONENT_OPERATION_ADD="A";
	String RATE_COMPONENT_OPERATION_SUB="S";
	String RATE_COMPONENT_OPERATION_MUL="M";
	String RATE_COMPONENT_OPERATION_DIV="D";
	String RATE_COMPONENT_OPERATION_PPERCENTILE_AND_SUBTRACT = "PS";
	String RATE_COMPONENT_OPERATION_PERCENTILE = "P";
	String RATE_COMPONENT_OPERATION_PA = "PA";
	int RATE_COMPONENT_SEQ_SlAB_RATE = 2;
	int RATE_COMPONENT_SEQ_DECLAIRED_VALUE = 1;
	int RATE_COMPONENT_SEQ_TOTAL_WTOUT_TAX = 14;
	int RATE_COMPONENT_SEQ_GRAND_TOTAL = 25;
	String INTRA_CITY = "Intra city ";
	Integer RATE_CASH_CUSTOMER_CATEGORY_ID = 2;
	String NO = "N";
	String YES = "Y";
	String PRIORITY_PRODUCT_CODE = "PC000005";
	String EB_PRODUCT_CODE = "PC000001";
	String T_SERIES_PRODUCT_CODE = "PC000003";
	String ZONE_NAMES ="NORTH,EAST,WEST,SOUTH,NORTH EAST";
	String TRAIN_CARGO_RATE_PRODUCT_CODE = "TR";
}
