
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.hr.csdtosap.emppickupdelivery;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-04-17T16:36:50.480+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_EmpPickUpDelivery_OutService",
                      portName = "SI_CSD_EmpPickUpDelivery_OutPort",
                      targetNamespace = "http://FirstFlight.com/HR/CSDToSAP/EmpPickUpDelivery",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FHR%2FCSDToSAP%2FEmpPickUpDelivery%5ESI_CSD_EmpPickUpDelivery_Out&QualityOfService=ExactlyOnce&sap-user=cg-csd&sap-password=interface",
                      endpointInterface = "com.firstflight.hr.csdtosap.emppickupdelivery.SICSDEmpPickUpDeliveryOut")
                      
public class SICSDEmpPickUpDeliveryOutImpl implements SICSDEmpPickUpDeliveryOut {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDEmpPickUpDeliveryOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.hr.csdtosap.emppickupdelivery.SICSDEmpPickUpDeliveryOut#siCSDEmpPickUpDeliveryOut(com.firstflight.hr.csdtosap.emppickupdelivery.DTCSDEmpPickUpDelivery  mtCSDEmpPickUpDelivery )*
     */
    public void siCSDEmpPickUpDeliveryOut(DTCSDEmpPickUpDelivery mtCSDEmpPickUpDelivery) { 
    	LOGGER.info("Executing operation siCSDEmpPickUpDeliveryOut");
        LOGGER.debug("mtCSDEmpPickUpDelivery::"+mtCSDEmpPickUpDelivery);
        try {
        } catch (java.lang.Exception ex) {
        	LOGGER.error("SICSDEmpPickUpDeliveryOutImpl::siCSDEmpPickUpDeliveryOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
