DROP PROCEDURE IF EXISTS sp_consignment_bulk_tracking;
CREATE PROCEDURE sp_consignment_bulk_tracking(IN  trackType varchar(10), consignments varchar(30000))
BEGIN
   SET @query = CONCAT('SELECT '
   'CASE '
    'WHEN (ffc.CONSG_STATUS = ''R'' OR '
          'ffc.CONSG_STATUS = ''S'') '
    'THEN '
      'concat( '
        'ffc.CONSG_NO '
       ',''*'') '
    'ELSE '
      'ffc.CONSG_NO '
  'END '
    'AS CONSG_NO'
 ' ,IFNULL( '
    'ffb.CUST_REF_NO '
   ',ffc.REF_NO) '
    'AS REF_NO' 
 ' ,IFNULL( '
    'ffb.BOOKING_DATE '
   ',ffc.CREATED_DATE) '
    'AS BOOKING_DATE' 
 ' ,CASE '
    'WHEN fdc_book.CITY_ID IS NOT NULL '
    'THEN '
      'concat( '
        'fdc_book.CITY_CODE '
       ','' - '' '
       ',fdc_book.CITY_NAME) '
    'ELSE '
      'concat( '
        'fdc_cn.CITY_CODE '
       ','' - '' '
       ',fdc_cn.CITY_NAME) '
  'END '
    'AS ORIGIN_CITY' 
 ' ,CASE '
    'WHEN fdc_dest_book.CITY_ID IS NOT NULL '
    'THEN '
      'concat( '
        'fdc_dest_book.CITY_CODE '
       ','' - '' '
       ',fdc_dest_book.CITY_NAME) '
    'ELSE '
      'concat( '
        'fdc_dest_cn.CITY_CODE '
       ','' - '' '
       ',fdc_dest_cn.CITY_NAME) '
  'END '
    'AS DEST_CITY' 
 ' ,CASE '
    'WHEN (ffc.CONSG_STATUS = ''R'' AND '
          'ffdd1.DELIVERY_STATUS = ''O'') '
    'THEN '
     '''RTO'''
    'WHEN (ffc.CONSG_STATUS = ''R'' AND '
          'ffdd1.DELIVERY_STATUS = ''P'') '
    'THEN '
      '''RTO Delivery Pending'' '
    'WHEN (ffc.CONSG_STATUS = ''S'') '
    'THEN '
      '''RTO Delivered'' '
    'WHEN ffdd1.DELIVERY_STATUS IS NULL '
    'THEN '
      '''In Transit'' '
    'WHEN ffdd1.DELIVERY_STATUS = ''D'' '
    'THEN '
      '''Delivered'' '
    'WHEN ffdd1.DELIVERY_STATUS = ''P'' '
    'THEN '
      '''Pending'' '
    'WHEN ffdd1.DELIVERY_STATUS = ''O'' '
    'THEN '
      '''Out For Delivery'' '
  'END '
    'AS CN_STATUS' 
 ' ,fdr.REASON_NAME AS PENDING_REASON' 
 ' ,IFNULL( '
    'ffdd1.DELIVERY_TIME '
   ',ffd.DRS_DATE) '
    'AS DELIVERY_DATE'
 ' ,IF( '
    'ffdd1.DELIVERY_TYPE = ''O'' '
   ',''( Office Seal & Sign )'' '
  ',ffdd1.RECEIVER_NAME) '
    'AS RECEIVER_NAME'
    ' ,IFNULL( '
    'ffb.FINAL_WEIGHT '
   ',ffc.FINAL_WEIGHT) '
    'AS CN_WEIGHT' 
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' THEN ffm_pkt1.MANIFEST_NO '
    'ELSE NULL '
  'END '
    'AS OGM_NO'
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' THEN ffm_pkt1.MANIFEST_DATE '
    'ELSE NULL '
  'END '
    'AS OGM_DATE'
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' THEN ffm_bag_dox.MANIFEST_NO '
    'ELSE ffm_bag_ppx1.MANIFEST_NO '
  'END '
    'AS BPL_NO'
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' THEN ffm_bag_dox.MANIFEST_DATE '
    'ELSE ffm_bag_ppx1.MANIFEST_DATE '
  'END '
    'AS BPL_DATE'
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' '
    'THEN '
      'CASE '
        'WHEN fflm_bag_dox.GATE_PASS_NUMBER IS NOT NULL '
        'THEN '
          'fflm_bag_dox.GATE_PASS_NUMBER '
        'ELSE '
          'fflm_mbag.GATE_PASS_NUMBER '
      'END '
    'WHEN fdct.CONSIGNMENT_CODE = ''PPX'' '
    'THEN '
      'CASE '
        'WHEN fflm_bag_ppx.GATE_PASS_NUMBER IS NOT NULL '
        'THEN '
          'fflm_bag_ppx.GATE_PASS_NUMBER '
        'ELSE '
          'fflm_mbag.GATE_PASS_NUMBER '
      'END '
    'ELSE '
      'NULL '
  'END '
    'AS CD_NO' 
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' '
    'THEN '
      'CASE '
        'WHEN fflm_bag_dox.GATE_PASS_NUMBER IS NOT NULL '
        'THEN '
          'fflm_bag_dox.LOADING_DATE '
        'ELSE '
          'fflm_mbag.LOADING_DATE '
      'END '
    'WHEN fdct.CONSIGNMENT_CODE = ''PPX'' '
    'THEN '
      'CASE '
        'WHEN fflm_bag_ppx.GATE_PASS_NUMBER IS NOT NULL '
        'THEN '
          'fflm_bag_ppx.LOADING_DATE '
        'ELSE '
          'fflm_mbag.LOADING_DATE '
      'END '
    'ELSE '
      'NULL '
  'END '
    'AS CD_DATE' 
 ' ,CASE '
    'WHEN fdt.TRAIN_NUMBER IS NOT NULL '
    'THEN '
      'fdt.TRAIN_NUMBER '
    'WHEN fdv1.REG_NUMBER IS NOT NULL '
    'THEN '
      'fdv1.REG_NUMBER '
    'WHEN fflm_mbag.VEHICLE_REG_NUMBER IS NOT NULL OR '
         'fflm_bag_dox.VEHICLE_REG_NUMBER IS NOT NULL OR '
         'fflm_bag_ppx.VEHICLE_REG_NUMBER IS NOT NULL '
    'THEN '
      'CASE '
        'WHEN ffm_mbag.MANIFEST_ID IS NOT NULL '
        'THEN '
          'fflm_mbag.VEHICLE_REG_NUMBER '
        'WHEN ffm_mbag.MANIFEST_ID IS NULL AND '
             'fdct.CONSIGNMENT_CODE = ''DOX'' '
        'THEN '
          'fflm_bag_dox.VEHICLE_REG_NUMBER '
        'WHEN ffm_mbag.MANIFEST_ID IS NULL AND '
             'fdct.CONSIGNMENT_CODE = ''PPX'' '
        'THEN '
          'fflm_bag_ppx.VEHICLE_REG_NUMBER '
      'END '
    'WHEN fdv.REG_NUMBER IS NOT NULL '
    'THEN '
      'fdv.REG_NUMBER '
    'WHEN fflc_mbag.RECV_TRANSPORT_NUMBER IS NOT NULL OR '
         'fflc_bag_dox.RECV_TRANSPORT_NUMBER IS NOT NULL OR '
         'fflc_bag_ppx.RECV_TRANSPORT_NUMBER IS NOT NULL '
    'THEN '
      'CASE '
        'WHEN ffm_mbag.MANIFEST_ID IS NOT NULL '
        'THEN '
          'fflc_mbag.RECV_TRANSPORT_NUMBER '
        'WHEN ffm_mbag.MANIFEST_ID IS NULL AND '
             'fdct.CONSIGNMENT_CODE = ''DOX'' '
        'THEN '
          'fflc_bag_dox.RECV_TRANSPORT_NUMBER '
        'WHEN ffm_mbag.MANIFEST_ID IS NULL AND '
             'fdct.CONSIGNMENT_CODE = ''PPX'' '
        'THEN '
          'fflc_bag_ppx.RECV_TRANSPORT_NUMBER '
      'END '
  'END '
    'AS FLIGHT_NO' 
    ' ,fft.DEPARTURE_TIME AS FLIGHT_DEP'
 ' ,IF( '
    'fflm_rec.RECEIVE_TYPE = ''O'' '
   ',fft_rec.ARRIVAL_TIME '
   ',fflm_rec.RECEIVED_AT_TIME) '
    'AS FLIGHT_ARR'
 ' ,CASE '
    'WHEN fflm_rec.LOADING_DATE IS NULL '
    'THEN '
      'ffm_in.MANIFEST_DATE '
    'ELSE '
      'IF( '
        'fflm_rec.RECEIVE_TYPE = ''O'' '
       ',CONCAT( '
          'DATE_FORMAT( '
            'fflm_rec.LOADING_DATE '
           ',''%m-%d-%Y'') '
         ','' '' '
         ',fft_rec.ARRIVAL_TIME) '
       ',CONCAT( '
          'DATE_FORMAT( '
            'fflm_rec.LOADING_DATE '
           ',''%m-%d-%Y'') '
         ','' '' '
         ',fflm_rec.RECEIVED_AT_TIME)) '
  'END '
    'AS RCV_DATE'
 ' ,date_format( '
    'ffm_in.MANIFEST_DATE '
   ',''%m-%d-%Y %H:%i:%S'') '
    'AS IN_MNFST_DATE'
' FROM '
  'ff_f_booking ffb   '
  'LEFT JOIN ff_f_consignment ffc ON ffc.CONSG_NO = ffb.CONSG_NUMBER '
  'LEFT JOIN ff_d_consignment_type fdct ON fdct.CONSIGNMENT_TYPE_ID = ffc.CONSG_TYPE '
--   ff_f_consignment ffc
--   JOIN ff_d_consignment_type fdct ON fdct.CONSIGNMENT_TYPE_ID = ffc.CONSG_TYPE 
--   LEFT JOIN ff_f_booking ffb ON ffb.CONSG_NUMBER = ffc.CONSG_NO 
  'LEFT JOIN ff_d_office fdo_book ON fdo_book.OFFICE_ID = ffb.BOOKING_OFF '
  'LEFT JOIN ff_d_city fdc_book ON fdc_book.CITY_ID = fdo_book.CITY_ID '
  'LEFT JOIN ff_d_office fdo_cn ON fdo_cn.office_id = ffc.ORG_OFF '
  'LEFT JOIN ff_d_city fdc_cn ON fdc_cn.CITY_ID = fdo_cn.CITY_ID '
  'LEFT JOIN ff_d_pincode fdpin_book ON fdpin_book.pincode_id = ffb.DEST_PINCODE '
  'LEFT JOIN ff_d_pincode fdpin_cn ON fdpin_cn.PINCODE_ID = ffc.DEST_PINCODE '
  'LEFT JOIN ff_d_city fdc_dest_book '
    'ON fdc_dest_book.CITY_ID = fdpin_book.CITY_ID '
  'LEFT JOIN ff_d_city fdc_dest_cn ON fdc_dest_cn.CITY_ID = fdpin_cn.CITY_ID '
  'LEFT JOIN ff_d_office fdo_book_hub '
    'ON fdo_book_hub.office_id = fdo_book.REPORTING_HUB '
  'LEFT JOIN ff_f_consignment_manifested ffcm '
    'ON ffcm.CONSIGNMENT_ID = ffc.CONSG_ID '
  /* last OGM prepared Packet at origin against the Consignment number of DOX */ 
  'LEFT JOIN ff_f_manifest ffm_pkt1 '
    'ON (ffm_pkt1.MANIFEST_ID = ffcm.MANIFEST_ID AND '
        'ffm_pkt1.MANIFEST_LOAD_CONTENT = fdct.CONSIGNMENT_TYPE_ID AND '
        'ffm_pkt1.MANIFEST_TYPE = ''O'') '
  'LEFT JOIN '
  '(SELECT '
     'ffcm2.consignment_id '
    ',ffm2.MANIFEST_DATE '
    ',ffm2.MANIFEST_ID '
    ',ffm2.MANIFEST_NO '
    ',ffm2.MANIFEST_TYPE '
   'FROM '
     'ff_f_consignment_manifested ffcm2 '
     'LEFT JOIN ff_f_manifest ffm2 ON ffm2.manifest_id = ffcm2.manifest_id) '
  'AS ffm_pkt2 '
    'ON (ffcm.consignment_id = ffm_pkt2.consignment_id AND '
        'ffm_pkt2.MANIFEST_TYPE = ffm_pkt1.MANIFEST_TYPE AND '
        '(ffm_pkt1.MANIFEST_DATE < ffm_pkt2.MANIFEST_DATE OR '
         '(ffm_pkt1.MANIFEST_DATE = ffm_pkt2.MANIFEST_DATE AND '
          'ffm_pkt1.MANIFEST_ID < ffm_pkt2.MANIFEST_ID))) '
  /* last OGM prepared Bag at origin against the Consignment number of DOX 
     for above packet */ 
  'LEFT JOIN ff_f_manifest ffm_bag_dox '
    'ON (ffm_pkt1.MANIFEST_EMBEDDED_IN = ffm_bag_dox.MANIFEST_ID) '
  /* last OGM prepared Bag at origin against the Consignment number of PPX */ 
  'LEFT JOIN ff_f_manifest ffm_bag_ppx1 '
    'ON (ffm_bag_ppx1.MANIFEST_ID = ffcm.MANIFEST_ID AND '
        'ffm_bag_ppx1.MANIFEST_LOAD_CONTENT = fdct.CONSIGNMENT_TYPE_ID AND '
        'ffm_bag_ppx1.MANIFEST_TYPE = ''O'') '
  'LEFT JOIN '
  '(SELECT '
     'ffcm2.consignment_id '
    ',ffm2.MANIFEST_DATE '
    ',ffm2.MANIFEST_ID '
    ',ffm2.MANIFEST_NO '
    ',ffm2.MANIFEST_TYPE '
   'FROM '
     'ff_f_consignment_manifested ffcm2 '
     'LEFT JOIN ff_f_manifest ffm2 ON ffm2.manifest_id = ffcm2.manifest_id) '
  'AS ffm_bag_ppx2 '
    'ON (ffcm.consignment_id = ffm_bag_ppx2.consignment_id AND '
        'ffm_bag_ppx2.MANIFEST_TYPE = ffm_bag_ppx1.MANIFEST_TYPE AND '
        '(ffm_bag_ppx1.MANIFEST_DATE < ffm_bag_ppx2.MANIFEST_DATE OR '
         '(ffm_bag_ppx1.MANIFEST_DATE = ffm_bag_ppx2.MANIFEST_DATE AND '
          'ffm_bag_ppx1.MANIFEST_ID < ffm_bag_ppx2.MANIFEST_ID))) '
  /* master bag */ 
  'LEFT JOIN ff_f_manifest ffm_mbag '
    'ON CASE '
         'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' '
         'THEN '
           '(ffm_bag_dox.MANIFEST_EMBEDDED_IN = ffm_mbag.MANIFEST_ID) '
         'WHEN fdct.CONSIGNMENT_CODE = ''PPX'' '
         'THEN '
           '(ffm_bag_ppx1.MANIFEST_EMBEDDED_IN = ffm_mbag.MANIFEST_ID) '
         'ELSE '
           'FALSE '
       'END '
  /* load movement for Bag of DOX */ 
  'LEFT JOIN ff_f_load_connected fflc_bag_dox '
    'ON (ffm_bag_dox.MANIFEST_ID = fflc_bag_dox.MANIFEST) '
  'LEFT JOIN ff_f_load_movement fflm_bag_dox '
    'ON fflm_bag_dox.LOAD_MOVEMENT_ID = fflc_bag_dox.LOAD_MOVEMENT '
  /* load movement for Bag of PPX */ 
  'LEFT JOIN ff_f_load_connected fflc_bag_ppx '
    'ON (ffm_bag_ppx1.MANIFEST_ID = fflc_bag_ppx.MANIFEST) '
  'LEFT JOIN ff_f_load_movement fflm_bag_ppx '
    'ON fflm_bag_ppx.LOAD_MOVEMENT_ID = fflc_bag_ppx.LOAD_MOVEMENT '
  /* load movement for Bag of PPX */ 
  'LEFT JOIN ff_f_load_connected fflc_mbag '
    'ON (ffm_mbag.MANIFEST_ID = fflc_mbag.MANIFEST) '
  'LEFT JOIN ff_f_load_movement fflm_mbag '
    'ON fflm_mbag.LOAD_MOVEMENT_ID = fflc_mbag.LOAD_MOVEMENT '
  /* last in manifest */ 
  'LEFT JOIN (SELECT '
               'manifest1.MANIFEST_ID '
              ',manifest1.MANIFEST_NO '
              ',manifest1.MANIFEST_DATE '
              ',manifest1.ORIGIN_OFFICE '
              ',manifest1.MANIFEST_EMBEDDED_IN '
              ',manifest1.CONSIGNMENT_ID '
              ',manifest1.MANIFEST_TYPE '
             'FROM '
               '(SELECT '
                  'm.MANIFEST_ID '
                 ',m.MANIFEST_NO '
                 ',m.MANIFEST_DATE '
                 ',m.ORIGIN_OFFICE '
                 ',m.MANIFEST_EMBEDDED_IN '
                 ',m.MANIFEST_TYPE '
                 ',cm.CONSIGNMENT_ID '
                'FROM '
                  'ff_f_consignment_manifested cm '
                  'JOIN ff_f_manifest m '
                    'ON cm.MANIFEST_ID = m.MANIFEST_ID AND '
                       'm.manifest_type = ''I'') manifest1 '
               'LEFT JOIN (SELECT '
                            'cm.CONSIGNMENT_ID '
                           ',m.MANIFEST_DATE '
                           ',m.MANIFEST_TYPE '
                          'FROM '
                            'ff_f_consignment_manifested cm '
                            'JOIN ff_f_manifest m '
                              'ON cm.MANIFEST_ID = m.MANIFEST_ID AND '
                                 'm.manifest_type = ''I'') manifest2 '
                 'ON manifest1.CONSIGNMENT_ID = manifest2.CONSIGNMENT_ID AND '
                    'manifest1.MANIFEST_DATE < manifest2.MANIFEST_DATE '
             'WHERE '
               'manifest2.MANIFEST_DATE IS NULL) ffm_in '
    'ON (ffm_in.CONSIGNMENT_ID = ffc.CONSG_ID) '
  /* Delivery details */ 
  'LEFT JOIN ff_f_delivery_dtls ffdd1 ON ffdd1.CONSIGNMENT_ID = ffc.CONSG_ID '
  'LEFT OUTER JOIN ff_f_delivery_dtls ffdd2 '
    'ON (ffdd1.CONSIGNMENT_ID = ffdd2.CONSIGNMENT_ID AND '
        '(ffdd1.TRANS_MODIFIED_DATE_TIME < ffdd2.TRANS_MODIFIED_DATE_TIME OR '
         '(ffdd1.TRANS_MODIFIED_DATE_TIME = ffdd2.TRANS_MODIFIED_DATE_TIME AND '
          'ffdd1.DELIVERY_DETAIL_ID > ffdd2.DELIVERY_DETAIL_ID))) '
  'LEFT JOIN ff_f_delivery ffd ON ffd.DELIVERY_ID = ffdd1.DELIVERY_ID '
  'LEFT JOIN ff_d_reason fdr ON fdr.REASON_ID = ffdd1.REASON_ID '
  /* vehicle data */ 
  'LEFT OUTER JOIN ff_d_vehicle fdv '
    'ON CASE '
         'WHEN ffm_mbag.MANIFEST_ID IS NOT NULL '
         'THEN '
           'fflm_mbag.VEHICLE = fdv.VEHICLE_ID '
         'WHEN ffm_mbag.MANIFEST_ID IS NULL AND '
              'fdct.CONSIGNMENT_CODE = ''DOX'' '
         'THEN '
           'fflm_bag_dox.VEHICLE = fdv.VEHICLE_ID '
         'WHEN ffm_mbag.MANIFEST_ID IS NULL AND '
              'fdct.CONSIGNMENT_CODE = ''PPX'' '
         'THEN '
           'fflm_bag_ppx.VEHICLE = fdv.VEHICLE_ID '
       'END '
  'LEFT JOIN ff_f_trip_serviced_by fftsb '
    'ON CASE '
         'WHEN ffm_mbag.MANIFEST_ID IS NOT NULL '
         'THEN '
           'fflm_mbag.TRIP_SERVICED_BY = fftsb.TRIP_SERVICED_BY_ID '
         'WHEN ffm_mbag.MANIFEST_ID IS NULL AND '
              'fdct.CONSIGNMENT_CODE = ''DOX'' '
         'THEN '
           'fflm_bag_dox.TRIP_SERVICED_BY = fftsb.TRIP_SERVICED_BY_ID '
         'WHEN ffm_mbag.MANIFEST_ID IS NULL AND '
              'fdct.CONSIGNMENT_CODE = ''PPX'' '
         'THEN '
           'fflm_bag_ppx.TRIP_SERVICED_BY = fftsb.TRIP_SERVICED_BY_ID '
       'END '
  'LEFT JOIN ff_f_trip fft ON fft.TRIP_ID = fftsb.TRIP '
  'LEFT JOIN ff_f_transport fftrn ON fftrn.TRANSPORT_ID = fft.TRANSPORT '
  'LEFT JOIN ff_d_flight fdf ON fdf.FLIGHT_ID = fftrn.FLIGHT '
  'LEFT JOIN ff_d_train fdt ON fdt.TRAIN_ID = fftrn.TRAIN '
  'LEFT JOIN ff_d_vehicle fdv1 ON fdv1.VEHICLE_ID = fftrn.VEHICLE '
  /* Receive information */ 
  'LEFT JOIN ff_f_load_movement fflm_rec '
    'ON CASE '
         'WHEN fflm_mbag.LOAD_MOVEMENT_ID '
         'THEN '
           '(fflm_mbag.GATE_PASS_NUMBER = fflm_rec.GATE_PASS_NUMBER AND '
            'fflm_rec.MOVEMENT_DIRECTION = ''R'') '
         'WHEN fflm_bag_dox.LOAD_MOVEMENT_ID '
         'THEN '
           '(fflm_bag_dox.GATE_PASS_NUMBER = fflm_rec.GATE_PASS_NUMBER AND '
            'fflm_rec.MOVEMENT_DIRECTION = ''R'') '
         'WHEN fflm_bag_ppx.LOAD_MOVEMENT_ID '
         'THEN '
           '(fflm_bag_ppx.GATE_PASS_NUMBER = fflm_rec.GATE_PASS_NUMBER AND '
            'fflm_rec.MOVEMENT_DIRECTION = ''R'') '
         'ELSE '
           'FALSE '
       'END '
  'LEFT JOIN ff_f_trip_serviced_by ftsb_rec '
    'ON fflm_rec.TRIP_SERVICED_BY = ftsb_rec.TRIP_SERVICED_BY_ID '
  'LEFT JOIN ff_f_trip fft_rec ON ftsb_rec.TRIP = fft_rec.TRIP_ID '
'WHERE '
  'CASE '
    'WHEN ffm_pkt1.MANIFEST_ID IS NOT NULL  '
    'THEN  '
      'ffm_pkt1.manifest_type = ''O'' '
    'ELSE  '
    'case  '
      'when ffcm.CONSIGNMENT_MANIFESTED_ID is null then '
        'TRUE '
      'else '
        'false '
    'end '
  'END AND '
  'CASE '
    'WHEN ffm_pkt1.MANIFEST_ID IS NOT NULL THEN ffm_pkt2.MANIFEST_ID IS NULL '
    'ELSE TRUE '
  'END AND '
  'CASE '
    'WHEN ffm_bag_ppx1.MANIFEST_ID IS NOT NULL '
    'THEN '
      'ffm_bag_ppx1.manifest_type = ''O'' '
    'ELSE '
    'case  '
      'when ffcm.CONSIGNMENT_MANIFESTED_ID is null then '
        'TRUE '
      'else '
        'false '
    'end '
  'END AND '
  'CASE '
    'WHEN ffm_bag_ppx1.MANIFEST_ID IS NOT NULL '
    'THEN '
      'ffm_bag_ppx2.MANIFEST_ID IS NULL '
    'ELSE '
      'TRUE '
  'END AND '
  'ffdd2.TRANS_MODIFIED_DATE_TIME IS NULL AND ');
  --  ffc.CONSG_NO IN ('F991M0100001','F01000000001');
  IF trackType = 'CN' THEN 
    SET @query = CONCAT(@query, 'ffb.CONSG_NUMBER IN (',consignments,');'); 
  END IF;
  
  IF trackType = 'RN' THEN 
    SET @query = CONCAT(@query, 'ffb.CUST_REF_NO IN (',consignments,');'); 
  END IF;
  
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END;

