ALTER TABLE ff_f_billing_consignment
  CHANGE ACTUAL_WEIGHT ACTUAL_WEIGHT double(10,3) DEFAULT NULL,
  CHANGE BREADTH BREADTH double(10,2) DEFAULT '0.00',
  CHANGE CONSG_STATUS CONSG_STATUS ENUM('B', 'S', 'D', 'P', 'H', 'R', 'X') NOT NULL DEFAULT 'B',
  CHANGE DECLARED_VALUE DECLARED_VALUE double(20,4) DEFAULT NULL,
  CHANGE DT_TO_BRANCH DT_TO_BRANCH ENUM('R','Y','N') NOT NULL DEFAULT 'N',
  CHANGE FINAL_WEIGHT FINAL_WEIGHT double(20,4) DEFAULT NULL,
  CHANGE HEIGHT HEIGHT double(10,2) DEFAULT '0.00',
  CHANGE LENGTH LENGTH double(10,2) DEFAULT '0.00',
  CHANGE PRICE PRICE double(20,6) DEFAULT '0.000000',
  CHANGE VOL_WEIGHT VOL_WEIGHT double(20,4) DEFAULT NULL;