-- ## Procedure Name : sp_consignment_bulk_tracking
-- ## Purpose : To track bulk consignments with Consignment/Reference Number
-- ## Syntax : call sp_consignment_bulk_tracking('CN/RN'," 'consgNo1/refNo1','consgNo2/refNo2',... ")
-- ## Created By : Shahnaz
-- ## Created Date : 29 Aug 2014
-- ## Updated By : Shahnaz
-- ## Updated Date : 23 Jan 2015
-- ## VERSION : 2.1
-- ## Resolved Issues : 
-- v2.0 - Performance improvement
-- v2.1 - 1. artf3760847: Error in Multiple tracking [Delivery date will be updated only when consignment is delivered.]
--        2. artf3756470 : C/ment reflecting in single tracking of UDAAN but not reflecting in Multiple tracking.[Base Table - ff_f_consignment]

DROP PROCEDURE IF EXISTS sp_consignment_bulk_tracking;
CREATE PROCEDURE sp_consignment_bulk_tracking(IN  trackType varchar(10), consignments varchar(30000))
BEGIN
   SET @query = CONCAT('SELECT '
   'CASE '
    'WHEN (ffc.CONSG_STATUS = ''R'' OR '
          'ffc.CONSG_STATUS = ''S'') '
    'THEN '
      'concat( '
--         'ffb.CONSG_NUMBER '
          'ffc.CONSG_NO '
       ',''*'') '
    'ELSE '
--       'ffb.CONSG_NUMBER '
        'ffc.CONSG_NO '
  'END '
    'AS CONSG_NO'
 ' ,IFNULL( '
    'ffb.CUST_REF_NO '
   ',ffc.REF_NO) '
    'AS REF_NO' 
 ' ,IFNULL( '
    'ffb.BOOKING_DATE '
   ',ffc.CREATED_DATE) '
    'AS BOOKING_DATE' 
 ' ,CASE '
    'WHEN fdc_book.CITY_ID IS NOT NULL '
    'THEN '
      'concat( '
        'fdc_book.CITY_CODE '
       ','' - '' '
       ',fdc_book.CITY_NAME) '
    'ELSE '
      'concat( '
        'fdc_cn.CITY_CODE '
       ','' - '' '
       ',fdc_cn.CITY_NAME) '
  'END '
    'AS ORIGIN_CITY' 
 ' ,CASE '
    'WHEN fdc_dest_book.CITY_ID IS NOT NULL '
    'THEN '
      'concat( '
        'fdc_dest_book.CITY_CODE '
       ','' - '' '
       ',fdc_dest_book.CITY_NAME) '
    'ELSE '
      'concat( '
        'fdc_dest_cn.CITY_CODE '
       ','' - '' '
       ',fdc_dest_cn.CITY_NAME) '
  'END '
    'AS DEST_CITY' 
 ' ,CASE '
    'WHEN (ffc.CONSG_STATUS = ''R'' AND '
          'ffdd1.DELIVERY_STATUS = ''O'') '
    'THEN '
     '''RTO'''
    'WHEN (ffc.CONSG_STATUS = ''R'' AND '
          'ffdd1.DELIVERY_STATUS = ''P'') '
    'THEN '
      '''RTO Delivery Pending'' '
    'WHEN (ffc.CONSG_STATUS = ''S'') '
    'THEN '
      '''RTO Delivered'' '
    'WHEN ffdd1.DELIVERY_STATUS IS NULL '
    'THEN '
      '''In Transit'' '
    'WHEN ffdd1.DELIVERY_STATUS = ''D'' '
    'THEN '
      '''Delivered'' '
    'WHEN ffdd1.DELIVERY_STATUS = ''P'' '
    'THEN '
      '''Pending'' '
    'WHEN ffdd1.DELIVERY_STATUS = ''O'' '
    'THEN '
      '''Out For Delivery'' '
  'END '
    'AS CN_STATUS' 
 ' ,fdr.REASON_NAME AS PENDING_REASON' 
--  ' ,IFNULL( '
    ',ffdd1.DELIVERY_TIME '
--    ',ffd.DRS_DATE) '
    'AS DELIVERY_DATE'
 ' ,IF( '
    'ffdd1.DELIVERY_TYPE = ''O'' '
   ',''( Office Seal & Sign )'' '
  ',ffdd1.RECEIVER_NAME) '
    'AS RECEIVER_NAME'
    ' ,IFNULL( '
    'ffb.FINAL_WEIGHT '
   ',ffc.FINAL_WEIGHT) '
    'AS CN_WEIGHT' 
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' THEN ffm_pkt1.MANIFEST_NO '
    'ELSE NULL '
  'END '
    'AS OGM_NO'
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' THEN ffm_pkt1.MANIFEST_DATE '
    'ELSE NULL '
  'END '
    'AS OGM_DATE'
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' THEN ffm_bag_dox.MANIFEST_NO '
    'ELSE ffm_bag_ppx1.MANIFEST_NO '
  'END '
    'AS BPL_NO'
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' THEN ffm_bag_dox.MANIFEST_DATE '
    'ELSE ffm_bag_ppx1.MANIFEST_DATE '
  'END '
    'AS BPL_DATE'
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' '
    'THEN '    
      'IFNULL(fflm_bag_dox_dsp.GATE_PASS_NUMBER,fflm_mbag_dox_dsp.GATE_PASS_NUMBER) '      
    'WHEN fdct.CONSIGNMENT_CODE = ''PPX'' '
    'THEN '    
      'IFNULL(fflm_bag_ppx_dsp.GATE_PASS_NUMBER,fflm_mbag_ppx_dsp.GATE_PASS_NUMBER) '    
  'END '
    'AS CD_NO' 
 ' ,CASE '
    'WHEN fdct.CONSIGNMENT_CODE = ''DOX'' '
    'THEN '
      'IFNULL(fflm_bag_dox_dsp.LOADING_DATE,fflm_mbag_dox_dsp.LOADING_DATE) '      
    'WHEN fdct.CONSIGNMENT_CODE = ''PPX'' '
    'THEN '
      'IFNULL(fflm_bag_ppx_dsp.LOADING_DATE,fflm_mbag_ppx_dsp.LOADING_DATE) '
  'END '
    'AS CD_DATE' 
    
    
 ' ,CASE '
    'WHEN fdf.FLIGHT_NUMBER IS NOT NULL '
    'THEN '
       'fdf.FLIGHT_NUMBER '
    'WHEN fdt.TRAIN_NUMBER IS NOT NULL '
    'THEN '
      'fdt.TRAIN_NUMBER '
    'WHEN fdv1.REG_NUMBER IS NOT NULL '
    'THEN '
      'fdv1.REG_NUMBER '
    'WHEN fflm_mbag_dox_dsp.VEHICLE_REG_NUMBER IS NOT NULL OR '
         'fflm_mbag_ppx_dsp.VEHICLE_REG_NUMBER IS NOT NULL OR '
         'fflm_bag_dox_dsp.VEHICLE_REG_NUMBER IS NOT NULL OR '
         'fflm_bag_ppx_dsp.VEHICLE_REG_NUMBER IS NOT NULL '
    'THEN '
      'CASE '
        'WHEN fflm_mbag_dox_dsp.load_movement_id IS NOT NULL '
        'THEN '
          'fflm_mbag_dox_dsp.VEHICLE_REG_NUMBER '
        'WHEN fflm_mbag_ppx_dsp.load_movement_id IS NOT NULL '
        'THEN '
          'fflm_mbag_ppx_dsp.VEHICLE_REG_NUMBER '          
        'WHEN fflm_bag_dox_dsp.load_movement_id IS NOT NULL '
        'THEN '
          'fflm_bag_dox_dsp.VEHICLE_REG_NUMBER '
          
        'WHEN fflm_bag_ppx_dsp.load_movement_id IS NOT NULL '
        'THEN '
          'fflm_bag_ppx_dsp.VEHICLE_REG_NUMBER '          
      'END '
    'WHEN fdv_mbag_dox_dsp.REG_NUMBER IS NOT NULL '
    'THEN '
      'fdv_mbag_dox_dsp.REG_NUMBER '    
    'WHEN fdv_mbag_ppx_dsp.REG_NUMBER IS NOT NULL '
    'THEN '
      'fdv_mbag_ppx_dsp.REG_NUMBER '    
    'WHEN fdv_bag_dox_dsp.REG_NUMBER IS NOT NULL '
    'THEN '
      'fdv_bag_dox_dsp.REG_NUMBER '      
    'WHEN fdv_bag_ppx_dsp.REG_NUMBER IS NOT NULL '
    'THEN '
      'fdv_bag_ppx_dsp.REG_NUMBER '      
  'END '
    'AS FLIGHT_NO' 
 ' ,fftrp_dsp.DEPARTURE_TIME AS FLIGHT_DEP'
 ' ,IF( '
    'fflm_rcv.RECEIVE_TYPE = ''O'' '
   ',fftrp_rcv.ARRIVAL_TIME '
   ',fflm_rcv.RECEIVED_AT_TIME) '
    'AS FLIGHT_ARR'
    
 ' ,CASE '
    'WHEN fflm_rcv.LOADING_DATE IS NOT NULL '
    'THEN '
      'IF( '
        'fflm_rcv.RECEIVE_TYPE = ''O'' '
       ',CONCAT( '
          'DATE_FORMAT( '
            'fflm_rcv.LOADING_DATE '
           ',''%m-%d-%Y'') '
         ','' '' '
         ',fftrp_rcv.ARRIVAL_TIME) '
       ',CONCAT( '
          'DATE_FORMAT( '
            'fflm_rcv.LOADING_DATE '
           ',''%m-%d-%Y'') '
         ','' '' '
         ',fflm_rcv.RECEIVED_AT_TIME)) '
         
    'ELSE '
      'ffm_in1.MANIFEST_DATE '
  'END '
    'AS RCV_DATE'
 ' ,date_format( '
    'ffm_in1.MANIFEST_DATE '
   ',''%m-%d-%Y %H:%i:%S'') '
    'AS IN_MNFST_DATE '
-- ' FROM ff_f_booking ffb   '
--   'LEFT JOIN ff_f_consignment ffc ON ffc.CONSG_NO = ffb.CONSG_NUMBER '
-- 'LEFT JOIN ff_d_consignment_type fdct ON fdct.CONSIGNMENT_TYPE_ID = ffc.CONSG_TYPE '

  'FROM ff_f_consignment ffc '
  'LEFT JOIN ff_d_consignment_type fdct ON fdct.CONSIGNMENT_TYPE_ID = ffc.CONSG_TYPE '
  'LEFT JOIN ff_f_booking ffb ON ffb.CONSG_NUMBER = ffc.CONSG_NO ' 
  'LEFT JOIN ff_d_office fdo_book ON fdo_book.OFFICE_ID = ffb.BOOKING_OFF '
  'LEFT JOIN ff_d_city fdc_book ON fdc_book.CITY_ID = fdo_book.CITY_ID '
  'LEFT JOIN ff_d_office fdo_cn ON fdo_cn.office_id = ffc.ORG_OFF '
  'LEFT JOIN ff_d_city fdc_cn ON fdc_cn.CITY_ID = fdo_cn.CITY_ID '
  'LEFT JOIN ff_d_pincode fdpin_book ON fdpin_book.pincode_id = ffb.DEST_PINCODE '
  'LEFT JOIN ff_d_pincode fdpin_cn ON fdpin_cn.PINCODE_ID = ffc.DEST_PINCODE '
  'LEFT JOIN ff_d_city fdc_dest_book ON fdc_dest_book.CITY_ID = fdpin_book.CITY_ID '
  'LEFT JOIN ff_d_city fdc_dest_cn ON fdc_dest_cn.CITY_ID = fdpin_cn.CITY_ID '
  'LEFT JOIN ff_f_consignment_manifested ffcm ON ffcm.CONSIGNMENT_ID = ffc.CONSG_ID '
  /* last OGM prepared Packet at origin against the Consignment number of DOX */ 
  'LEFT JOIN ff_f_manifest ffm_pkt1 '
    'ON (ffm_pkt1.MANIFEST_ID = ffcm.MANIFEST_ID AND '
        'ffm_pkt1.MANIFEST_TYPE = ''O'') '
  'LEFT JOIN ff_f_manifest ffm_pkt2 ' 
   'ON (ffcm.manifest_id = ffm_pkt2.manifest_id AND '
      'ffm_pkt2.MANIFEST_TYPE = ffm_pkt1.MANIFEST_TYPE AND '
      '(ffm_pkt2.MANIFEST_DATE < ffm_pkt1.MANIFEST_DATE OR '
      '(ffm_pkt2.MANIFEST_DATE = ffm_pkt1.MANIFEST_DATE AND '
      'ffm_pkt2.MANIFEST_ID < ffm_pkt1.MANIFEST_ID))) '          
  /* last OGM prepared Bag at origin against the Consignment number of DOX 
     for above packet */ 
  'LEFT JOIN ff_f_manifest ffm_bag_dox '
    'ON (ffm_pkt1.MANIFEST_EMBEDDED_IN = ffm_bag_dox.MANIFEST_ID) '
  /* last OGM prepared Bag at origin against the Consignment number of PPX */ 
  'LEFT JOIN ff_f_manifest ffm_bag_ppx1 '
    'ON (ffm_bag_ppx1.MANIFEST_ID = ffcm.MANIFEST_ID AND '
        'ffm_bag_ppx1.MANIFEST_TYPE = ''O'') '
        
  'LEFT JOIN ff_f_manifest ffm_bag_ppx2 '
    'ON (ffcm.manifest_id = ffm_bag_ppx2.manifest_id AND '
      'ffm_bag_ppx2.MANIFEST_TYPE = ffm_bag_ppx1.MANIFEST_TYPE AND '
      '(ffm_bag_ppx1.MANIFEST_DATE < ffm_bag_ppx2.MANIFEST_DATE OR '
      '(ffm_bag_ppx1.MANIFEST_DATE = ffm_bag_ppx2.MANIFEST_DATE AND '
      'ffm_bag_ppx1.MANIFEST_ID < ffm_bag_ppx2.MANIFEST_ID))) '
  /* master bag */ 
  'LEFT JOIN ff_f_manifest ffm_mbag_dox ON ffm_bag_dox.MANIFEST_EMBEDDED_IN = ffm_mbag_dox.MANIFEST_ID '
  'LEFT JOIN ff_f_manifest ffm_mbag_ppx ON ffm_bag_ppx2.MANIFEST_EMBEDDED_IN = ffm_mbag_ppx.MANIFEST_ID '
  
  /* load movement for Bag of DOX - DISPATCH */ 
  'LEFT JOIN ff_f_load_connected fflc_bag_dox_dsp '
    'ON (ffm_bag_dox.MANIFEST_ID = fflc_bag_dox_dsp.MANIFEST) '
  'LEFT JOIN ff_f_load_movement fflm_bag_dox_dsp '
    'ON fflm_bag_dox_dsp.LOAD_MOVEMENT_ID = fflc_bag_dox_dsp.LOAD_MOVEMENT '
    'AND fflm_bag_dox_dsp.MOVEMENT_DIRECTION = ''D'' '
  /* load movement for master Bag of DOX - DISPATCH */
  'LEFT JOIN ff_f_load_connected fflc_mbag_dox_dsp '
    'ON (ffm_mbag_dox.MANIFEST_ID = fflc_mbag_dox_dsp.MANIFEST) '
  'LEFT JOIN ff_f_load_movement fflm_mbag_dox_dsp '
    'ON fflm_mbag_dox_dsp.LOAD_MOVEMENT_ID = fflc_mbag_dox_dsp.LOAD_MOVEMENT '
    'AND fflm_bag_dox_dsp.MOVEMENT_DIRECTION = ''D'' '
  /* load movement for Bag of PPX - DISPATCH */
  'LEFT JOIN ff_f_load_connected fflc_bag_ppx_dsp '
    'ON (ffm_bag_ppx2.MANIFEST_ID = fflc_bag_ppx_dsp.MANIFEST) '
  'LEFT JOIN ff_f_load_movement fflm_bag_ppx_dsp '
    'ON fflm_bag_ppx_dsp.LOAD_MOVEMENT_ID = fflc_bag_ppx_dsp.LOAD_MOVEMENT '
    'AND fflm_bag_dox_dsp.MOVEMENT_DIRECTION = ''D'' '
  /* load movement for master Bag of PPX - DISPATCH */
  'LEFT JOIN ff_f_load_connected fflc_mbag_ppx_dsp '
    'ON (ffm_mbag_ppx.MANIFEST_ID = fflc_mbag_ppx_dsp.MANIFEST) '
  'LEFT JOIN ff_f_load_movement fflm_mbag_ppx_dsp '
    'ON fflm_mbag_ppx_dsp.LOAD_MOVEMENT_ID = fflc_mbag_ppx_dsp.LOAD_MOVEMENT '
    'AND fflm_bag_dox_dsp.MOVEMENT_DIRECTION = ''D'' '
  
  'LEFT OUTER JOIN ff_d_vehicle fdv_mbag_dox_dsp ON fflm_mbag_dox_dsp.VEHICLE = fdv_mbag_dox_dsp.VEHICLE_ID '
    'AND ffm_mbag_dox.MANIFEST_ID IS NOT NULL  '
  'LEFT OUTER JOIN ff_d_vehicle fdv_mbag_ppx_dsp ON fflm_mbag_ppx_dsp.VEHICLE = fdv_mbag_ppx_dsp.VEHICLE_ID '
    'AND ffm_mbag_ppx.MANIFEST_ID IS NOT NULL '      
  'LEFT OUTER JOIN ff_d_vehicle fdv_bag_dox_dsp ON fflm_bag_dox_dsp.VEHICLE = fdv_bag_dox_dsp.VEHICLE_ID '
    'AND ffm_bag_dox.MANIFEST_ID IS NOT NULL '
  'LEFT OUTER JOIN ff_d_vehicle fdv_bag_ppx_dsp ON fflm_bag_ppx_dsp.VEHICLE = fdv_bag_ppx_dsp.VEHICLE_ID '
    'AND ffm_bag_ppx2.MANIFEST_ID IS NOT NULL '
    
  'LEFT JOIN ff_f_trip_serviced_by fftsb_bag_dox_dsp ON fflm_bag_dox_dsp.TRIP_SERVICED_BY = fftsb_bag_dox_dsp.TRIP_SERVICED_BY_ID '    
      'AND ffm_bag_dox.MANIFEST_ID IS NOT NULL '
  'LEFT JOIN ff_f_trip_serviced_by fftsb_mbag_dox_dsp ON fflm_mbag_dox_dsp.TRIP_SERVICED_BY = fftsb_mbag_dox_dsp.TRIP_SERVICED_BY_ID '
      'AND ffm_mbag_dox.MANIFEST_ID IS NOT NULL '
  'LEFT JOIN ff_f_trip_serviced_by fftsb_bag_ppx_dsp ON fflm_bag_ppx_dsp.TRIP_SERVICED_BY = fftsb_bag_ppx_dsp.TRIP_SERVICED_BY_ID '    
      'AND ffm_bag_ppx2.MANIFEST_ID IS NOT NULL '
  'LEFT JOIN ff_f_trip_serviced_by fftsb_mbag_ppx_dsp ON fflm_mbag_ppx_dsp.TRIP_SERVICED_BY = fftsb_mbag_ppx_dsp.TRIP_SERVICED_BY_ID '
      'AND ffm_mbag_ppx.MANIFEST_ID IS NOT NULL '     
       
  'LEFT JOIN ff_f_trip fftrp_dsp ON '
  'CASE '
    'WHEN fflm_bag_dox_dsp.LOAD_MOVEMENT_ID IS NOT NULL '
      'THEN fftrp_dsp.TRIP_ID = fftsb_bag_dox_dsp.TRIP '
    'WHEN fflm_mbag_dox_dsp.LOAD_MOVEMENT_ID IS NOT NULL ' 
      'THEN fftrp_dsp.TRIP_ID = fftsb_mbag_dox_dsp.TRIP '
    'WHEN fflm_bag_ppx_dsp.LOAD_MOVEMENT_ID IS NOT NULL '
      'THEN fftrp_dsp.TRIP_ID = fftsb_bag_ppx_dsp.TRIP '
    'WHEN fflm_mbag_ppx_dsp.LOAD_MOVEMENT_ID IS NOT NULL ' 
      'THEN fftrp_dsp.TRIP_ID = fftsb_mbag_ppx_dsp.TRIP '
  'END '
  
  'LEFT JOIN ff_f_transport fftrn ON fftrn.TRANSPORT_ID = fftrp_dsp.TRANSPORT '
  'LEFT JOIN ff_d_flight fdf ON fdf.FLIGHT_ID = fftrn.FLIGHT '
  'LEFT JOIN ff_d_train fdt ON fdt.TRAIN_ID = fftrn.TRAIN '
  'LEFT JOIN ff_d_vehicle fdv1 ON fdv1.VEHICLE_ID = fftrn.VEHICLE '
  
  /* last in manifest */ 
  'LEFT JOIN ff_f_manifest ffm_in1 ON ffcm.MANIFEST_ID = ffm_in1.MANIFEST_ID AND ffm_in1.MANIFEST_TYPE = ''I'' '
  'LEFT JOIN ff_f_manifest ffm_in2 '
  'ON (ffcm.manifest_id = ffm_in2.manifest_id AND '
      'ffm_in2.MANIFEST_TYPE = ffm_in1.MANIFEST_TYPE AND '
      '(ffm_in2.MANIFEST_DATE > ffm_in1.MANIFEST_DATE OR '
      '(ffm_in2.MANIFEST_DATE = ffm_in1.MANIFEST_DATE AND '
      'ffm_in2.MANIFEST_ID > ffm_in1.MANIFEST_ID))) '
      
   /*** RECEIVE ***/
  'LEFT JOIN ff_f_load_connected fflc_rcv ON (ffm_in1.MANIFEST_ID = fflc_rcv.MANIFEST) '    
  'LEFT JOIN ff_f_load_movement fflm_rcv ON fflm_rcv.LOAD_MOVEMENT_ID = fflc_rcv.LOAD_MOVEMENT '
    'AND fflm_rcv.MOVEMENT_DIRECTION = ''R'' '
    
  'LEFT JOIN ff_f_trip_serviced_by fftsb_rcv ON fflm_rcv.TRIP_SERVICED_BY = fftsb_rcv.TRIP_SERVICED_BY_ID '    
      'AND ffm_in1.MANIFEST_ID IS NOT NULL '
  'LEFT JOIN ff_f_trip fftrp_rcv ON fftrp_rcv.TRIP_ID = fftsb_rcv.TRIP '
  
  /* Delivery details */ 
  'LEFT JOIN ff_f_delivery_dtls ffdd1 ON ffdd1.CONSIGNMENT_ID = ffc.CONSG_ID '
  'LEFT OUTER JOIN ff_f_delivery_dtls ffdd2 '
  'ON (ffdd1.CONSIGNMENT_ID = ffdd2.CONSIGNMENT_ID AND '
       '(ffdd1.TRANS_MODIFIED_DATE_TIME < ffdd2.TRANS_MODIFIED_DATE_TIME OR '
       '(ffdd1.TRANS_MODIFIED_DATE_TIME = ffdd2.TRANS_MODIFIED_DATE_TIME AND '
        'ffdd1.DELIVERY_DETAIL_ID > ffdd2.DELIVERY_DETAIL_ID))) '
  'LEFT JOIN ff_f_delivery ffd ON ffd.DELIVERY_ID = ffdd1.DELIVERY_ID '
  'LEFT JOIN ff_d_reason fdr ON fdr.REASON_ID = ffdd1.REASON_ID '
  
'WHERE '
  'ffm_pkt2.MANIFEST_ID IS NULL '
  'AND ffm_bag_ppx2.MANIFEST_ID IS NULL '
  'AND ffm_in2.MANIFEST_ID IS NULL '
  'AND ffdd2.DELIVERY_DETAIL_ID IS NULL AND ');
  IF trackType = 'CN' THEN 
--     SET @query = CONCAT(@query, 'ffb.CONSG_NUMBER IN (',consignments,') GROUP BY ffb.CONSG_NUMBER;'); 
      SET @query = CONCAT(@query, 'ffc.CONSG_NO IN (',consignments,') GROUP BY ffc.CONSG_NO;');
  END IF;
  
  IF trackType = 'RN' THEN 
--     SET @query = CONCAT(@query, 'ffb.CUST_REF_NO IN (',consignments,') GROUP BY ffb.CONSG_NUMBER;'); 
      SET @query = CONCAT(@query, 'ffc.REF_NO IN (',consignments,') GROUP BY ffc.REF_NO;');
  END IF;
  
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END;

