package com.firstflight.mm.csdtosap.goodscancellation;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-05-28T14:49:43.492+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/GoodsCancellation", name = "SI_CSD_GoodsCancellation_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDGoodsCancellationOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_GoodsCancellation_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDGoodsCancellationOut(
        @WebParam(partName = "MT_CSD_GoodsCancellation", name = "MT_CSD_GoodsCancellation", targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/GoodsCancellation")
        DTCSDGoodsCancellation mtCSDGoodsCancellation
    );
}
