
package com.firstflight.mm.csdtosap.goodscancellation;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-05-28T14:49:43.211+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDGoodsCancellationOut_SICSDGoodsCancellationOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDGoodsCancellationOut_SICSDGoodsCancellationOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/MM/CSDToSAP/GoodsCancellation", "SI_CSD_GoodsCancellation_OutService");

    private SICSDGoodsCancellationOut_SICSDGoodsCancellationOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDGoodsCancellationOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDGoodsCancellationOut_SICSDGoodsCancellationOutPort_Client::main::error::",e);
            }
        }
      
        SICSDGoodsCancellationOutService ss = new SICSDGoodsCancellationOutService(wsdlURL, SERVICE_NAME);
        SICSDGoodsCancellationOut port = ss.getSICSDGoodsCancellationOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDGoodsCancellationOut...");
        com.firstflight.mm.csdtosap.goodscancellation.DTCSDGoodsCancellation _siCSDGoodsCancellationOut_mtCSDGoodsCancellation = new com.firstflight.mm.csdtosap.goodscancellation.DTCSDGoodsCancellation();
        java.util.List<com.firstflight.mm.csdtosap.goodscancellation.DTCSDGoodsCancellation.GoodsCancellation> _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellation = new java.util.ArrayList<com.firstflight.mm.csdtosap.goodscancellation.DTCSDGoodsCancellation.GoodsCancellation>();
        com.firstflight.mm.csdtosap.goodscancellation.DTCSDGoodsCancellation.GoodsCancellation _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1 = new com.firstflight.mm.csdtosap.goodscancellation.DTCSDGoodsCancellation.GoodsCancellation();
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1.setTimestamp("Timestamp-941071972");
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1.setSAPStatus("SAPStatus-2063600235");
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1.setDocDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-05-28T14:49:43.461+05:30"));
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1.setReason("Reason1658678988");
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1.setMaterialCode("MaterialCode1988929413");
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1.setQuantity("Quantity41561867");
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1.setStkCanDocNo("StkCanDocNo688892774");
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1.setLoggedInPlant("LoggedInPlant-1919464777");
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1.setPostingDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-05-28T14:49:43.461+05:30"));
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellation.add(_siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellationVal1);
        _siCSDGoodsCancellationOut_mtCSDGoodsCancellation.getGoodsCancellation().addAll(_siCSDGoodsCancellationOut_mtCSDGoodsCancellationGoodsCancellation);
        port.siCSDGoodsCancellationOut(_siCSDGoodsCancellationOut_mtCSDGoodsCancellation);


        }

        System.exit(0);
    }

}
