
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.firstflight.mm.csdtosap.goodscancellation;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-05-28T14:49:43.477+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "SI_CSD_GoodsCancellation_OutService",
                      portName = "SI_CSD_GoodsCancellation_OutPort",
                      targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/GoodsCancellation",
                      wsdlLocation = "http://pidev.firstflight.net:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FGoodsCancellation%5ESI_CSD_GoodsCancellation_Out&QualityOfService=ExactlyOnce&sap-user=cg-pi&sap-password=gouri1",
                      endpointInterface = "com.firstflight.mm.csdtosap.goodscancellation.SICSDGoodsCancellationOut")
                      
public class SICSDGoodsCancellationOutImpl implements SICSDGoodsCancellationOut {

	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDGoodsCancellationOutImpl.class);

    /* (non-Javadoc)
     * @see com.firstflight.mm.csdtosap.goodscancellation.SICSDGoodsCancellationOut#siCSDGoodsCancellationOut(com.firstflight.mm.csdtosap.goodscancellation.DTCSDGoodsCancellation  mtCSDGoodsCancellation )*
     */
    public void siCSDGoodsCancellationOut(DTCSDGoodsCancellation mtCSDGoodsCancellation) { 
    	LOGGER.info("Executing operation siCSDGoodsCancellationOut");
    	  LOGGER.debug("mtCSDGoodsCancellation::"+mtCSDGoodsCancellation);
        try {
        } catch (java.lang.Exception ex) {
        	LOGGER.error("SICSDGoodsCancellationOutImpl::siCSDGoodsCancellationOut::error::",ex);
            throw new RuntimeException(ex);
        }
    }

}
