
package com.firstflight.fi.csdtosap.expenseentries;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-08-06T15:54:45.559+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDExpenseEntriesOut_SICSDExpenseEntriesOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDExpenseEntriesOut_SICSDExpenseEntriesOutPort_Client.class);


    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/FI/CSDToSAP/ExpenseEntries", "SI_CSD_ExpenseEntries_OutService");

    private SICSDExpenseEntriesOut_SICSDExpenseEntriesOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDExpenseEntriesOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDExpenseEntriesOut_SICSDExpenseEntriesOutPort_Client::main::error::",e);
            }
        }
      
        SICSDExpenseEntriesOutService ss = new SICSDExpenseEntriesOutService(wsdlURL, SERVICE_NAME);
        SICSDExpenseEntriesOut port = ss.getSICSDExpenseEntriesOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDExpenseEntriesOut...");
        com.firstflight.fi.csdtosap.expenseentries.DTCSDExpenseEntries _siCSDExpenseEntriesOut_mtCSDExpenseEntries = new com.firstflight.fi.csdtosap.expenseentries.DTCSDExpenseEntries();
        java.util.List<com.firstflight.fi.csdtosap.expenseentries.DTCSDExpenseEntries.ExpenseEntries> _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntries = new java.util.ArrayList<com.firstflight.fi.csdtosap.expenseentries.DTCSDExpenseEntries.ExpenseEntries>();
        com.firstflight.fi.csdtosap.expenseentries.DTCSDExpenseEntries.ExpenseEntries _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1 = new com.firstflight.fi.csdtosap.expenseentries.DTCSDExpenseEntries.ExpenseEntries();
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setReportingRHOCode("ReportingRHOCode-190128427");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setBranchCode("BranchCode-1320005607");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setTransactionID("TransactionID-768727310");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setExpenseGLCode("ExpenseGLCode1418866669");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setModeOfPayment("ModeOfPayment-1488975093");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setBankGLCode("BankGLCode120366244");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setAmount("Amount609691147");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setChequeDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-08-06T15:54:45.746+05:30"));
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setChequeNo("ChequeNo-1435849497");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setChequeBank("ChequeBank-222492080");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setCreationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-08-06T15:54:45.762+05:30"));
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setSAPStatus("SAPStatus1226012102");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setEmployeeCode("EmployeeCode-1700865188");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setConsignmentNo("ConsignmentNo-820846303");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setDestinationRHO("DestinationRHO217663480");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setServiceCharge("ServiceCharge-1930269001");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setServiceTaxBasic("ServiceTaxBasic-274519724");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setEDOnServiceTax("EDOnServiceTax-732449924");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setHEDOnServiceTax("HEDOnServiceTax-1799585738");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setGLIndicator("GLIndicator1245219317");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setTimestamp("Timestamp2069083961");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1.setRemarks("Remarks-1078831212");
        _siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntries.add(_siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntriesVal1);
        _siCSDExpenseEntriesOut_mtCSDExpenseEntries.getExpenseEntries().addAll(_siCSDExpenseEntriesOut_mtCSDExpenseEntriesExpenseEntries);
        port.siCSDExpenseEntriesOut(_siCSDExpenseEntriesOut_mtCSDExpenseEntries);


        }

        System.exit(0);
    }

}
