package com.firstflight.mm.csdtosap.purchaserequisitions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-04-08T20:14:03.610+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "SI_CSD_PurchaseRequisition_OutService", 
                  wsdlLocation = "http://172.16.10.106:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FPurchaseRequisition%5ESI_CSD_PurchaseRequisition_Out&QualityOfService=ExactlyOnce&sap-user=cg-pi&sap-password=gouri1",
                  targetNamespace = "http://FirstFlight.com/MM/CSDToSAP/PurchaseRequisition") 
public class SICSDPurchaseRequisitionOutService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://FirstFlight.com/MM/CSDToSAP/PurchaseRequisition", "SI_CSD_PurchaseRequisition_OutService");
    public final static QName SICSDPurchaseRequisitionOutPort = new QName("http://FirstFlight.com/MM/CSDToSAP/PurchaseRequisition", "SI_CSD_PurchaseRequisition_OutPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.16.10.106:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FPurchaseRequisition%5ESI_CSD_PurchaseRequisition_Out&QualityOfService=ExactlyOnce&sap-user=cg-pi&sap-password=gouri1");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SICSDPurchaseRequisitionOutService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.16.10.106:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=CSD_DEV&Interface=http%3A%2F%2FFirstFlight.com%2FMM%2FCSDToSAP%2FPurchaseRequisition%5ESI_CSD_PurchaseRequisition_Out&QualityOfService=ExactlyOnce&sap-user=cg-pi&sap-password=gouri1");
        }
        WSDL_LOCATION = url;
    }

    public SICSDPurchaseRequisitionOutService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SICSDPurchaseRequisitionOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICSDPurchaseRequisitionOutService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDPurchaseRequisitionOutService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDPurchaseRequisitionOutService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SICSDPurchaseRequisitionOutService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SICSDPurchaseRequisitionOut
     */
    @WebEndpoint(name = "SI_CSD_PurchaseRequisition_OutPort")
    public SICSDPurchaseRequisitionOut getSICSDPurchaseRequisitionOutPort() {
        return super.getPort(SICSDPurchaseRequisitionOutPort, SICSDPurchaseRequisitionOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICSDPurchaseRequisitionOut
     */
    @WebEndpoint(name = "SI_CSD_PurchaseRequisition_OutPort")
    public SICSDPurchaseRequisitionOut getSICSDPurchaseRequisitionOutPort(WebServiceFeature... features) {
        return super.getPort(SICSDPurchaseRequisitionOutPort, SICSDPurchaseRequisitionOut.class, features);
    }

}
