
package com.firstflight.mm.csdtosap.purchaserequisitions;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-04-08T20:14:03.407+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDPurchaseRequisitionOut_SICSDPurchaseRequisitionOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDPurchaseRequisitionOut_SICSDPurchaseRequisitionOutPort_Client.class);
    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/MM/CSDToSAP/PurchaseRequisition", "SI_CSD_PurchaseRequisition_OutService");

    private SICSDPurchaseRequisitionOut_SICSDPurchaseRequisitionOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDPurchaseRequisitionOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDPurchaseRequisitionOut_SICSDPurchaseRequisitionOutPort_Client::main::error::",e);
            }
        }
      
        SICSDPurchaseRequisitionOutService ss = new SICSDPurchaseRequisitionOutService(wsdlURL, SERVICE_NAME);
        SICSDPurchaseRequisitionOut port = ss.getSICSDPurchaseRequisitionOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDPurchaseRequisitionOut...");
        com.firstflight.mm.csdtosap.purchaserequisitions.DTCSDPurchaseRequisition _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisition = new com.firstflight.mm.csdtosap.purchaserequisitions.DTCSDPurchaseRequisition();
        java.util.List<com.firstflight.mm.csdtosap.purchaserequisitions.DTCSDPurchaseRequisition.PurchaseRequisition> _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisition = new java.util.ArrayList<com.firstflight.mm.csdtosap.purchaserequisitions.DTCSDPurchaseRequisition.PurchaseRequisition>();
        com.firstflight.mm.csdtosap.purchaserequisitions.DTCSDPurchaseRequisition.PurchaseRequisition _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1 = new com.firstflight.mm.csdtosap.purchaserequisitions.DTCSDPurchaseRequisition.PurchaseRequisition();
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setTimestamp("Timestamp1788813327");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setROWNUMBER(new java.math.BigInteger("32183807666393108226460791696982343832"));
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setREQUISITIONOFFICECODE("REQUISITIONOFFICECODE-2068490029");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setREQCREATEDDATETIME(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-04-08T20:14:03.547+05:30"));
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setREQUISITIONNUMBER("REQUISITIONNUMBER-1429552007");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setITEMCODE("ITEMCODE-867270983");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setITEMTYPECODE("ITEMTYPECODE762855543");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setDESCRIPTION("DESCRIPTION1772084252");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setUOM("UOM684417939");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1.setAPPROVEDQUANTITY("APPROVEDQUANTITY645398544");
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisition.add(_siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisitionVal1);
        _siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisition.getPurchaseRequisition().addAll(_siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisitionPurchaseRequisition);
        port.siCSDPurchaseRequisitionOut(_siCSDPurchaseRequisitionOut_mtCSDPurchaseRequisition);


        }

        System.exit(0);
    }

}
