use CorpUDAAN;


INSERT INTO ff_d_std_type (ID,STD_TYPE_CODE,DESCRIPTION,PARENT_TYPE,TYPE_NAME,CUR_STATUS,DT_TO_BRANCH) VALUES(307,'Y','YP DRS','DRS_MODULE','DRS_BULK_LOAD_TYPE','A','N'),(308,'N','Fresh DRS','DRS_MODULE','DRS_BULK_LOAD_TYPE','A','N');