CREATE TABLE `ff_f_released_scripts` (
  `SCRIPT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SCRIPT_NAME` varchar(50) DEFAULT NULL,
  `MODULE_NAME` varchar(50) DEFAULT NULL,
  `SCRIPT_CONTENT` blob,
  `RELEASE_DATE` datetime DEFAULT NULL,
  `IS_EXECUTED` enum('Yes','No') DEFAULT 'No',
  `CREATED_DATE` datetime DEFAULT NULL,
  `DT_TO_BRANCH` enum('Y','N') NOT NULL DEFAULT 'N',
  `EXECUTED_DATE` datetime DEFAULT NULL,
  `EXCEPTION` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`SCRIPT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
