
package com.firstflight.mm.csdtosap.stktransfer;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-09-03T15:32:04.339+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class SICSDStockTransferOut_SICSDStockTransferOutPort_Client {
	/** The logger. */
	private final static Logger LOGGER = LoggerFactory
			.getLogger(SICSDStockTransferOut_SICSDStockTransferOutPort_Client.class);

    private static final QName SERVICE_NAME = new QName("http://FirstFlight.com/MM/CSDToSAP/StockTransfer", "SI_CSD_StockTransfer_OutService");

    private SICSDStockTransferOut_SICSDStockTransferOutPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SICSDStockTransferOutService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOGGER.error("SICSDStockTransferOut_SICSDStockTransferOutPort_Client::main::error::",e);
            }
        }
      
        SICSDStockTransferOutService ss = new SICSDStockTransferOutService(wsdlURL, SERVICE_NAME);
        SICSDStockTransferOut port = ss.getSICSDStockTransferOutPort();  
        
        {
        	LOGGER.debug("Invoking siCSDStockTransferOut...");
        com.firstflight.mm.csdtosap.stktransfer.DTCSDStockTransfer _siCSDStockTransferOut_mtCSDStockTransfer = new com.firstflight.mm.csdtosap.stktransfer.DTCSDStockTransfer();
        java.util.List<com.firstflight.mm.csdtosap.stktransfer.DTCSDStockTransfer.StockTransfer> _siCSDStockTransferOut_mtCSDStockTransferStockTransfer = new java.util.ArrayList<com.firstflight.mm.csdtosap.stktransfer.DTCSDStockTransfer.StockTransfer>();
        com.firstflight.mm.csdtosap.stktransfer.DTCSDStockTransfer.StockTransfer _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1 = new com.firstflight.mm.csdtosap.stktransfer.DTCSDStockTransfer.StockTransfer();
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setTimestamp("Timestamp-1937754195");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setSAPStatus("SAPStatus1207776988");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setROWNUMBER(new java.math.BigInteger("16527180125344118251702305502158927729"));
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setISSUEDATE(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-09-03T14:42:10.579+05:30"));
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setREQUISITIONNUMBER("REQUISITIONNUMBER1350693871");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setITEMTYPECODE("ITEMTYPECODE602892724");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setITEMCODE("ITEMCODE-2134444480");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setDESCRIPTION("DESCRIPTION-846048792");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setUNITOFMEASURE("UNITOFMEASURE-1613095174");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setISSUEDQUANTITY(new java.math.BigInteger("-53379002845955218446177688897624253094"));
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setISSUENUMBER("ISSUENUMBER-1966190823");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setISSUEDTOOFFICE("ISSUEDTOOFFICE-1170645166");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setISSUEOFFICEID("ISSUEOFFICEID236730758");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1.setBANO("BANO1899355526");
        _siCSDStockTransferOut_mtCSDStockTransferStockTransfer.add(_siCSDStockTransferOut_mtCSDStockTransferStockTransferVal1);
        _siCSDStockTransferOut_mtCSDStockTransfer.getStockTransfer().addAll(_siCSDStockTransferOut_mtCSDStockTransferStockTransfer);
        port.siCSDStockTransferOut(_siCSDStockTransferOut_mtCSDStockTransfer);


        }

        System.exit(0);
    }

}
