UPDATE ff_d_rate_weight_slabs SET  WEIGHT_SLAB = 1 ,DT_TO_BRANCH = 'N' WHERE RATE_WEIGHT_SLABS_ID = 37;
UPDATE ff_d_rate_weight_slabs SET  WEIGHT_SLAB = 2 ,DT_TO_BRANCH = 'N' WHERE RATE_WEIGHT_SLABS_ID = 38;
UPDATE ff_d_rate_weight_slabs SET  WEIGHT_SLAB = 6 ,DT_TO_BRANCH = 'N' WHERE RATE_WEIGHT_SLABS_ID = 39;
