package com.firstflight.fi.csdtosap.codlcliabilityRegion;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-06-03T12:32:58.454+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://FirstFlight.com/FI/CSDToSAP/CODLCLiability", name = "SI_CSD_CODLCLiability_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SICSDCODLCLiabilityOut {

    @Oneway
    @WebMethod(operationName = "SI_CSD_CODLCLiability_Out", action = "http://sap.com/xi/WebService/soap1.1")
    public void siCSDCODLCLiabilityOut(
        @WebParam(partName = "MT_CSD_CODLCLiability", name = "MT_CSD_CODLCLiability", targetNamespace = "http://FirstFlight.com/FI/CSDToSAP/CODLCLiability")
        DTCSDCODLCLiability mtCSDCODLCLiability
    );
}
