DROP TABLE IF EXISTS ff_dim_geography_pc;
CREATE TABLE `ff_dim_geography_pc` (
  `N_GEO_SKEY_PC` int(11) NOT NULL,
  `PINCODE_ID` int(11) NOT NULL,
  `PINCODE` varchar(15) DEFAULT NULL,
  `CITY_ID` int(11) DEFAULT NULL,
  `CITY_CODE` varchar(15) DEFAULT NULL,
  `CITY_NAME` varchar(150) DEFAULT NULL,
  `STATE_ID` int(11) DEFAULT NULL,
  `STATE_CODE` varchar(15) DEFAULT NULL,
  `STATE_NAME` varchar(150) DEFAULT NULL,
  `REGION_ID` int(11) DEFAULT NULL,
  `REGION_CODE` varchar(15) DEFAULT NULL,
  `REGION_NAME` varchar(150) DEFAULT NULL,
  `ZONE_ID` int(11) DEFAULT NULL,
  `ZONE_CODE` varchar(15) DEFAULT NULL,
  `ZONE_NAME` varchar(150) DEFAULT NULL,
  `LAST_UPDT_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `idx_dgpc1` (`N_GEO_SKEY_PC`),
  KEY `idx_dgpc2` (`PINCODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
