drop table `ff_f_hit_ratio_report_data_originwise`;
CREATE TABLE `ff_f_hit_ratio_report_data_originwise` (
  `DATA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOOKING_DATE` datetime DEFAULT NULL,
  `BOOKING_OFFICE` int(11) DEFAULT NULL COMMENT 'FF_D_OFFICE(OFFICE_ID)',
  `DELIVERY_OFFICE` int(11) DEFAULT NULL COMMENT 'FF_D_OFFICE (OFFICE_ID)',
  `CONSG_TYPE` int(11) DEFAULT NULL COMMENT 'FF_D_CONSIGNMENT_TYPE(CONSIGNMENT_TYPE_ID)',
  `PRODUCT` int(11) DEFAULT NULL COMMENT 'FF_D_PRODUCT(PRODUCT_ID)',
  `CATEGORY_ID` int(2) DEFAULT NULL COMMENT 'FF_D_CATEGORY_FOR_REPORTS(CATEGORY_ID). Local or National',
  `CONSIGNMENTS_BOOKED` int(11) DEFAULT NULL COMMENT 'Total Consignments booked',
  `DELIVERED_D1` int(11) DEFAULT NULL COMMENT 'Count of Consignments delivered on next day of Booking date',
  `D1_HOLIDAY` varchar(50) DEFAULT NULL COMMENT 'Name of Destination Region Holiday on next day of Booking Date',
  `DELIVERED_D2` int(11) DEFAULT NULL COMMENT 'Count of Consignments delivered on 2nd day after Booking',
  `D2_HOLIDAY` varchar(50) DEFAULT NULL COMMENT 'Name of Destination Region Holiday on 2nd day after Booking',
  `DELIVERED_D3` int(11) DEFAULT NULL COMMENT 'Count of Consignments delivered on 3rd day after Booking',
  `D3_HOLIDAY` varchar(50) DEFAULT NULL COMMENT 'Name of Destination Region Holiday on 3rd day after Booking',
  `DELIVERED_D4` int(11) DEFAULT NULL COMMENT 'Count of Consignments delivered on 4th day after Booking',
  `D4_HOLIDAY` varchar(50) DEFAULT NULL COMMENT ' Name of Destination Region Holiday on 4th day after Booking',
  `DELIVERED_D5` int(11) DEFAULT NULL COMMENT 'Count of Consignments delivered on 5th day after Booking',
  `D5_HOLIDAY` varchar(50) DEFAULT NULL COMMENT 'Name of Destination Region Holiday on 5th day after Booking',
  `DELIVERED_BEYOND_D5` int(11) DEFAULT NULL COMMENT 'ount of Consignments delivered beyond 5th day after Booking',
  `D6_HOLIDAY` varchar(50) DEFAULT NULL COMMENT 'Name of Destination Region Holiday on 6th day after Booking',
  `RTO` int(11) DEFAULT NULL COMMENT 'Count of RTO Consignments',
  `MIS` int(11) DEFAULT NULL COMMENT 'Count of MIS Consignments',
  `LOST` int(11) DEFAULT NULL COMMENT 'Count of Lost Consignments',
  PRIMARY KEY (`DATA_ID`),
  UNIQUE KEY `idx_unique` (`BOOKING_DATE`,`BOOKING_OFFICE`,`DELIVERY_OFFICE`,`CONSG_TYPE`,`PRODUCT`,`CATEGORY_ID`),
  KEY `FK_hit_ratio_report_data_originwise1` (`DELIVERY_OFFICE`),
  KEY `FK_hit_ratio_report_data_originwise5` (`BOOKING_OFFICE`),
  KEY `FK_hit_ratio_report_data_originwise2` (`CATEGORY_ID`),
  KEY `FK_hit_ratio_report_data_originwise3` (`CONSG_TYPE`),
  KEY `FK_hit_ratio_report_data_originwise4` (`PRODUCT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
